import type { SeedFullLesson } from "../types";

export const lessonChainOfInfection: SeedFullLesson = {
  courseSlug: "microbiology-1",
  moduleTitle: "Infection & Its Chain",
  lessonTitle: "The Chain of Infection",
  description: "Infection never happens by accident — it travels a six-link chain from a hiding place to a new host. Learn the links and you will see exactly where hand washing, sterile technique and clean cord care cut the story short.",
  difficulty: "Moderate",
  durationMin: 15,
  objectives: [
    "By the end you can name the six links of the chain of infection in order.",
    "By the end you can match each link to real nursing examples — blood, instruments, hands and mucous membranes.",
    "By the end you can explain how hand hygiene, PPE, safe sharps handling and sterilisation each break specific links.",
    "By the end you can apply standard precautions — and explain why they protect you with every patient, not just the infected ones.",
    "By the end you can counsel a family kindly and practically about protecting a newborn from infection.",
  ],
  tags: ["microbiology", "infection control", "standard precautions", "hand hygiene", "newborn care"],
  sourceStatus: "PROPOSED",
  sections: [
    {
      type: "callout",
      title: "Why this matters",
      body: "In Ghanaian maternity units, infection prevention is not a poster on the wall — it is the daily barrier between families and tragedy. Puerperal sepsis and newborn infection remain among the most preventable causes of maternal and neonatal death. The chain of infection is the map that shows you exactly where to stand in that barrier.",
    },
    {
      type: "text",
      title: "Infection is a journey, not an event",
      body: "Simply first: for an infection to happen, a germ must travel from where it lives to where it can multiply in a new body. That journey has six stops, and every stop is a chance to stop it.\n\nThe six links: the infectious agent (the germ itself), the reservoir (where it lives and multiplies — blood, water, skin, equipment), the portal of exit (how it leaves the reservoir), the mode of transmission (how it travels), the portal of entry (how it enters the new host), and the susceptible host (whose defences it must defeat).\n\nThink of it as a journey by tro-tro: the germ needs a starting station, a door out, a road, a door in, and a welcoming passenger at the destination. Block any one of those and the journey never completes.",
    },
    {
      type: "table",
      title: "The six links in nursing colours",
      body: "| Link | What it means | Maternity example |\n|---|---|---|\n| Infectious agent | The organism itself — bacterium, virus, fungus, parasite | HIV, hepatitis B, group B streptococcus, staphylococci |\n| Reservoir | Where the agent lives and multiplies | Blood and body fluids, the birth canal, unwashed hands, unsterilised instruments, standing water |\n| Portal of exit | The route out of the reservoir | Blood splash, droplets from a cough, vaginal secretions, fluid on a used needle |\n| Mode of transmission | The road between hosts | Contact via hands, droplets, sharps injuries, contaminated instruments |\n| Portal of entry | The route into the new host | Broken skin, mucous membranes of eyes and mouth, the umbilical cord stump |\n| Susceptible host | A person whose defences can be overwhelmed | Newborns, pregnant women, people who are malnourished or unimmunised |",
    },
    {
      type: "memory_trick",
      title: "Angry Rhinos Escape, Trampling Everything Southward",
      body: "The six links in order — Agent, Reservoir, Exit, Transmission, Entry, Susceptible host — give the initials A R E T E S. Picture Angry Rhinos Escaping, Trampling Everything Southward: a chain of destruction that fails if you break any single link. If the picture ever fades, rebuild it from the journey: who is travelling, from where, out how, by which road, in how, into whom.",
    },
    {
      type: "text",
      title: "The chain-breakers you will use every single day",
      body: "Hand hygiene is the master key: it breaks the mode of transmission for nearly every organism at once. WHO's Five Moments tell you exactly when the key turns — before touching a patient, before a clean or aseptic procedure, after body fluid exposure, after touching the patient, and after touching the patient's surroundings.\n\nGloves protect you during contact with blood and body fluids, but they are a moment-tool, not a second skin: they are changed between patients and between tasks, and they never replace hand hygiene, because hands can be contaminated while removing them.\n\nSterilisation and high-level disinfection clear the reservoir on instruments. Safe sharps practice removes the needle's road: the puncture-proof box lives beside you, and needles are never recapped by hand and never passed hand to hand. Clean cord care keeps the newborn's portal of entry sealed while it heals.",
    },
    {
      type: "text",
      title: "You are part of the chain too",
      body: "The chain of infection is not something that happens around you — you are a potential link in it. Hands are the classic road, but uniforms, phones, pens, shared trolleys and even a stethoscope can serve as reservoirs between patients.\n\nThis is why infection prevention discipline includes the small unglamorous habits: cleaning your stethoscope between patients, keeping personal items off beds and treatment surfaces, and changing out of contaminated clothing between tasks.\n\nFar from being paranoia, this is professional identity: the nurse who knows she is part of the chain is the one who keeps it broken — for her patients and for herself.",
    },
    {
      type: "clinical_pearl",
      title: "Standard precautions have no exceptions",
      body: "Standard precautions mean treating every patient's blood and body fluids as potentially infectious — not out of fear or distrust, but because you cannot reliably know who carries what, and the patient you least suspect may be the one who teaches you. The precaution works in both directions: it protects you, and it protects every future patient from anything travelling on your hands.",
    },
    {
      type: "quiz_prompt",
      title: "The cord stump and the chain",
      body: "A newborn's cord stump is a portal of entry. Which link does clean, dry cord care mainly attack — and which everyday family habit can quietly rebuild the chain?\n\nAnswer: Clean, dry cord care guards the portal of entry; applying unclean substances to the stump, or letting unwashed hands handle it, rebuilds the chain by giving agents a road straight in. That is why hand washing before touching the baby is clinical care, not etiquette.",
    },
    {
      type: "text",
      title: "Why the newborn is the most susceptible host on the ward",
      body: "A newborn's immune system is brand new. Some antibodies cross from the mother before birth and more arrive in breast milk, but the skin and mucous barriers are thin, the umbilical cord is an open door for the first days, and temperature control is fragile. Birth itself supplies portals: the cord stump, the eyes, the skin, and sometimes instruments.\n\nThis is why the newborn receives a bundle of small rituals that each look trivial: drying, warming, clean handling, clean cord care, early feeding. Together they are a fortress — and every visitor who skips hand washing walks through the gate.\n\nYour gentle voice at the bedside — 'please wash hands before you hold her, even me!' — is part of clinical care, not extra politeness.",
    },
    {
      type: "case",
      title: "The naming ceremony visitor",
      body: "Mimie, you are the student nurse on the postnatal ward. It is visiting hour, and the space around cot 3 is full of joy — Madam Dede's baby is being admired by relatives, passed from arm to arm, and kissed on the cheek by a cousin who has just mentioned 'a small cold sore' on her lip.\n\nWho is the susceptible host in this room, and which links are being passed around with the baby? With a cold sore on a lip, which portals of entry sit dangerously close to it? And what could you say to this happy family that keeps both the joy and the baby safe?\n\nNotice that nothing here requires a lecture or an alarm. You are breaking the chain with a warm sentence and a basin of water at the door: 'Please, everyone, hands washed before you hold her — and let's keep kisses off her face while that sore heals.' Kindness is a transmission-interruption strategy.",
    },
    {
      type: "quiz_prompt",
      title: "The needle on the trolley",
      body: "A used syringe and needle have been left on the delivery trolley. Which TWO links does that single object already serve — and what one action removes it from the chain?\n\nAnswer: The needle is a reservoir (holding blood) and a ready mode of transmission (a sharps injury creates a direct exit-to-entry route). Immediate disposal into the puncture-proof sharps container removes it from the chain — no recapping, no passing, no delay.",
    },
    {
      type: "text",
      title: "When the chain wins: recognising and escalating",
      body: "Sometimes infection arrives despite good care, and your task shifts from prevention to recognition. In the postnatal woman, watch for fever, abdominal or breast pain, offensive lochia, painful urination and a rising pulse. In the newborn, watch for poor feeding, fast breathing, grunting, poor temperature control, a red or offensive cord stump, or unusual sleepiness.\n\nNone of these are yours to diagnose or treat alone — they are yours to notice, measure, document and escalate. Infection moves quickly in the puerperium and in neonates, and the student who reports a shaky observation at 02:00 buys the whole team time to respond.",
    },
    {
      type: "quiz_prompt",
      title: "Name the chain, then break it",
      body: "Recall without scrolling: name the six links in order, using the rhino picture if it helps. Then say which link hand hygiene breaks — and why that one link is so powerful.\n\nAnswer: Agent, Reservoir, portal of Exit, mode of Transmission, portal of Entry, Susceptible host. Hand hygiene breaks the mode of transmission — the road most germs must travel — which is why it is the single most powerful habit in the building.",
    },
    {
      type: "summary",
      title: "In one minute",
      body: "- Infection needs a six-link chain: agent → reservoir → portal of exit → mode of transmission → portal of entry → susceptible host (AR E T E S).\n- Break ANY single link and the infection journey fails — you never need to break them all.\n- Hand hygiene at WHO's Five Moments is the master chain-breaker because it interrupts transmission for nearly all organisms.\n- Standard precautions apply to every patient, every time — you cannot know who carries what, and hands travel both ways.\n- Newborns are the ward's most susceptible hosts: thin barriers, an open cord stump, a brand-new immune system.\n- Sharps are both reservoir and road: immediate disposal in the puncture-proof container, never recapping by hand.\n- When infection appears anyway, your sequence is recognise → document → escalate; early reporting is treatment's head start.",
    },
  ],
  questions: [
    {
      topic: "Infection Control",
      type: "MCQ",
      difficulty: "Moderate",
      stem: "On a busy maternity shift, which single habit interrupts the chain of infection for the widest range of organisms and patients?",
      options: [
        "Wearing two pairs of gloves for the entire shift",
        "Closing the ward door to keep dust out of the unit",
        "Hand hygiene performed at WHO's Five Moments, with gloves used for the moments that need them",
        "Spraying the ward with disinfectant every morning",
      ],
      correctIndex: 2,
      explanation: "Hands are the most common mode of transmission in healthcare — they touch patients, equipment and surfaces in a constant loop, which is why cleaning them at the right five moments breaks the chain for bacteria, viruses and fungi alike. Glove-wearing is a supplement for specific tasks, not a substitute, because gloves get contaminated during removal and are misused when worn continuously. Environmental cleaning matters, but it cannot follow the germs the way your hands do.",
      whyOthers: {
        A: "Double-gloving all shift creates false security: gloves are contaminated by tasks, and wearing them from bed to bed or task to task can spread organisms rather than stop them.",
        B: "Dust control is environmental housekeeping, not transmission interruption — it does nothing for hands, sharps or instruments.",
        D: "Morning spraying without the Five Moments misses the hours of hand-mediated transmission that fill the day — environmental measures support, but never replace, hand hygiene.",
      },
      courseSlug: "microbiology-1",
    },
    {
      topic: "Newborn Infection Prevention",
      type: "CLINICAL_SCENARIO",
      difficulty: "Clinical Reasoning",
      stem: "Visiting hour on the postnatal ward: a newborn is being passed happily among relatives, and one who mentions 'a small cold sore on my lip' leans in to kiss the baby's cheek. Which response is most appropriate for the student nurse?",
      options: [
        "Say nothing — cold sores are so common that mentioning it would embarrass the family",
        "Kindly ask everyone to wash hands before holding the baby, gently suggest kisses stay off the baby's face until the sore heals, and mention the contact to the nurse in charge",
        "Take the baby away from the mother until all visitors have left the ward",
        "Advise the mother to stop breastfeeding until the sore has completely healed",
      ],
      correctIndex: 1,
      explanation: "Cold sores are caused by a virus that can be dangerous to newborns, and kissing is a direct route from a portal of exit (the sore) to portals of entry (the baby's skin and mouth). The chain can be broken kindly: hand hygiene for every handler, kisses deferred while the sore is active, and a report to the nurse in charge so the team can watch for any signs in the baby. Preventing infection and preserving the joy of the family are not opposites — the tone is part of the treatment.",
      whyOthers: {
        A: "Silence keeps the transmission route wide open — embarrassment is a small price compared with the risk of serious newborn infection.",
        C: "Separating mother and baby is disproportionate and harmful to bonding and feeding; the chain can be broken without isolating anyone.",
        D: "Breastfeeding is precisely what supports the baby's immune defences — stopping it would remove protection while doing nothing about the kissing route.",
      },
      courseSlug: "microbiology-1",
    },
    {
      topic: "PPE and Sequence",
      type: "ORDERING",
      difficulty: "Moderate",
      stem: "You are about to assist with a procedure that carries a splash risk. Put the sequence of events in the correct order.",
      options: [
        "Perform hand hygiene",
        "Don the PPE chosen for the task, including eye protection if splashes are expected",
        "Carry out the procedure",
        "Remove the PPE in the order you were trained, then perform hand hygiene again",
      ],
      explanation: "Clean hands must come before touching any PPE, because contaminated hands transfer organisms onto the gloves and gown you are about to rely on. PPE goes on second so that you are protected throughout the procedure, which sits third. Removal comes after the procedure — in the trained sequence, carefully, because PPE surfaces are now contaminated — and hand hygiene comes last to clear whatever reached your skin during removal. The two hand-hygiene moments are the bookends of every procedure, not optional extras.",
      whyOthers: {
        A: "Hand hygiene must precede donning — putting gloves over dirty hands seals the contamination in and spreads it to every surface you then touch.",
        B: "Donning must precede the procedure — PPE worn after the exposure has missed the exposure entirely.",
        C: "The procedure belongs between donning and doffing — performing it before protection exposes you, and performing it after removal makes no sense.",
        D: "Doffing and the second hand hygiene must come last — PPE surfaces are contaminated by then, and hands need cleaning after removal precisely because gloves fail invisibly.",
      },
      courseSlug: "microbiology-1",
    },
    {
      topic: "Standard Precautions",
      type: "TRUE_FALSE",
      difficulty: "Easy",
      stem: "True or false: standard precautions apply to every patient, not only those with a known infection.",
      options: [
        "True",
        "False",
        "True, but only during declared outbreaks",
        "True only for patients who currently have a fever",
      ],
      correctIndex: 0,
      explanation: "Standard precautions exist precisely because you cannot know everyone's status: blood-borne infections can be silent for years, testing may be incomplete, and results may not reach you at the bedside. Treating all blood and body fluids as potentially infectious protects you and every subsequent patient from whatever travels on hands and equipment. Additional precautions are added for specific diagnoses — but the baseline never switches off.",
      whyOthers: {
        B: "False would confine precautions to known infections — historically, that exact assumption is how healthcare workers and patients were infected by unsuspected carriers.",
        C: "Outbreaks justify extra, transmission-based precautions on top of the standard baseline; they never define when the baseline itself applies.",
        D: "Fever is only one sign of some infections and is absent in many transmissible ones, including silent blood-borne viruses — status unknown is the working assumption of standard precautions.",
      },
      courseSlug: "microbiology-1",
    },
    {
      topic: "Sharps Safety",
      type: "MCQ",
      difficulty: "Hard",
      stem: "After a delivery, you are clearing the trolley when a used needle pierces your glove and skin. What is the most appropriate immediate action for a student nurse?",
      options: [
        "Squeeze the wound hard to expel as much blood as possible, then finish your tasks quietly",
        "Wash the site with soap and running water, report immediately to your supervisor, and follow the facility's post-exposure management pathway",
        "Wait until the end of the shift, then report only if you remember the patient's status",
        "Report the injury only if the patient is known to be HIV positive",
      ],
      correctIndex: 1,
      explanation: "A sharps injury is a potential portal of exit meeting a portal of entry — the chain completing in one accident. The immediate steps are washing (not squeezing, which can drive fluid deeper and damage tissue), then prompt reporting so post-exposure assessment can happen within the window where preventive measures are most effective. Every facility has a post-exposure pathway; your job is to know that it exists and to activate it immediately, for every exposure, with every patient status.",
      whyOthers: {
        A: "Squeezing can express fluid deeper into tissues and injure them further — washing with soap and running water is the taught first response, and finishing tasks delays reporting.",
        C: "Post-exposure care is time-sensitive; a silent injury discovered hours later loses options — the report belongs to the minute, not the shift.",
        D: "Patient status is frequently unknown at the moment of injury, and the pathway exists precisely so that unknown status triggers assessment, not inaction.",
      },
      courseSlug: "microbiology-1",
    },
    {
      topic: "Newborn Infection Prevention",
      type: "MULTI_SELECT",
      difficulty: "Moderate",
      stem: "A healthy newborn is on the postnatal ward. Select all measures that break the chain of infection for this baby.",
      options: [
        "Everyone washes hands before handling the baby",
        "The cord stump is kept clean and dry according to facility protocol",
        "Early and exclusive breastfeeding is supported",
        "Routine antibiotics are given to every newborn on the ward",
      ],
      correctIndexes: [0, 1, 2],
      explanation: "Hand washing by every handler interrupts transmission — the road most germs travel to reach the baby. Clean, dry cord care protects the baby's most vulnerable portal of entry during healing. Breastfeeding delivers maternal antibodies and colonises the gut protectively, strengthening the most susceptible host. Together these three simple habits are the backbone of newborn infection prevention.",
      whyOthers: {
        D: "Blanket antibiotics for well newborns are not prevention — they are misuse: they add no protection against the main transmission routes, promote resistance, and belong to medical prescribing decisions for specific indications only.",
      },
      courseSlug: "microbiology-1",
    },
  ],
  flashcards: [
    {
      topic: "Chain of Infection",
      front: "Name the six links of the chain of infection in order.",
      back: "Infectious agent → reservoir → portal of exit → mode of transmission → portal of entry → susceptible host. Mnemonic: Angry Rhinos Escape, Trampling Everything Southward.",
    },
    {
      topic: "Infection Control",
      front: "Which link does hand hygiene break, and why is that so powerful?",
      back: "The mode of transmission — the road between hosts. Because hands carry nearly every type of organism, breaking this one link stops almost the whole chain.",
    },
    {
      topic: "Hand Hygiene",
      front: "What are WHO's Five Moments for hand hygiene?",
      back: "Before touching a patient; before a clean/aseptic procedure; after body fluid exposure; after touching the patient; after touching the patient's surroundings.",
    },
    {
      topic: "Newborn Infection Prevention",
      front: "Why is the newborn the most susceptible host on the ward?",
      back: "Thin skin and mucous barriers, an open portal of entry at the cord stump, fragile temperature control, and an immune system that relies on maternal passive immunity.",
    },
    {
      topic: "Standard Precautions",
      front: "What do standard precautions assume?",
      back: "That every patient's blood and body fluids are potentially infectious — precautions apply with every patient, every time, because status is often unknown or silent.",
    },
  ],
  sources: [
    {
      organization: "World Health Organization",
      title: "WHO Guidelines on Hand Hygiene in Health Care",
      year: "2009",
      url: "https://www.who.int/publications/i/item/9789241597906",
      note: "Educational source — verify current WHO guidance.",
    },
    {
      organization: "World Health Organization",
      title: "Guidelines on core components of infection prevention and control programmes at the national and acute health care facility level",
      year: "2016",
      note: "Educational source — verify current edition.",
    },
    {
      organization: "Ghana Health Service",
      title: "National Infection Prevention and Control Guidelines",
      note: "Educational reference — always consult the current national document and your facility's protocol.",
    },
    {
      organization: "Elsevier",
      title: "Myles Textbook for Nurses",
      year: "2020 (17th edition)",
      note: "Educational source — verify current edition.",
    },
  ],
};
