import type { SeedFullLesson } from "../types";

export const lessonVitalSigns: SeedFullLesson = {
  courseSlug: "foundations-nursing-1",
  moduleTitle: "Vital Signs & Observation",
  lessonTitle: "Taking Vital Signs Without Missing the Story",
  description: "A temperature of 37.8 °C is just a number — until you know it was 36.6 °C two hours ago. This lesson teaches you to take vital signs the way midwives read them: as a story told in trends.",
  difficulty: "Moderate",
  durationMin: 18,
  objectives: [
    "By the end you can list the core vital signs and explain what each one monitors.",
    "By the end you can describe commonly taught adult reference ranges and explain why a single 'normal' value never guarantees stability.",
    "By the end you can explain why respirations are counted without warning, and why a full minute matters.",
    "By the end you can interpret a set of observations as a trend and identify which finding is most urgent.",
    "By the end you can describe the escalation pathway when observations suggest a woman is deteriorating.",
  ],
  tags: ["vital signs", "observations", "deterioration", "escalation", "clinical skills"],
  sourceStatus: "PROPOSED",
  sections: [
    {
      type: "callout",
      title: "Why this matters",
      body: "In Ghanaian facilities, vital signs are charted on temperature charts (TPR sheets) and, during labour, on the partograph — and senior midwives make decisions from what you record. The skill is not placing the thermometer; it is noticing which number is telling you something, and saying it out loud early. That is how a student midwife helps save a life.",
    },
    {
      type: "text",
      title: "Vital signs are chapters, not sentences",
      body: "Temperature, pulse, respiration and blood pressure — plus oxygen saturation and pain in modern practice — are the body's rolling reports on its most urgent projects: fighting infection, circulating blood, breathing and perfusing tissues.\n\nEach sign is a chapter of the same book. A single raised temperature is one chapter. A raised temperature with a pulse of 118 and respirations of 26 is a different book entirely — the story of a body fighting something systemic.\n\nYour job as a student is two-layered: measure accurately, then interpret honestly. Machines cannot do the second part, and senior staff cannot do either part if you never tell them.",
    },
    {
      type: "table",
      title: "The core vital signs and what they monitor",
      body: "| Sign | What it monitors | Commonly taught adult reference range | Direction that flags trouble |\n|---|---|---|---|\n| Temperature | Thermoregulation and infection | about 36.5–37.5 °C | 38.0 °C or higher; or below 36.0 °C |\n| Pulse | Cardiac workload and compensation | about 60–100 beats per minute | Rising trend; sustained above 100 at rest |\n| Respiration | Gas exchange and respiratory effort | about 12–20 breaths per minute | 24 or more, or new breathlessness |\n| Blood pressure | Perfusion pressure | commonly quoted around 100–120 systolic | Falling trend, or a rise above her booking baseline |\n| Oxygen saturation | Blood oxygenation | 95–100% on room air | Below 95% needs review and escalation |\n| Pain | Comfort and tissue stress — assessed, not machine-measured | scored 0–10 or by behaviour | New pain, or pain rising from her baseline |\n\nThese ranges are teaching references, not verdicts — always interpret against the woman's own booking baseline and your facility's charts. In pregnancy the norms shift: the pulse rises slightly and blood pressure falls in the second trimester, which is exactly why booking observations matter so much.",
    },
    {
      type: "quiz_prompt",
      title: "Read the trend, not the moment",
      body: "Look at this series across three checks: temperature 36.6 → 37.4 → 38.2 °C; pulse 84 → 96 → 110; respirations 18 → 20 → 24. Every value in the last set is only borderline on its own. Why is the pattern urgent anyway?\n\nAnswer: All three signs are moving together in the direction of systemic infection — trends outrank single values, and a parallel rise in temperature, pulse and respiration is the classic trajectory of sepsis. This pattern must be reported now, not at the next round.",
    },
    {
      type: "text",
      title: "The trick with respirations",
      body: "Respirations are the most honest vital sign and the easiest to ruin. The moment a patient knows you are counting her breathing, she changes it — consciously or not.\n\nSo the profession has a quiet trick: keep your fingers on the wrist as if you are still counting the pulse, and count breaths instead. Watch the chest rise. One rise and fall is one breath. Count for a full minute, because breathing is naturally uneven — a 15-second count multiplied by four can miss deep swings.\n\nNote the quality, not just the speed: is the breathing shallow? Noisy? Is she using her shoulders? Is she pausing to speak in broken sentences? That description is often worth more than the number.",
    },
    {
      type: "text",
      title: "Pulse: what your fingers should learn",
      body: "Feel with your fingertips, never your thumb — the thumb carries its own pulse and will quietly fool you. Count for a full minute when the rhythm is irregular or the rate is the very thing you are tracking.\n\nReport three things, not one: the rate (beats per minute), the rhythm (regular or irregular), and the strength (bounding, normal, or weak and thready). A weak, thready pulse at a 'normal' rate is carrying a different message from a strong one.\n\nAnd remember that in pregnancy the resting pulse runs naturally a little faster than before conception — one more reason the booking baseline, not the textbook average, is your real reference point.",
    },
    {
      type: "clinical_pearl",
      title: "The pulse you should tell someone about",
      body: "A pulse of 96 in a woman whose booking pulse was 64 is a 50% rise — a bigger story than an isolated 104 in a woman whose baseline is already 92. Always read observations against her own baseline, and write the baseline where the next shift can see it.",
    },
    {
      type: "memory_trick",
      title: "PQRST: the story behind a symptom",
      body: "When a woman reports pain — or any new symptom — run PQRST: what Provokes or Palliates it? what is its Quality? which Region does it affect and does it Radiate? how Severe (0–10)? and what is its Timing (start, duration, pattern)? One structured sweep turns 'she says she is not well' into a story you can hand over.",
    },
    {
      type: "text",
      title: "What deterioration looks like before it announces itself",
      body: "Physiology tends to fail from the outside in: the respiratory rate rises first, then the pulse, and blood pressure falls late. That sequence is why respiratory rate is called the most sensitive early sign — and, famously, the most skipped or guessed number on the chart.\n\nA woman quietly developing infection may simply look 'just tired'. So between observations, ask three questions: how does she feel compared to this morning? is she drinking and passing urine? and has anything new started — headache, faintness on sitting up, feeling cold when everyone else is warm? Her answers often arrive before her numbers.\n\nWhen your instinct and the chart disagree, trust both enough to escalate. 'Something is not right with Madam Ama, and here are her numbers' is a completely legitimate thing to say to the midwife in charge — senior staff would always rather be called early than late.",
    },
    {
      type: "case",
      title: "The quiet postnatal shift",
      body: "Mimie, you are the student midwife on the postnatal ward at 22:00. Madam Efua delivered yesterday evening. Her 18:00 observations were T 37.0 °C, P 92, R 18, BP 118/74, noted as 'mild tachycardia — monitor'. At 22:00 you find T 38.1 °C, P 118, R 24, BP 112/70. She is awake but oddly quiet, says she feels 'cold inside', and has wrapped herself in two wrappers.\n\nWhich observation must be reported immediately — and why is the answer the pattern rather than any single value? What is the difference between documenting 'pyrexia 38.1' and documenting 'temperature rising over 4 hours with parallel rise in pulse and respiration'? The midwife asks whether she is breastfeeding — what infection clues should you be ready to help explore (breast tenderness, lochia odour, wound pain, urinary symptoms)? And where does your role stop — whose job are the diagnosis and the treatment plan?\n\nThis is the shape of early postnatal sepsis: quiet, polite, and moving in one direction. Your measurement and your escalation are the treatment's head start.",
    },
    {
      type: "quiz_prompt",
      title: "The 15-second shortcut",
      body: "You count a patient's respirations for 15 seconds and get 6 breaths — quick math says 24 per minute. Why is that shortcut risky, and what should you do instead?\n\nAnswer: Breathing is naturally irregular, so a short sample can miss runs of deep or shallow breaths — the full-minute count is the honest one. Keep your fingers on her wrist as if still counting the pulse so she does not consciously alter her breathing, and count for the whole 60 seconds.",
    },
    {
      type: "text",
      title: "Charting: the TPR sheet and partograph are communication tools",
      body: "During labour, your observations live on the partograph; on the ward, in many Ghanaian facilities, they live on the TPR (temperature–pulse–respiration) sheet. These charts are not filing — they are your shift's argument to the next shift.\n\nChart at the times your facility requires, chart the actual value (never the value you expected), and never chart ahead. If a round was missed, write that honestly — a gap is information, and an invented number is a hazard.\n\nWhen you hand over, hand over trends. 'She was 88 at 14:00 and she is 112 now' is a sentence that moves people; 'her obs are on the chart' is not.",
    },
    {
      type: "quiz_prompt",
      title: "Early bird, late bird",
      body: "One-line recall: which vital sign usually changes first when a patient begins to deteriorate, and which one is famous for falling late?\n\nAnswer: The respiratory rate rises first and is the most sensitive early marker of deterioration; blood pressure is the late mover — which is why a 'normal' blood pressure never reassures you on its own.",
    },
    {
      type: "summary",
      title: "In one minute",
      body: "- Core vital signs: temperature, pulse, respiration and blood pressure — with oxygen saturation and pain assessed alongside.\n- A single value answers a single question; the trend answers the important one — which direction is she moving?\n- Count respirations for a full minute, without announcing it, fingers still resting on the wrist.\n- Read every observation against the woman's own booking baseline, not just population ranges.\n- Respiratory rate is the earliest mover in deterioration; blood pressure is the famous late one.\n- Sepsis's first signature is a parallel rise in temperature, pulse and respiration — report patterns early.\n- In labour, observations live on the partograph; on the ward, on the TPR sheet. Chart honestly, hand over trends, escalate early.",
    },
  ],
  questions: [
    {
      topic: "Respiration Assessment",
      type: "MCQ",
      difficulty: "Easy",
      stem: "You are counting a patient's respirations during routine observations. Which technique gives the most honest reading?",
      options: [
        "Tell her you are counting her breaths, so she can cooperate with the assessment",
        "Keep your fingers on her wrist as though still counting the pulse, and count chest rises for a full minute without announcing it",
        "Count for 15 seconds and multiply by four to save time on a busy shift",
        "Ask her to take a few deep breaths so the pattern is easier to see",
      ],
      correctIndex: 1,
      explanation: "The moment patients know their breathing is being counted, they consciously or unconsciously alter its rate and depth — which destroys the very measurement you are taking. Keeping your fingers on the wrist disguises the count, and the full minute captures breathing's natural irregularity. This small piece of theatre is a genuine clinical skill, taught in fundamentals courses everywhere.",
      whyOthers: {
        A: "Announcing the count invites the patient to control her breathing — the number stops reflecting her true resting state.",
        C: "Breathing is irregular; a 15-second sample can easily miss a run of shallow or deep breaths and mislead you at exactly the moment accuracy matters.",
        D: "Asking for deep breaths changes the thing you are measuring — you would be documenting her obedience, not her physiology.",
      },
      courseSlug: "foundations-nursing-1",
    },
    {
      topic: "Deterioration Recognition",
      type: "CLINICAL_SCENARIO",
      difficulty: "Clinical Reasoning",
      stem: "Four hours after a normal birth, a woman's observations read: temperature 38.1 °C, pulse 118, respirations 24, blood pressure 112/70, pain score 3/10. Which finding must you report first?",
      options: [
        "The pain score, because pain is often called the fifth vital sign",
        "The pattern of temperature, pulse and respiration rising together, which suggests possible early sepsis and needs immediate escalation",
        "The blood pressure, because 112/70 is below the expected postpartum range",
        "The temperature alone, since 38.1 °C is the only objectively abnormal value",
      ],
      correctIndex: 1,
      explanation: "Individually, each value is borderline; together, they form the classic early signature of systemic infection — rising temperature, tachycardia and tachypnoea moving in step. The normal blood pressure is the least reassuring number here because young women compensate well, and compensation hides in the pulse. Reporting the pattern, not the single fever, is what triggers timely review and treatment.",
      whyOthers: {
        A: "Pain deserves assessment and relief, but a score of 3/10 is not the urgency here — it does not explain a rising pulse and respiration.",
        C: "112/70 is a normal-range blood pressure; treating it as the priority finding mistakes the least sensitive sign for the most important one.",
        D: "Focusing only on the temperature misses the point that trends and combinations — not single values — predict deterioration.",
      },
      courseSlug: "foundations-nursing-1",
    },
    {
      topic: "Compensation",
      type: "TRUE_FALSE",
      difficulty: "Moderate",
      stem: "True or false: a blood pressure within the woman's normal range rules out significant ongoing blood loss.",
      options: [
        "True",
        "False",
        "True, but only if her pulse is also normal",
        "True, but only in the first hour after delivery",
      ],
      correctIndex: 1,
      explanation: "Blood pressure is the late mover: baroreceptor reflexes raise the heart rate and constrict vessels to hold pressure almost until the compensation fails. A 'normal' blood pressure can therefore coexist with serious volume loss — the pulse trend, skin colour and behaviour are the earlier witnesses. Even a normal pulse does not fully rule out gradual loss, because healthy young women compensate remarkably well.",
      whyOthers: {
        A: "This is the single most dangerous assumption in postpartum observation — pressure is maintained at the price of the pulse until it suddenly is not.",
        C: "A normal pulse is more reassuring than a normal pressure alone, but compensation can keep both deceptively steady during slow ongoing loss — trends and the whole picture govern.",
        D: "The first hour is precisely when most primary postpartum haemorrhage occurs, and compensation is at its most deceptive then.",
      },
      courseSlug: "foundations-nursing-1",
    },
    {
      topic: "Antenatal Observations",
      type: "MCQ",
      difficulty: "Moderate",
      stem: "At 34 weeks, a woman whose booking blood pressure was 124/78 now records 152/98 and mentions a persistent headache since this morning. What does this observation set most suggest, and what does it demand?",
      options: [
        "Normal pregnancy-related fluctuation; recheck at her next routine visit",
        "A significant rise from her own baseline with a warning symptom — a hypertensive disorder of pregnancy must be considered, so report immediately for same-day review by the midwife or clinician in charge",
        "White-coat effect; reassure her and repeat the reading after a chat",
        "Early labour; prepare her for transfer to the labour ward",
      ],
      correctIndex: 1,
      explanation: "The key comparison is with her own booking baseline: a rise of nearly 30 mmHg systolic with a headache is the pattern that raises concern for pre-eclampsia and its complications, which can escalate quickly. This is a same-day-review finding, not a next-visit finding, and the decision belongs to senior staff — your task is accurate measurement, the symptom history and immediate reporting. Headache in this context is a symptom, not a trivial complaint.",
      whyOthers: {
        A: "Waiting for the next routine visit risks missing a condition that can progress to eclampsia within hours to days — rises from personal baseline are never 'normal fluctuation'.",
        C: "White-coat effect produces small, variable rises without warning symptoms; a 28-point sustained rise with headache deserves full assessment, not reassurance.",
        D: "Hypertension with headache is not a sign of labour — treating it as such delays the review that protects both mother and baby.",
      },
      courseSlug: "foundations-nursing-1",
    },
    {
      topic: "Escalation",
      type: "CLINICAL_SCENARIO",
      difficulty: "Hard",
      stem: "02:00 on the postnatal ward. Your observations for Madam Afia show pulse 112 (booking 72), respirations 24, temperature 37.9 °C, blood pressure 106/64. She is quiet and looks pale. As the student midwife, what is your most appropriate action?",
      options: [
        "Chart the values and wait for the 06:00 round so you do not wake anyone unnecessarily",
        "Wake the midwife in charge now, present the trend and your concern, and stay with the woman while she is reviewed",
        "Give her extra fluids by mouth and recheck in one hour",
        "Reassure her that each value is only borderline and encourage her to sleep",
      ],
      correctIndex: 1,
      explanation: "A rising pulse from her own baseline, tachypnoea, low-grade fever and pallour at 02:00 is a deterioration pattern — and deterioration at night moves fastest precisely because it is least watched. The student's scope is to observe, document and escalate: waking the midwife in charge is not an interruption, it is the system working. Presenting the trend ('her pulse has climbed from 72 to 112') is far stronger than presenting numbers.",
      whyOthers: {
        A: "Waiting four hours on a rising trend converts a treatable early problem into an emergency — nobody is ever blamed for calling early.",
        C: "Oral fluids are supportive but cannot address unidentified blood loss or infection, and an hour of delay may be the hour that mattered.",
        D: "'Each value borderline' is the trap of reading numbers in isolation — the pattern, the pallor and the behaviour are all saying the same thing.",
      },
      courseSlug: "foundations-nursing-1",
    },
    {
      topic: "Observation Practice",
      type: "MULTI_SELECT",
      difficulty: "Moderate",
      stem: "Select all habits that make observations trustworthy.",
      options: [
        "Counting respirations for a full minute with your fingers resting on the wrist",
        "Recording the value you expected when the device gives an odd reading",
        "Comparing today's values with the woman's own booking baseline",
        "Handing over trends rather than isolated numbers",
      ],
      correctIndexes: [0, 2, 3],
      explanation: "The full-minute disguised respiratory count reflects true resting breathing; comparing against her own baseline turns population ranges into personal medicine; and trend-based handover tells the next shift which direction the story is moving. Together they transform observation from data collection into clinical communication. An odd device reading is a signal to recheck the patient and the device — never to quietly write a tidier number.",
      whyOthers: {
        B: "Writing the expected value instead of the observed one is falsification — it hides the very deviation that might have saved a life, and it is a professional offence.",
      },
      courseSlug: "foundations-nursing-1",
    },
    {
      topic: "Deterioration Recognition",
      type: "MCQ",
      difficulty: "Hard",
      stem: "Which observation is LEAST likely to be an early warning sign that a patient is deteriorating?",
      options: [
        "A respiratory rate rising from 16 to 24 across three observations",
        "New confusion noted while you help her to the bathroom",
        "A blood pressure that has not changed from her booking baseline",
        "A pulse climbing stepwise across consecutive checks",
      ],
      correctIndex: 2,
      explanation: "Early deterioration whispers through the most sensitive channels first: respiratory rate, mental state and heart rate. Blood pressure is the last to move, so an unchanged pressure is the least informative early finding — it cannot rule anything out, but it is the least likely to be the first sign of trouble. The exam-wise reading: stable BP is not a warning sign, but it is also not a promise.",
      whyOthers: {
        A: "A stepwise rise in respiratory rate is the single most sensitive early marker of deterioration — this is a warning that demands attention.",
        B: "New confusion reflects cerebral perfusion and oxygenation failing — subtle mental state change is a well-recognised early red flag.",
        D: "A stepwise pulse climb is classic compensation in action — often the earliest evidence of blood loss or infection.",
      },
      courseSlug: "foundations-nursing-1",
    },
  ],
  flashcards: [
    {
      topic: "Vital Signs",
      front: "Why is respiratory rate called the most sensitive early marker of deterioration?",
      back: "It usually rises before the other vital signs change, while blood pressure classically falls late — so a climbing respiratory rate is an early red flag that is often missed or guessed.",
    },
    {
      topic: "Vital Signs",
      front: "How do you count respirations without the patient changing her breathing?",
      back: "Keep your fingers on the wrist as if still counting the pulse, watch the chest rise, and count for a full 60 seconds without announcing what you are doing.",
    },
    {
      topic: "Pain Assessment",
      front: "What does PQRST stand for?",
      back: "Provocation/Palliation, Quality, Region/Radiation, Severity, Timing — a structured sweep for assessing pain or any new symptom.",
    },
    {
      topic: "Vital Signs",
      front: "Why compare observations with the booking baseline?",
      back: "Pregnancy shifts the norms (pulse up slightly, blood pressure down in the second trimester), and a change from her own normal is a more sensitive warning than any population range.",
    },
    {
      topic: "Deterioration Recognition",
      front: "What pattern is the classic early signature of sepsis on the observation chart?",
      back: "Temperature, pulse and respiratory rate all rising together across consecutive observations — report the pattern, not just the fever.",
    },
  ],
  sources: [
    {
      organization: "Elsevier",
      title: "Potter and Perry: Fundamentals of Nursing",
      year: "2021 (10th edition)",
      note: "Educational source — verify current edition for vital sign technique and ranges.",
    },
    {
      organization: "World Health Organization",
      title: "WHO recommendations for prevention and treatment of peripartum infections",
      year: "2015",
      note: "Educational source — recognise infection early and follow current local protocols.",
    },
    {
      organization: "Nursing and Midwifery Council of Ghana",
      title: "Professional standards for midwifery practice and conduct",
      note: "Educational reference — consult current NMC Ghana publications for exact documents.",
    },
    {
      organization: "Elsevier",
      title: "Myles Textbook for Midwives",
      year: "2020 (17th edition)",
      note: "Educational source — verify current edition.",
    },
  ],
};
