import type { SeedFullLesson } from "../types";

export const lessonNewbornAssessment: SeedFullLesson = {
  courseSlug: "neonatal-nursing",
  moduleTitle: "The First Minutes",
  lessonTitle: "Your First Newborn Assessment",
  description: "The first minutes of a baby's life are the most examined minutes in medicine — and the most misunderstood. Learn what your eyes, hands and ears are actually checking for, and how a little scoring tool called Apgar turns instinct into numbers.",
  difficulty: "Moderate",
  durationMin: 20,
  objectives: [
    "By the end you can describe the immediate assessment sequence for a newborn at birth.",
    "By the end you can score the five Apgar components and total them at 1 and 5 minutes.",
    "By the end you can explain what Apgar does and does not tell you about a baby.",
    "By the end you can list the newborn danger signs that demand immediate escalation.",
    "By the end you can describe the immediate care bundle — dry, warm, airway position, cord care — as it is taught for supervised practice.",
    "By the end you can counsel a mother on keeping her newborn warm, fed and safe.",
  ],
  tags: ["newborn", "Apgar score", "immediate care", "danger signs", "neonatal assessment"],
  sourceStatus: "GCU_ALIGNED",
  sections: [
    {
      type: "callout",
      title: "Why this matters",
      body: "In Ghana, the first hours of life carry some of the highest neonatal risk of the whole journey — and the student at the bedside is often the first pair of trained eyes a baby meets. This lesson is the theory; the skills are learned with a preceptor, a warm blanket and many repetitions. Your job from day one is to know exactly what you are looking at.",
    },
    {
      type: "text",
      title: "The first minute is a sequence, not a scramble",
      body: "Simply first: at birth the newborn needs three things in the first seconds — to be dried, to be warm, and to breathe. So immediate assessment runs together with immediate care: dry the baby (drying stimulates breathing and prevents heat loss), look and listen for the cry, tone, breathing and colour, keep the airway open in a neutral position, and — if the baby is well — hold baby skin-to-skin with mother.\n\nIn your first sixty seconds you are really answering three questions: Is the baby breathing or crying well? Is the tone good — moving, flexing, resisting a little? And is the colour right — pink at the centre, with blue hands and feet usually acceptable?\n\nA well baby answers all three and then mostly needs warmth, the breast, and to be left alone with its mother. A baby that falters on any of the three needs help — and calling for that help is the first step of giving it.",
    },
    {
      type: "table",
      title: "The Apgar score at 1 and 5 minutes",
      body: "| Sign | 0 | 1 | 2 |\n|---|---|---|---|\n| Appearance (colour) | Blue or pale all over | Body pink, hands and feet blue | Completely pink |\n| Pulse (heart rate) | Absent | Below 100 beats per minute | 100 or above |\n| Grimace (response to stimulation) | No response | Grimace or feeble response | Coughs, sneezes or pulls away vigorously |\n| Activity (muscle tone) | Limp and floppy | Some flexion of arms and legs | Active movement, well flexed |\n| Respiration (breathing) | Absent | Slow, irregular, weak cry | Strong cry, regular breathing |\n\nEach component is scored 0, 1 or 2, then summed. Scored at 1 minute and 5 minutes; if the 5-minute score remains low, scoring is usually repeated every 5 minutes while the team keeps working. As a general frame, 7–10 is considered reassuring, 4–6 moderate, 0–3 low — but remember that the team's response is guided by the baby in front of them, never by the number alone.",
    },
    {
      type: "quiz_prompt",
      title: "The heart rate question",
      body: "A newborn at 1 minute has a heart rate of 96 beats per minute. What does the Pulse component earn — and why does the heart rate carry so much weight with the team?\n\nAnswer: It scores 1, because the rate is below 100. The heart rate is the anchor of newborn assessment — a slow heart rate tells the team the circulation may need support, which is why listening (or feeling the cord stump for pulsation) comes first in a quiet baby.",
    },
    {
      type: "memory_trick",
      title: "APGAR spells itself",
      body: "The score's own name is your mnemonic — APGAR: Appearance, Pulse, Grimace, Activity, Respiration — each scored 0, 1 or 2, at 1 and 5 minutes. If the letters ever scramble, remember the question behind them: how does this baby look, pump, react, move and breathe, right now?",
    },
    {
      type: "text",
      title: "What Apgar means — and what it does not",
      body: "The Apgar score is a snapshot of how the baby is doing at specific minutes — a shared language for the whole team, and one input into decisions about support. The 1-minute score often prompts the first decisions about breathing help; later scores track whether the baby is responding.\n\nWhat Apgar is not: a prophecy. A low 1-minute score frequently improves with the basic steps, and many babies with rocky first minutes grow perfectly well. Equally, an Apgar of 10 is not a discharge from care — warmth, feeding, cord care and the medicines given after birth (such as vitamin K, per local standing orders) still happen, and vigilance continues.\n\nLearn to feel a baby's condition with your eyes and hands first, then let the score confirm. The number is a summary, not a substitute for the baby in front of you.",
    },
    {
      type: "clinical_pearl",
      title: "Pink hands don't count; pink centres do",
      body: "Peripheral cyanosis — blue hands and feet on an otherwise pink, vigorous baby in the first hours — is common and usually benign. Central cyanosis — a blue tongue, lips or face — is an emergency: the baby needs help breathing now, and the senior clinician must be called immediately. Same colour word, two different worlds — always check the centre.",
    },
    {
      type: "text",
      title: "The first hours: warmth, feeding and the quiet newborn",
      body: "After the golden first minutes, assessment becomes a rhythm of quiet checks. Warmth is physiology: a wet newborn loses heat fast, cold stress raises oxygen needs and undermines feeding — dry, warm, skin-to-skin, with a cap on the head, is clinical care, not comfort garnish.\n\nFeeding behaviour is the newborn's fuel gauge: a baby who wakes, roots, attaches and swallows is behaving like a well baby. A baby who is 'too sleepy to feed' by six to twelve hours is sending up a flare.\n\nYour sweep over the first hours: tone and movement, colour, breathing pattern, temperature, feeding behaviour, cord stump, urine and stool passage — documented and compared, because newborns change quickly and your serial observations are the monitoring.",
    },
    {
      type: "text",
      title: "Danger signs: the list that outranks everything",
      body: "These findings in a newborn demand immediate escalation — call the senior midwife or clinician, never wait for the next round: fast breathing (around 60 breaths per minute or more), grunting with each breath, chest indrawing, central cyanosis, an unusually cold or hot baby, poor or absent feeding, convulsions or abnormal movements, unusual sleepiness or floppiness, and a red, spreading or offensive cord stump.\n\nThese map closely onto the newborn danger signs taught to frontline workers in Ghana and across WHO programmes — the shared grammar of 'this baby needs review now'. Recognition is the entry ticket; response belongs to the whole team. Say the finding, say the time, and stay with the baby.",
    },
    {
      type: "case",
      title: "The baby who arrived quiet",
      body: "Mimie, you are the student midwife at a facility birth. Baby Selasi is born at 01:20 after a long second stage. The midwife is at the warmer drying and stimulating him, and she asks you to note times and be her second pair of hands. At 1 minute: his body is mostly pink with blue hands and feet; the heart rate is 110; he grimaces to stimulation; his arms and legs show some flexion; his cry is weak and breathing irregular.\n\nScore the 1-minute Apgar, component by component. At 5 minutes he is completely pink, heart rate 140, he coughs when the mouth is cleared, moves actively and cries strongly — score that too. What does the improvement from the first score to the second actually mean, and what does it NOT mean? And what are your non-negotiable jobs as the student in this room?\n\nThe 1-minute score: Appearance 1, Pulse 2, Grimace 1, Activity 1, Respiration 1 — a total of 6, moderate. The 5-minute score: 2 + 2 + 2 + 2 + 2 = 10. The climb means the basic support worked and the baby is now transitioning well — it does not cancel the watch: warmth, feeding, cord care and the full first-hours sweep continue, and the events are documented clearly. In real practice the team calls these numbers aloud while working — that is what Apgar was designed to be: a shared language under pressure, scored in seconds.",
    },
    {
      type: "quiz_prompt",
      title: "Score it yourself",
      body: "At 5 minutes: body pink with blue hands and feet; heart rate 130; coughs when stimulated; actively flexed and moving; strong cry with regular breathing. What is the total — and which component are you most tempted to over-score?\n\nAnswer: 1 + 2 + 2 + 2 + 2 = 9. The temptation is Appearance — blue hands and feet score 1, not 2, because only a completely pink baby earns the 2.",
    },
    {
      type: "text",
      title: "Immediate care: the bundle you will practise under supervision",
      body: "After a well birth, the immediate care bundle runs: dry and stimulate; assess; keep warm with skin-to-skin and a cap; position the airway; and provide cord care. WHO guidance favours clean, dry cord care in settings where it works, with chlorhexidine used in high-mortality settings — Ghana's national programme includes chlorhexidine for the cord, so learn exactly how your facility does it and follow that protocol precisely. Delayed cord clamping is supported in current WHO guidance, with timing as per protocol.\n\nEye care, vitamin K, weighing, measuring and identification all follow local standing orders and your supervised training — you will learn each one hands-on, with a preceptor checking you, before you do them alone.\n\nWhat is yours from the very first day: know the sequence exists, keep the baby warm, support early breastfeeding, document timings honestly, and escalate the moment any check feels wrong. The skills list grows with practice; vigilance is yours from the first shift.",
    },
    {
      type: "text",
      title: "The mother is part of the assessment",
      body: "A newborn check is a two-for-one: the baby's condition and the mother's condition, feeding and understanding travel together. Skin-to-skin doubles as assessment — does the baby root toward the breast? Watching a feed is assessment — is the attachment right, is she swallowing? And the mother's questions are assessment: 'he is not waking like yesterday' is often the earliest danger-sign report you will ever receive.\n\nSo end every newborn check by teaching one thing: tonight, keep him warm and skin-to-skin; feed on cue, waking him as the team advises; watch the danger-sign list we discussed; and bring him immediately if anything on it appears. A mother who knows what to watch is the best neonatal monitor on the ward — and the community nurse visiting in the coming days continues exactly that vigilance.",
    },
    {
      type: "quiz_prompt",
      title: "The cold baby",
      body: "A newborn's temperature at two hours of age is 35.8 °C, and he is feeding sleepily. What does this finding mean, and what is your immediate response as the student?\n\nAnswer: Hypothermia — a cold baby is a danger-sign baby, because cold stress undermines both feeding and breathing. Warm him immediately with skin-to-skin under a blanket and report for review; never simply add a blanket and wait, and never warm him near an open flame.",
    },
    {
      type: "summary",
      title: "In one minute",
      body: "- Immediate assessment runs with immediate care: dry, warm, position the airway — and answer three questions: breathing/crying, tone, colour.\n- APGAR: Appearance, Pulse, Grimace, Activity, Respiration — each 0–2, scored at 1 and 5 minutes (repeated 5-minutely if low).\n- As a frame: 7–10 reassuring, 4–6 moderate, 0–3 low — the score is a shared language, not a prophecy, and never a substitute for looking at the baby.\n- Central cyanosis is an emergency; blue hands and feet alone usually are not — check the centre, not the edges.\n- Newborn danger signs: fast breathing, grunting, chest indrawing, central cyanosis, hypothermia or fever, poor feeding, convulsions, lethargy, red or offensive cord — escalate immediately.\n- Immediate care (cord care including chlorhexidine per Ghana protocol, delayed clamping, vitamin K, eye care) follows standing orders and supervised training.\n- Teach the mother warmth, feeding on cue and the danger signs — after you, she is the monitor.",
    },
  ],
  questions: [
    {
      topic: "Apgar Score",
      type: "MCQ",
      difficulty: "Moderate",
      stem: "At 1 minute: the baby's body is pink with blue hands and feet; heart rate 130; she grimaces and coughs when the mouth is suctioned; arms and legs are flexed and moving; the cry is strong and breathing regular. What is the Apgar score?",
      options: [
        "7",
        "8",
        "9",
        "10",
      ],
      correctIndex: 2,
      explanation: "Score each component: Appearance 1 (pink body but blue extremities is not 'completely pink'), Pulse 2 (130 is 100 or above), Grimace 2 (coughing is a vigorous response), Activity 2 (flexed and moving), Respiration 2 (strong cry, regular breathing). The total is 9 — the most common trap is awarding a 2 for colour when the hands and feet are still blue. Train your eye to give the 1 honestly; the difference between 9 and 10 is precisely this finding.",
      whyOthers: {
        A: "7 would require under-scoring two additional components — every other sign here earns its full 2.",
        B: "8 would mean a second component scored 1 — but pulse, grimace, activity and respiration are all clearly full-credit findings.",
        D: "10 requires 'completely pink' — blue hands and feet keep the Appearance score at 1, so the ceiling here is 9.",
      },
      courseSlug: "neonatal-nursing",
    },
    {
      topic: "Immediate Newborn Care",
      type: "CLINICAL_SCENARIO",
      difficulty: "Clinical Reasoning",
      stem: "A baby is born limp and pale, not crying. As the student midwife present, what is your first and most important action?",
      options: [
        "Complete the 1-minute Apgar score before touching the baby, since the score guides everything",
        "Call loudly for senior help while ensuring the baby is dried, warmed and the airway positioned — the immediate steps you were trained to perform",
        "Place the baby skin-to-skin with the mother and observe for a further minute",
        "Note the time and begin documenting the event in the case notes",
      ],
      correctIndex: 1,
      explanation: "Care and assessment begin together, in the same seconds: drying stimulates breathing, warmth protects it, and the neutral airway position supports it — while the call for help mobilises the people whose skills the baby may need. The Apgar score is a communication tool applied at defined minutes; it never delays the immediate steps. Documentation matters, but it follows the call for help — and skin-to-skin is for a baby who is breathing and vigorous, not one who is limp and silent.",
      whyOthers: {
        A: "Scoring is performed at its minute mark but never comes before drying, warming and airway positioning — those ARE the first assessment minutes.",
        C: "Skin-to-skin is precious for well babies; a limp, non-crying baby needs warming with active assessment and help, not observation on the mother's chest.",
        D: "Accurate timing is genuinely important — but the call for help and the basic steps come first; the pen follows the action.",
      },
      courseSlug: "neonatal-nursing",
    },
    {
      topic: "Newborn Assessment",
      type: "MCQ",
      difficulty: "Easy",
      stem: "Four newborns on the ward. Which baby's colour is the emergency?",
      options: [
        "A vigorous feeder whose hands and feet are blue but whose trunk, tongue and lips are pink",
        "A baby whose tongue and lips look blue despite being warmed",
        "A twelve-hour-old baby with a mild yellow tinge to the face only",
        "A baby whose hands and feet are pink but slightly mottled when unwrapped",
      ],
      correctIndex: 1,
      explanation: "Blue tongue and lips are central cyanosis — the sign that blood is not carrying oxygen well enough, and it demands immediate help with breathing and an urgent call to the senior clinician. Blue hands and feet on a pink, vigorous baby are peripheral cyanosis, common in the first hours and usually benign; mild facial jaundice at twelve hours deserves monitoring rather than panic, but is not the colour emergency. The rule that separates the worlds: check the centre — tongue, lips, face.",
      whyOthers: {
        A: "This is peripheral cyanosis in a well baby — a familiar, usually benign finding in the first hours that needs observation, not emergency response.",
        C: "Jaundice appearing on the face within the first day should be monitored and reported for review, but it is not the immediate breathing emergency that central cyanosis is.",
        D: "Pink hands and mild mottling when briefly unwrapped is a warmth cue, not an emergency — rewrap and reassess temperature.",
      },
      courseSlug: "neonatal-nursing",
    },
    {
      topic: "Apgar Score",
      type: "TRUE_FALSE",
      difficulty: "Moderate",
      stem: "True or false: an Apgar score of 10 at 5 minutes means the newborn needs no further observation or care.",
      options: [
        "True",
        "False",
        "True, if the baby is already breastfeeding",
        "True, if the birth was completely normal",
      ],
      correctIndex: 1,
      explanation: "Apgar is a snapshot of condition at a moment in time — it says nothing about the hours that follow. Even a baby scoring 10 at 5 minutes still needs warmth, feeding support, cord care, medicines per standing orders (vitamin K among them), and continuous danger-sign vigilance, because newborns can deteriorate quickly and quietly after a perfect start. A perfect score ends the scoring, never the watching — the score is one sentence, not the whole story.",
      whyOthers: {
        A: "This mistake is exactly how well-scored babies deteriorate unnoticed — the Apgar was never designed as a guarantee of the hours ahead.",
        C: "Early feeding is a good sign, but it does not replace warmth, cord care, vitamin K per standing orders or the danger-sign watch.",
        D: "A normal birth lowers some risks but does not switch off newborn monitoring — every baby, however well born, gets the vigilance.",
      },
      courseSlug: "neonatal-nursing",
    },
    {
      topic: "Newborn Danger Signs",
      type: "CLINICAL_SCENARIO",
      difficulty: "Hard",
      stem: "Twelve hours after a normal birth, a baby has not woken to feed for five hours, feels cool to touch (temperature 35.9 °C), and is less active than earlier. What is the most appropriate action?",
      options: [
        "Wrap him in an extra blanket and recheck at the next routine round",
        "Report immediately to the senior midwife — poor feeding plus hypothermia is a newborn danger-sign combination needing urgent review",
        "Advise the mother to keep attempting feeds and review him at discharge",
        "Reassure the mother that newborns sleep deeply in the first day",
      ],
      correctIndex: 1,
      explanation: "Two danger signs together — poor feeding and hypothermia — plus reduced activity make this a now-problem: the combination is a recognised marker of serious newborn illness, including infection, and it warrants immediate review, warming with skin-to-skin, and assessment by the senior team. Sleeping and missed feeds are how sick newborns present — quietly, not dramatically. The student's task is the same as ever: recognise fast, report fast, stay with the baby.",
      whyOthers: {
        A: "An extra blanket without reporting treats the thermometer, not the baby — hypothermia with poor feeding is a danger sign, not a linen problem.",
        C: "Waiting until discharge leaves an unassessed window in which infection or other illness can escalate — the review belongs to today, this hour.",
        D: "Deep sleep is normal; a five-hour feed gap with cool skin and reduced activity is not — reassurance here is how danger signs get missed.",
      },
      courseSlug: "neonatal-nursing",
    },
    {
      topic: "Newborn Danger Signs",
      type: "MULTI_SELECT",
      difficulty: "Moderate",
      stem: "Select all findings that count as newborn danger signs needing immediate escalation.",
      options: [
        "Grunting with each breath",
        "Central cyanosis of the tongue and lips",
        "Poor feeding or no feeding at all",
        "Blue hands and feet in an otherwise pink, active baby",
      ],
      correctIndexes: [0, 1, 2],
      explanation: "Grunting is the baby forcing pressure to keep the lungs open — a respiratory danger sign. Central cyanosis means oxygenation is failing. Poor or absent feeding is one of the most reliable early signs of serious newborn illness, from infection to hypothermia. Together these findings trigger immediate escalation to the senior team. Blue hands and feet on a pink, active baby are peripheral cyanosis — common in the first hours and usually benign, though always noted and observed.",
      whyOthers: {
        D: "Peripheral cyanosis in a vigorous baby is expected in the first hours and is not on the danger-sign list — document it, keep the baby warm, and observe.",
      },
      courseSlug: "neonatal-nursing",
    },
    {
      topic: "Apgar Score",
      type: "MCQ",
      difficulty: "Hard",
      stem: "At 1 minute you count a newborn heart rate of 96 beats per minute. What does the Pulse component earn, and why does this number carry particular weight with the team?",
      options: [
        "It scores 2, since any audible heartbeat earns full marks",
        "It scores 1, because the rate is below 100 — and heart rate is central to decisions about respiratory support, so the team will watch its response to the immediate steps closely",
        "It scores 0, because 96 is functionally the same as absent circulation",
        "It cannot be scored until the 5-minute assessment",
      ],
      correctIndex: 1,
      explanation: "The Pulse component gives 2 for a heart rate of 100 or above and 1 for below 100 — so 96 earns a 1. Heart rate is the heavyweight of newborn assessment because it drives the resuscitation decisions: a slow heart rate in a floppy or poorly breathing baby tells the team the circulation is under strain and the response to basic steps must be watched closely. This is why the team listens for the rate early — by stethoscope, or by feeling pulsation at the cord stump — before anything else in a quiet baby.",
      whyOthers: {
        A: "The threshold is numerical, not existential — below 100 scores 1, whatever the rate's clinical meaning.",
        C: "A rate of 96 is very much present and far from zero — but the sub-100 threshold is exactly why it earns a 1 rather than a 2.",
        D: "The 1-minute score exists precisely to summarise the baby's state now — heart rate is scored at the same minute as every other component.",
      },
      courseSlug: "neonatal-nursing",
    },
  ],
  flashcards: [
    {
      topic: "Apgar Score",
      front: "What do the letters of APGAR stand for, and how is each scored?",
      back: "Appearance, Pulse, Grimace, Activity, Respiration — each scored 0, 1 or 2, summed at 1 minute and 5 minutes (repeated 5-minutely if the score stays low).",
    },
    {
      topic: "Apgar Score",
      front: "Give the heart-rate thresholds for the Apgar Pulse component.",
      back: "2 = 100 beats per minute or above; 1 = below 100; 0 = absent. The heart rate anchors the team's decisions about respiratory support.",
    },
    {
      topic: "Newborn Assessment",
      front: "Central vs peripheral cyanosis — which is the emergency?",
      back: "Central (blue tongue, lips or face) is an emergency needing breathing help and an immediate call for the senior clinician. Peripheral (blue hands and feet on a pink, vigorous baby) is common in the first hours and usually benign.",
    },
    {
      topic: "Newborn Danger Signs",
      front: "List six newborn danger signs.",
      back: "Fast breathing (about 60/min or more), grunting, chest indrawing, central cyanosis, hypothermia or fever, poor or absent feeding — plus convulsions, lethargy and a red/offensive cord stump.",
    },
    {
      topic: "Immediate Newborn Care",
      front: "What three questions do you answer in the newborn's first 60 seconds?",
      back: "Is the baby breathing or crying well? Is the tone good (moving, flexing, resisting)? Is the colour right at the centre? A falter on any one means help — and calling for it is the first step.",
    },
    {
      topic: "Immediate Newborn Care",
      front: "Why is warmth a clinical priority, not a comfort nicety?",
      back: "A wet newborn loses heat fast; cold stress raises oxygen needs, undermines feeding, and can tip a borderline baby into trouble — drying, skin-to-skin and a cap are assessment-grade care.",
    },
  ],
  sources: [
    {
      organization: "World Health Organization",
      title: "WHO recommendations on maternal and newborn care for a positive postnatal experience",
      year: "2022",
      note: "Educational source — verify current edition and local protocols.",
    },
    {
      organization: "World Health Organization",
      title: "Pregnancy, childbirth, postpartum and newborn care: a guide for essential practice",
      year: "2015 (2nd edition)",
      note: "Educational source — verify current edition.",
    },
    {
      organization: "American Academy of Pediatrics",
      title: "Textbook of Neonatal Resuscitation (NRP)",
      year: "2021 (8th edition)",
      note: "Educational source — skills are learnt through certified, supervised training, never from text alone.",
    },
    {
      organization: "Elsevier",
      title: "Myles Textbook for Midwives",
      year: "2020 (17th edition)",
      note: "Educational source — verify current edition.",
    },
  ],
};
