import type { SeedFullLesson } from "../types";

export const lessonFourStages: SeedFullLesson = {
  courseSlug: "normal-labour",
  moduleTitle: "The Four Stages",
  lessonTitle: "The Four Stages of Labour",
  description: "Labour has a map, and every midwife in the world reads the same one. Learn the four stages — from the first true twinge to the watchful hour after — and you will always know where you are and what to watch next.",
  difficulty: "Moderate",
  durationMin: 18,
  objectives: [
    "By the end you can state the boundaries of all four stages of labour.",
    "By the end you can describe the latent and active phases of the first stage and why the distinction matters on the partograph.",
    "By the end you can list the signs of placental separation and describe what the third stage involves.",
    "By the end you can explain why the fourth stage is a high-risk hour and which observations it demands.",
    "By the end you can recognise the findings in any stage that must be escalated to senior staff.",
  ],
  tags: ["labour", "stages of labour", "third stage", "postpartum haemorrhage", "partograph"],
  sourceStatus: "GCU_ALIGNED",
  sections: [
    {
      type: "callout",
      title: "Why this matters",
      body: "If labour is a journey, the stages are its milestones — and midwifery is the discipline of knowing exactly which milestone you are standing on. In Ghanaian labour wards, the partograph turns these stages into a picture, and your ability to place a woman on the map decides whether you chart, call, or run. Examiners adore this topic — and honestly, so will you, because it is the skeleton key to normal labour.",
    },
    {
      type: "text",
      title: "The map, in one look",
      body: "Simply first: labour has four stations. First stage: from the onset of true labour to full cervical dilation (10 cm). Second stage: from full dilation to the birth of the baby. Third stage: from the birth of the baby to the delivery of the placenta. Fourth stage: the first hour or two after the placenta — the hour of closest watching.\n\nThink of it as a relay: the cervix opens, the baby travels and is born, the placenta follows, and the mother's body lands safely. Each runner hands over a baton of risk — and the last runner carries the baton that people most underestimate.\n\nThe map matters because it tells you what to watch: dilation and fetal heart in the first, descent and pushing in the second, bleeding and separation in the third, and the fundus in the fourth.",
    },
    {
      type: "table",
      title: "The four stages at a glance",
      body: "| Stage | From → To | The work being done | What you watch |\n|---|---|---|---|\n| First | Onset of true labour → full dilation (10 cm) | Cervix effaces and dilates; baby begins descent | Contraction pattern, fetal heart, cervical progress on the partograph, maternal comfort and hydration |\n| Second | Full dilation → birth of the baby | Mother pushes; baby rotates and descends through the pelvis | Urge to push, descent, fetal heart more closely, perineum — delivery is a supervised skill |\n| Third | Birth of the baby → placenta delivered | Placenta separates and is expelled | Signs of separation, blood loss, uterine tone — management follows protocol and the midwife in charge |\n| Fourth | First 1–2 hours after the placenta | Haemostasis, bonding, first feed | Fundal tone and height, lochia, pulse and blood pressure, bladder, warmth, newborn condition |",
    },
    {
      type: "text",
      title: "The first stage: latent and active",
      body: "The first stage has two phases with different personalities. The latent phase is the warm-up: contractions establish a rhythm, the cervix effaces and dilates slowly, and progress is measured in patience. The active phase is the highway: dilation moves faster, the partograph's alert and action lines are built for it, and progress is expected to be steady.\n\nWhere does active begin? Definitions have evolved: WHO's intrapartum guidance recognises the active first stage as typically starting around 5 cm dilation, while older texts and some local practices use lower thresholds — always follow your facility's teaching. Clinically, the trend is what counts: steady progress on the partograph is reassuring; crossing the action line is a call for review.\n\nYour first-stage jobs as a student: comfort, hydration, positioning, accurate observation and honest charting — and reporting when progress stalls or the woman's condition changes.",
    },
    {
      type: "quiz_prompt",
      title: "Is she in active labour?",
      body: "A woman arrives contracting every 10 minutes; the cervix is 3 cm, and she is comfortable between contractions. Which phase is she in, and what are your main tasks over the next few hours if contractions remain mild?\n\nAnswer: She is in latent (early) labour — WHO recognises active first stage as typically beginning around 5 cm. Latent hours are normal, so your tasks are supportive care, calm observation and honest charting, with review if contractions strengthen or her condition changes.",
    },
    {
      type: "text",
      title: "The second stage: full dilation to birth",
      body: "Second stage begins at 10 cm, and the mother's urge to push usually arrives with it — the Ferguson reflex, the body's own bearing-down signal (yes, another positive feedback loop — you met this one in your homeostasis lesson).\n\nThe stage has quiet mechanics: the head stays flexed, rotates to bring the occiput anterior, descends, crowns, and is born — then the shoulders, then the whole body in a rush. Some women push spontaneously and effectively; coached pushing is a skill you will be taught in supervised practice, not from a screen.\n\nSecond stage is also a stage of vigilance: the fetal heart is monitored more closely, and a second stage that runs long, or a fetal heart that does not recover between contractions, belongs to the senior midwife immediately. Signs of descent you will learn hands-on include a bulging perineum and the head visible at the opening.",
    },
    {
      type: "memory_trick",
      title: "The four Ds",
      body: "Dilate, Deliver, Deliver the placenta, Don't relax yet. First stage dilates the door, second delivers the baby, third delivers the afterbirth — and the fourth D is the one students forget: the hour when you do NOT relax, because this is when most primary postpartum haemorrhage occurs.",
    },
    {
      type: "text",
      title: "The third stage: the placenta's exit",
      body: "The third stage runs from the baby's birth to the placenta's. Its physiology is a two-step: the contracting uterus shears the placenta off its bed, and then the placenta is expelled.\n\nSeparation announces itself with classic signs: a sudden small gush of blood, the cord visibly lengthening at the opening, and the uterus changing character — rising and becoming firm and globular as the placenta drops into the lower segment. Two signs together should make you confident; none of them should be rushed.\n\nHow the third stage is managed — physiological (supporting the mother to deliver the placenta, often with the baby at the breast) or active (uterotonics with controlled cord traction, as prescribed and as trained) — is decided by protocol and the midwife in charge, never improvised by a student. Uterotonics are powerful medicines with real doses and contraindications: this is a learn-then-practise-under-supervision zone, and so is cord traction.",
    },
    {
      type: "clinical_pearl",
      title: "The blood you don't see",
      body: "Most primary postpartum haemorrhage happens within the first hour — precisely the fourth stage. A firm fundus, an empty bladder and a watched lochia are your lifeline trio; a soft fundus with a steady trickle is your alarm. And remember that blood loss judged by eye is famously underestimated — measure and estimate honestly.",
    },
    {
      type: "case",
      title: "Eleven minutes after the birth",
      body: "Mimie, you are the student midwife at a facility birth. The baby was delivered 11 minutes ago, dried, placed on the mother's chest, and is crying well. The midwife is documenting. You are watching the cord: it suddenly lengthens, a gush of dark blood appears at the opening, and the fundus — firm a minute ago — now feels soft and slightly high.\n\nWhat do the lengthening cord and the gush suggest is happening? Why is the soft fundus the finding that outranks them — and what does it change about the urgency? And what is your role in the next 60 seconds as the student in the room?\n\nThe gush and the lengthening cord are classic separation signs — good news if the uterus stays firm. A soft fundus after separation is the warning: the living ligatures of the uterine muscle may not be clamping the placental site. Your role is not to manage it — it is to say it out loud immediately, fetch help, and support warmth and positioning as directed. Timing and tone are everything: a calm, immediate sentence — 'the fundus is soft, and she is bleeding' — is the student midwife's finest skill.",
    },
    {
      type: "quiz_prompt",
      title: "Order the third stage",
      body: "Put these events in order before checking: the uterus contracts and shears the placenta free / the gush and cord lengthening appear / the placenta is expelled. And which action must never come before separation is confirmed?\n\nAnswer: Shearing first, then the gush and cord lengthening together, then expulsion — and traction on the cord must never precede confirmed separation, because pulling an attached placenta risks inversion and haemorrhage. Recognise the signs, let physiology lead, and leave the techniques to supervised training.",
    },
    {
      type: "text",
      title: "The fourth stage: the quiet hour",
      body: "The fourth stage is the first one or two hours after the placenta. The drama is over, which is exactly why it is dangerous: attention drifts to the baby just as the mother's risk peaks. The uterus is now a raw, dinner-plate-sized placental site that must stay contracted to seal its own vessels.\n\nYour fourth-stage routine — learned as a supervised skill — is a loop: fundal tone and height, lochia, pulse and blood pressure, bladder, warmth, skin-to-skin and the first breastfeed. The breastfeeding itself is therapy: suckling releases oxytocin, the same hormone that keeps the uterus tight.\n\nWatch for the quiet variants: the woman who is 'just pale and restless' (recall compensation — the pulse is the price tag), the fundus that fills and softens when nobody is looking, and the trickle that never quite stops. Check, chart, and stay close.",
    },
    {
      type: "quiz_prompt",
      title: "Why a whole hour of watching?",
      body: "Why does the fourth stage earn a full hour of observations when the baby is already safely born? Give two physiological reasons — one about the placental site, one about breastfeeding hormones.\n\nAnswer: The placental site is a large open vascular bed that only sustained uterine contraction seals — relaxation there is the mechanism of primary PPH, and most of it happens in this hour. And early suckling releases oxytocin, helping the uterus stay contracted — which is why skin-to-skin and the first feed are written into fourth-stage care.",
    },
    {
      type: "summary",
      title: "In one minute",
      body: "- First stage: true labour onset → 10 cm. Latent is the slow warm-up; active is the fast highway (WHO recognises active as typically beginning around 5 cm).\n- Second stage: 10 cm → birth of the baby — pushing urge, descent and rotation, closest fetal-heart vigilance.\n- Third stage: birth of the baby → placenta. Separation signs: a gush of blood, cord lengthening, and a firm, rising, globular uterus.\n- Fourth stage: the first 1–2 hours — highest PPH risk of the whole journey; watch fundus, lochia, vitals, bladder and bonding.\n- The four Ds: Dilate, Deliver, Deliver the placenta, Don't relax yet.\n- Escalate without hesitation: soft fundus, heavy loss, fetal heart concerns, or progress crossing the action line.\n- Third-stage techniques (uterotonics, controlled cord traction) belong to protocol and supervised practice — recognition and reporting are your domain.",
    },
  ],
  questions: [
    {
      topic: "Stages of Labour",
      type: "MCQ",
      difficulty: "Easy",
      stem: "A student's note reads 'second stage complete at 03:12'. Which event defines that moment?",
      options: [
        "The cervix reached full dilation",
        "The baby was completely born",
        "The placenta was delivered",
        "The umbilical cord was cut",
      ],
      correctIndex: 1,
      explanation: "The second stage runs from full dilation to the birth of the baby, so it is complete only when the whole baby — head, shoulders and body — is born. Full dilation marks its beginning, not its end; the placenta ends the third stage; and cutting the cord is a care step that happens after the second stage has already finished. These boundaries are the vocabulary of every labour handover you will ever give.",
      whyOthers: {
        A: "Full dilation (10 cm) is the starting line of the second stage, not its finish.",
        C: "Placental delivery closes the third stage — at 03:12 this baby has only just arrived.",
        D: "Cord cutting is immediate newborn care; the stage was already complete when the body was born.",
      },
      courseSlug: "normal-labour",
    },
    {
      topic: "Stages of Labour",
      type: "ORDERING",
      difficulty: "Moderate",
      stem: "Put these milestones of a normal labour in the order they occur.",
      options: [
        "Cervix reaches 10 cm dilation",
        "Baby's head crowns",
        "Cord lengthens with a gush of blood",
        "Fundus checked firm in the first postpartum hour",
      ],
      explanation: "Each milestone is the signature event of one stage, in order: full dilation closes the first stage, crowning is the climax of the second, the gush and lengthening cord are third-stage separation signs, and the firm-fundus check is the working heart of the fourth stage. Sequencing them correctly proves you can place yourself on labour's map — which is what every partograph entry and every handover sentence is really asking. A student who knows which stage they are standing in knows what to watch and whom to call.",
      whyOthers: {
        A: "Full dilation must come first — nothing that follows can happen before the cervix is fully open.",
        B: "Crowning belongs second: it is the second stage's finale and cannot precede full dilation.",
        C: "The gush and cord lengthening follow the birth — they are separation signs of the third stage.",
        D: "The postpartum fundal check comes last, in the fourth stage, after the placenta has separated and been delivered.",
      },
      courseSlug: "normal-labour",
    },
    {
      topic: "Postpartum Haemorrhage",
      type: "CLINICAL_SCENARIO",
      difficulty: "Clinical Reasoning",
      stem: "Twenty minutes after a vaginal birth, the fundus feels soft and slightly high, with a steady trickle of dark red blood. The baby is at the breast. What is the student midwife's most appropriate action?",
      options: [
        "Document the fundal height and recheck at the next scheduled round",
        "Call the midwife in charge immediately and stay to assist — a soft fundus with ongoing bleeding after birth needs urgent attention",
        "Wait ten more minutes, since placentas can take half an hour or more",
        "Ask the mother to stop breastfeeding until the bleeding settles",
      ],
      correctIndex: 1,
      explanation: "A soft (boggy) fundus with ongoing bleeding is the classic picture of a uterus not clamping its placental site — the mechanism of primary postpartum haemorrhage, and a now-problem, not a next-round problem. The student's role is immediate escalation and staying to assist: senior staff will assess and act (uterine massage, emptying the bladder, uterotonics per protocol) — your sentence and your speed are the treatment's head start. Babies feeding at the breast help, not harm: suckling releases oxytocin.",
      whyOthers: {
        A: "Waiting for the next round on a soft fundus with active bleeding forfeits the window in which simple measures work best — this is an immediately-tell-someone finding.",
        C: "The waiting-for-the-placenta logic applies to a well-contracted uterus; when the fundus is soft and bleeding, the emergency is uterine atony, not slow separation.",
        D: "Stopping breastfeeding removes a natural source of oxytocin, the very hormone that helps the uterus clamp — exactly backwards.",
      },
      courseSlug: "normal-labour",
    },
    {
      topic: "Postpartum Haemorrhage",
      type: "TRUE_FALSE",
      difficulty: "Moderate",
      stem: "True or false: most primary postpartum haemorrhage occurs more than 24 hours after delivery.",
      options: [
        "True",
        "False",
        "True, but only after caesarean births",
        "True, but only for mothers of many children",
      ],
      correctIndex: 1,
      explanation: "Primary PPH is bleeding within the first 24 hours, and the majority occurs within the first hour — the fourth stage — because that is when the placental site is raw and the uterus must do its clamping work. Bleeding after 24 hours and up to about six weeks is called secondary PPH, usually with different causes such as retained tissue or infection. The timing distinction matters because it dictates which observations you are guarding: the fourth-stage checks exist precisely because of this hour.",
      whyOthers: {
        A: "This confuses primary with secondary PPH — the early hours are the dangerous ones for primary haemorrhage, which is why the fourth stage exists as a stage at all.",
        C: "Route of birth does not move the definition — caesarean births carry their own bleeding risks, but primary PPH timing is measured the same way.",
        D: "Grand multiparity is a risk factor for uterine atony, not a change in when primary PPH occurs — the first hour remains the critical window for everyone.",
      },
      courseSlug: "normal-labour",
    },
    {
      topic: "Third Stage of Labour",
      type: "MCQ",
      difficulty: "Hard",
      stem: "Which trio represents the classic signs of placental separation?",
      options: [
        "A sudden gush of blood, lengthening of the cord, and a firm, globular, rising uterus",
        "Cessation of the cord pulse, maternal shivering, and a soft fundus",
        "Cord shortening, decreased bleeding, and a fundus descending below the pubic bone",
        "Maternal bearing down, a boggy fundus, and bright red blood",
      ],
      correctIndex: 0,
      explanation: "Separation has a consistent script: the uterus contracts and the placenta drops into the lower segment, so the uterus feels firm, globular and slightly higher; blood escapes behind the placenta as a small gush; and the cord advances visibly at the opening because the placenta has moved down. A soft fundus is the opposite finding — a warning of atony. Recognising this trio confidently (without rushing or pulling) is what safe third-stage watching is built on.",
      whyOthers: {
        B: "Shivering is common after birth but is not a separation sign, and a soft fundus argues against good contraction — this trio mixes reassurance with its opposite.",
        C: "The cord lengthens rather than shortens, and bleeding shows as a gush, not a decrease — this reverses the physiology.",
        D: "Bearing down belongs to the second stage, and a boggy fundus with bright red loss is the alarm picture of haemorrhage, not separation.",
      },
      courseSlug: "normal-labour",
    },
    {
      topic: "First Stage of Labour",
      type: "CLINICAL_SCENARIO",
      difficulty: "Moderate",
      stem: "A woman at term has had mild, irregular contractions for 10 hours; the cervix is 3 cm with no change over the last 4 hours. Membranes are intact, the fetal heart is reassuring, and she is exhausted and tearful. What is the student's most appropriate contribution?",
      options: [
        "Tell her she is in obstructed labour and needs theatre",
        "Provide comfort, hydration and encouragement; chart honestly, and alert the midwife in charge about the fatigue and the static cervix so decisions are made by senior staff",
        "Encourage her to push with each contraction to speed progress",
        "Send her home to sleep and return when contractions are strong",
      ],
      correctIndex: 1,
      explanation: "This picture fits a prolonged latent phase with a tired mother — and prolonged latent labour is a recognised reason for review, so the senior midwife should hear about both the static cervix and the exhaustion. Your contribution as a student is the supportive layer — comfort, fluids, encouragement, position changes — plus honest charting that shows the trend. Diagnosis and decisions (augmentation, analgesia, rest strategies) belong to qualified staff; label her 'obstructed' or send her home and you have stepped beyond your role either way.",
      whyOthers: {
        A: "Obstruction is a diagnosis of established labour with poor progress and specific findings — announcing it is both inaccurate and terrifying, and it is not the student's call.",
        C: "Pushing at 3 cm swells an undilated cervix and gains nothing — bearing down belongs to the fully dilated second stage.",
        D: "Discharging an exhausted woman in latent labour is a senior decision weighing distance, membranes and safety — not a student judgement, and 'sleep at home' can mean 'deliver on the road'.",
      },
      courseSlug: "normal-labour",
    },
    {
      topic: "Fourth Stage of Labour",
      type: "MCQ",
      difficulty: "Moderate",
      stem: "Which explanation best answers a tired new mother who asks why the baby should be put to the breast right now?",
      options: [
        "So the baby does not become hungry before the milk comes in on the third day",
        "Because suckling releases oxytocin, which helps the uterus stay firmly contracted and reduces bleeding — and the first milk is exactly what the baby needs",
        "Because the notes need to show that breastfeeding started before transfer to the postnatal ward",
        "So the baby stays awake for the examinations scheduled in the first hour",
      ],
      correctIndex: 1,
      explanation: "Early suckling is physiology with a purpose: oxytocin released at the breast keeps the uterine muscle clamped over the placental site — the fourth stage's own natural protection against haemorrhage. Skin-to-skin and the first feed also warm the baby, stabilise the heart rate, and deliver colostrum, the perfect first food. It is one of the few interventions that is simultaneously newborn care, maternal care and haemorrhage prophylaxis — which is why the answer is 'now', not 'later'.",
      whyOthers: {
        A: "Colostrum is present from the start and is precisely what the newborn needs in the first hours — waiting would starve the baby of it, and hunger is not the main reason for the timing.",
        C: "Documentation is a by-product, never a reason — care is for the mother and baby, not for the notes.",
        D: "Newborn examinations are timed around the baby's condition, and keeping a baby awake is not a goal of the first hour — warmth, feeding and bonding are.",
      },
      courseSlug: "normal-labour",
    },
  ],
  flashcards: [
    {
      topic: "Stages of Labour",
      front: "Give the boundaries of the four stages of labour.",
      back: "1st: true labour onset → full dilation (10 cm). 2nd: full dilation → birth of the baby. 3rd: birth of baby → placenta delivered. 4th: the first 1–2 hours after the placenta.",
    },
    {
      topic: "Third Stage of Labour",
      front: "Name the classic signs of placental separation.",
      back: "A sudden gush of blood; visible lengthening of the cord at the opening; and the uterus becoming firm, globular and rising in the abdomen.",
    },
    {
      topic: "Stages of Labour",
      front: "The four Ds of labour — what are they?",
      back: "Dilate (1st), Deliver the baby (2nd), Deliver the placenta (3rd), Don't relax yet (4th — the hour of highest PPH risk).",
    },
    {
      topic: "Fourth Stage of Labour",
      front: "Why is the fourth stage the highest-risk hour?",
      back: "The placental site is a raw, open vascular bed that only uterine contraction can seal — most primary PPH happens in this first hour. Watch fundus, lochia, vitals, bladder and bonding.",
    },
    {
      topic: "First Stage of Labour",
      front: "Latent vs active first stage — the one-line difference?",
      back: "Latent: slow warm-up with irregular-to-regular contractions and gradual dilation. Active: faster dilation with a partograph expectation of steady progress (WHO recognises active as typically starting around 5 cm).",
    },
    {
      topic: "Postpartum Haemorrhage",
      front: "Primary vs secondary PPH — when does each occur?",
      back: "Primary: excessive bleeding within 24 hours of birth (mostly in the first hour). Secondary: abnormal bleeding after 24 hours up to about six weeks, often from retained tissue or infection.",
    },
  ],
  sources: [
    {
      organization: "World Health Organization",
      title: "WHO recommendations: Intrapartum care for a positive childbirth experience",
      year: "2018",
      url: "https://www.who.int/publications/i/item/9789241550215",
      note: "Educational source — verify current edition and follow local protocols.",
    },
    {
      organization: "World Health Organization",
      title: "WHO recommendations for the prevention and treatment of postpartum haemorrhage",
      year: "2022",
      note: "Educational source — no doses taught here; verify current edition and local protocol.",
    },
    {
      organization: "Elsevier",
      title: "Myles Textbook for Midwives",
      year: "2020 (17th edition)",
      note: "Educational source — verify current edition.",
    },
    {
      organization: "Elsevier (Baillière Tindall)",
      title: "Mayes' Midwifery: A Textbook for Midwives",
      year: "2019 (14th edition)",
      note: "Educational source — verify current edition.",
    },
  ],
};
