import type { SeedFullLesson } from "../types";

export const lessonFetalPositions: SeedFullLesson = {
  courseSlug: "normal-labour",
  moduleTitle: "Understanding the Passenger",
  lessonTitle: "Understanding Fetal Lie, Presentation and Position",
  description: "Three questions — is the baby lying straight, what is at the door, and which way is the back facing — decide whether labour runs smoothly or heads for trouble. Learn to answer them with your hands and your reasoning, the way midwives do.",
  difficulty: "Moderate",
  durationMin: 20,
  objectives: [
    "By the end you can define fetal lie, presentation and position, and explain how they differ.",
    "By the end you can name the denominator for vertex, breech, face and shoulder presentations.",
    "By the end you can describe the common vertex positions (LOA, OA, ROA, OP and their families) and which travel best.",
    "By the end you can explain in outline what abdominal palpation (Leopold's manoeuvres) is assessing — as a supervised clinical skill.",
    "By the end you can recognise findings like transverse lie at term as ones that need escalation and referral planning, not watchful waiting.",
  ],
  tags: ["fetal lie", "presentation", "position", "Leopold's manoeuvres", "labour mechanics"],
  sourceStatus: "GCU_ALIGNED",
  sections: [
    {
      type: "callout",
      title: "Why this matters",
      body: "Every labour assessment you will ever make begins with the same three questions: how is this baby lying, what comes first, and which way does the back face? On Ghanaian antenatal and labour wards, these answers shape whether a woman delivers safely where she is or needs referral before labour starts. Get fluent in them now, and the pregnant abdomen becomes a map you can actually read.",
    },
    {
      type: "text",
      title: "Lie: is the baby straight or across?",
      body: "Simply first: fetal lie is the relationship between the baby's long axis (its spine) and the mother's long axis. A baby lying head-down or bottom-down is in a longitudinal lie — aligned with the mother. A baby lying sideways is in a transverse lie — shoulder first. In between, angled diagonally, is an oblique lie, which often shifts to longitudinal or transverse as labour approaches.\n\nMost term babies settle into longitudinal lie, because the womb is shaped like a pear and a pear fits a baby like a sleeping bag — lengthwise.\n\nClinically, transverse lie at term is not a curiosity: the presenting part cannot press the cervix effectively, labour can obstruct, and once the waters break the cord or an arm can slip down — a prolapse. It is a finding for experienced hands and referral planning, never a wait-and-see item for a student.",
    },
    {
      type: "text",
      title: "Presentation: what is at the door?",
      body: "Presentation answers one question: which part of the baby sits over the cervix, first in line for the outside world? Cephalic means head-first — the presentation of the great majority of term labours. Breech means buttocks or feet first. Shoulder presentation goes with a transverse lie.\n\nWithin cephalic, the leading part depends on how the head is tilted — its attitude. A well-flexed chin-to-chest head presents the vertex, the best-fitting passenger. As the head extends, the ladder of trouble climbs: sinciput, then brow, then face — each presenting a larger, less favourable profile.\n\nA separate term you will meet: the presenting part is the specific area your fingers would meet at the cervix — for the ideal baby, the vertex. The denominator, used for naming position, is the occiput.",
    },
    {
      type: "table",
      title: "Three questions, three answers",
      body: "| Question the examiner asks | Term | Possible answers | The answer you hope for |\n|---|---|---|---|\n| How is the baby's spine aligned with the mother's? | Lie | Longitudinal, oblique, transverse | Longitudinal |\n| What part is at the cervical door? | Presentation | Vertex, sinciput, brow, face, breech, shoulder | Vertex (flexed cephalic) |\n| Which way does the denominator face? | Position | LOA, OA, ROA, LOT, ROT, LOP, ROP, OP (for vertex) | Anterior positions — LOA or OA |\n\nNotice the ladder of logic: lie first (is the baby straight?), then presentation (what leads?), then position (which direction?). Every palpation and every referral sentence is built in that order.",
    },
    {
      type: "text",
      title: "Position: the denominator's address",
      body: "To name position, pick a landmark on the presenting part called the denominator — the occiput for a vertex baby, the sacrum for breech, the mentum (chin) for face, and the acromion (shoulder) for shoulder presentation. Then state where that landmark sits relative to the mother's pelvis: front, back, left or right.\n\nFor the vertex there are eight positions: left and right occipito-anterior (LOA, ROA), left and right occipito-transverse (LOT, ROT), left and right occipito-posterior (LOP, ROP), and the two direct positions — occipito-anterior (OA) and occipito-posterior (OP). Many babies sit around occipito-transverse or slightly anterior as labour begins, then rotate as they descend.\n\nThe heart of it: find the back, and the occiput is usually its neighbour. A baby with its back on the mother's left front is very likely LOA.",
    },
    {
      type: "quiz_prompt",
      title: "What is missing from this note?",
      body: "A classmate writes on the notes: 'Lie longitudinal, presentation vertex, position: left.' What information is missing from the position, and what would a complete entry look like?\n\nAnswer: Position needs the denominator's side AND direction — anterior, transverse or posterior. A complete entry would be, for example, 'position LOA' (left occipito-anterior). 'Left' alone does not tell the next caregiver whether to expect an easy anterior rotation or a back-grinding posterior labour.",
    },
    {
      type: "memory_trick",
      title: "Same side of the house",
      body: "When you locate the fetal back on the mother's abdomen, the occiput almost always keeps to that same side: back on the left and front → think LOA; back on the right and front → think ROA; back toward the mother's spine → posterior positions (LOP, ROP or OP). For denominators, remember the ladder: Occiput rules the crown, Sacrum the seat, Mentum the chin, Acromion the shoulder.",
    },
    {
      type: "text",
      title: "Reading the abdomen: what palpation is actually asking",
      body: "Abdominal palpation — commonly taught as Leopold's manoeuvres — asks four questions in order, with warm hands, an empty bladder and the woman lying comfortably with knees slightly bent. First: what is in the fundus? A hard, round, ballotable mass is a head; a soft, irregular mass is a breech. Second: where is the back? A firm, flat wall of resistance on one side, with small limbs kicking on the other. Third: what is presenting above the pelvis, and has it engaged? Fourth: where does the occiput face, confirming flexion and position?\n\nYou will learn this skill under supervision — hands-on, corrected in real time by an experienced midwife, because fingertips learn from feedback. What you can own from today is the interpretation: given the findings, state lie, presentation and position as one sentence — 'longitudinal lie, vertex presentation, back left anterior — LOA.'",
    },
    {
      type: "clinical_pearl",
      title: "The description that moves patients",
      body: "On referral or handover, 'transverse lie at 38 weeks' or 'breech at term in a first-time mother' is a sentence that mobilises senior review and delivery planning. Vague words like 'the baby feels across' do not. Precision in these three terms is not academic polish — it is how the system decides where this woman should deliver, and when.",
    },
    {
      type: "case",
      title: "The 39-week check",
      body: "Mimie, you are the student midwife at the antenatal desk, with a senior midwife palpating beside you. Madam Zenabu is 39 weeks into her second pregnancy. The fundus feels soft and irregular — not the hard ball of a head. Low down, just above the pubic bone, there is a hard, round mass. The firm, flat back lies on the left, toward the front; small parts kick on the right. The head is not yet engaged.\n\nWhat is sitting in the fundus, and how do you know? Put the whole picture into one proper sentence — lie, presentation, position. And if the head is still high at 39 weeks in a second pregnancy, is that automatically alarming — and whose judgement is that call?\n\nThe proper sentence: 'Longitudinal lie, cephalic — vertex — presentation, back left anterior, likely LOA, head not yet engaged.' A soft, irregular fundal mass is the breech pole; a hard, round lower pole is the head. A high head at term in a second-time mother can be perfectly normal, but engagement is exactly the kind of finding you report so the senior midwife can judge the delivery plan — in a first pregnancy, a head that never engages deserves closer attention.",
    },
    {
      type: "quiz_prompt",
      title: "Name the position from the back",
      body: "Palpation report: the back is firm and flat on the mother's right side toward the front; limbs are easily felt on the left; the presenting part is a well-flexed vertex. Give the position in proper notation — and why did you not need any further detective work?\n\nAnswer: ROA — right occipito-anterior. The back and the occiput keep to the same side of the house, so a right-anterior back with a vertex presentation gives ROA directly. Knowing one landmark gives you the other.",
    },
    {
      type: "text",
      title: "Which positions travel best",
      body: "Anterior positions (LOA, OA, ROA) are the well-trodden path: the occiput leads, the head stays flexed, and descent rotates the baby through the pelvis presenting the smallest diameters. Posterior positions (LOP, ROP, OP) are the scenic detour: labour often runs longer, the mother feels intense backache — the baby's spine grinding her sacrum — and while many rotate late, some need help and senior decision-making.\n\nTransverse positions of the occiput (LOT, ROT) are mid-stations: most rotate to anterior with good contractions and descent.\n\nYour student role in all of this is pattern recognition, charting and flagging deviations. 'Second baby, OP, backache severe since this morning' is a sentence a senior midwife wants to hear early, not late.",
    },
    {
      type: "quiz_prompt",
      title: "The referral-level finding",
      body: "A woman at term is diagnosed with a transverse lie at a routine ANC visit. What is the core clinical concern once her membranes rupture — and which single action is not yours to take?\n\nAnswer: The concern is obstruction of labour and the risk of cord or arm prolapse when the waters break — a referral-level finding needing senior delivery planning. Any attempt to correct the lie is a specialist skill, never a student action: your role is accurate description, documentation and supporting referral.",
    },
    {
      type: "text",
      title: "Why the mechanics care",
      body: "Think of the pelvis as a curving corridor and the head as a key that fits best in one orientation. A well-flexed vertex in an anterior position presents its smallest diameter to the corridor and presses the cervix evenly — encouraging steady dilation and descent, engine and steering in harmony.\n\nDeviate on any axis — an extended head presenting brow or face, a posterior occiput, or a transverse lie — and the same journey must be negotiated with a poorer key. Some corridors still open; many need more time, more skill, and sometimes a different door entirely (or a different facility). That is the entire reason lie, presentation and position are the first triad you learn in midwifery: they predict the traffic.",
    },
    {
      type: "summary",
      title: "In one minute",
      body: "- Lie = the baby's long axis versus the mother's: longitudinal, oblique, transverse — longitudinal is the goal.\n- Presentation = the part at the cervical door: vertex is best; brow and face are the extended, unfavourable cephalics; breech and shoulder follow.\n- Position = where the denominator points: occiput (vertex), sacrum (breech), mentum (face), acromion (shoulder).\n- Back and occiput live on the same side of the house: left-anterior back in a vertex baby → LOA; right-anterior → ROA; back toward the spine → posterior positions.\n- Anterior positions travel best; posterior ones bring longer labours and backache; transverse lie at term is referral territory with cord-prolapse risk.\n- Palpation (Leopold's manoeuvres) is a supervised skill — your job today is fluent interpretation and precise reporting.\n- Say the full sentence: lie, presentation, position — vagueness like 'the baby feels across' changes nothing; precision moves patients.",
    },
  ],
  questions: [
    {
      topic: "Fetal Position Assessment",
      type: "CLINICAL_SCENARIO",
      difficulty: "Moderate",
      stem: "At 38 weeks you assist with abdominal palpation: the fundus holds a soft, irregular mass; just above the pubis is a hard, round mass; the back is firm and flat on the left toward the front; limbs kick on the right. What is the correct summary description?",
      options: [
        "Transverse lie, shoulder presentation, back anterior",
        "Longitudinal lie, cephalic (vertex) presentation, position likely LOA",
        "Longitudinal lie, breech presentation, position ROP",
        "Oblique lie, face presentation, position ROA",
      ],
      correctIndex: 1,
      explanation: "A soft, irregular mass in the fundus is the breech pole, and a hard, round mass above the pubis is the head — spine aligned with spine means longitudinal lie with a cephalic presentation. The firm flat back on the left front, with limbs on the right, points to a left-anterior position, and for a flexed vertex that means LOA. Reading palpation findings into the three-term sentence is the skill this question rehearses — fundus, back, lower pole, in that order.",
      whyOthers: {
        A: "A transverse lie would put the head and breech in the mother's flanks, not in fundus and pelvis — the poles are stacked vertically here, proving longitudinal.",
        C: "The hard, round, lower mass is the head presenting; the breech is up in the fundus — this is cephalic, not breech.",
        D: "Nothing suggests an oblique lie or an extended head — the finding described is the textbook picture of a flexed vertex in an anterior position.",
      },
      courseSlug: "normal-labour",
    },
    {
      topic: "Fetal Position Assessment",
      type: "MCQ",
      difficulty: "Easy",
      stem: "A baby is presenting breech. When documenting position, which landmark is the denominator?",
      options: [
        "The occiput",
        "The mentum (chin)",
        "The sacrum",
        "The anterior fontanelle",
      ],
      correctIndex: 2,
      explanation: "Each presentation carries its own naming landmark — its denominator: the occiput for vertex, the sacrum for breech, the mentum for face, and the acromion for shoulder. So a breech baby with its sacrum toward the mother's left front is LSA — left sacro-anterior. Mixing denominators is the classic documentation error, and it garbles the message the next caregiver receives.",
      whyOthers: {
        A: "The occiput is the denominator for vertex presentations — in breech, the occiput of the flexed head sits up in the fundus, leading nothing.",
        B: "The mentum is the denominator for face presentations, not breech.",
        D: "Fontanelles are used to assess flexion and descent on vaginal examination, not as the denominator for breech position.",
      },
      courseSlug: "normal-labour",
    },
    {
      topic: "Labour Complications",
      type: "CLINICAL_SCENARIO",
      difficulty: "Clinical Reasoning",
      stem: "A woman at 39 weeks with a known transverse lie telephones the ward: her waters have just broken. What is the appropriate response from the student midwife who takes the call?",
      options: [
        "Reassure her that waters breaking at term is normal and review can wait until contractions are regular",
        "Tell her to come to the facility immediately, and alert the senior midwife at once — a transverse lie with ruptured membranes risks cord prolapse and needs emergency review",
        "Advise her to monitor at home for six hours and call back only if she sees the cord at the opening",
        "Book her an ambulance for tomorrow morning and advise her to avoid walking in the meantime",
      ],
      correctIndex: 1,
      explanation: "With a transverse lie, nothing fills the pelvis to keep the cord above the baby — so when membranes rupture, cord prolapse becomes a live, time-critical danger to the baby. The correct move is immediate transfer plus immediate escalation so the receiving team is ready; delay for monitoring or for tomorrow is how a preventable emergency becomes a tragedy. Recognising which findings convert a routine phone call into an emergency is exactly the reasoning this topic trains.",
      whyOthers: {
        A: "The lie — not the broken waters — is the danger here: waiting for contractions in a transverse lie with ruptured membranes courts cord prolapse and obstruction.",
        C: "Waiting to see the cord means waiting for the complication to arrive; the emergency is the risk, not the visible cord, and by the time it is visible the clock is already running.",
        D: "Tomorrow morning is a full night of prolapse risk; a known transverse lie with SROM is a now-problem requiring emergency assessment.",
      },
      courseSlug: "normal-labour",
    },
    {
      topic: "Fetal Position Assessment",
      type: "TRUE_FALSE",
      difficulty: "Moderate",
      stem: "True or false: in a vertex presentation, the denominator is the anterior fontanelle.",
      options: [
        "True",
        "False",
        "True, but only when the head is well flexed",
        "True, because the fontanelle is the leading part",
      ],
      correctIndex: 1,
      explanation: "The denominator for vertex presentation is the occiput — the landmark that names positions like LOA, ROA and OP. The fontanelles are certainly landmarks on the fetal skull, and you will use them on vaginal examination to judge flexion and position — but naming rights belong to the occiput. Keeping 'occiput = occipito-anterior/posterior' straight is what makes position notation readable across every chart and every exam.",
      whyOthers: {
        A: "This would scramble the entire naming system — LOA means left occipito-anterior, not left fontanelle-anterior.",
        C: "When the head is well flexed the occiput leads — which is precisely why the occiput is the denominator; flexion makes the fontanelle follow, not lead.",
        D: "In a flexed vertex the leading area is the vertex just posterior to the anterior fontanelle, with the occiput as the naming landmark — the fontanelle never serves as denominator.",
      },
      courseSlug: "normal-labour",
    },
    {
      topic: "Labour Mechanics",
      type: "MCQ",
      difficulty: "Hard",
      stem: "A woman in established labour has severe, continuous lower back pain that worsens with contractions; the fetal limbs are easily felt on both sides of the midline and the back is hard to define. Which position group best fits this picture?",
      options: [
        "Occipito-anterior (LOA or ROA)",
        "Occipito-posterior (LOP, ROP or OP)",
        "Left occipito-transverse (LOT)",
        "Breech with an anterior sacrum",
      ],
      correctIndex: 1,
      explanation: "This is the classic posterior-position presentation: the baby's spine lies against the mother's spine, grinding her sacrum with every contraction — hence severe backache — while the small limbs present forward, felt easily on both sides of the midline. Anterior positions give a firm, clearly one-sided back; a breech would put a soft fundal mass where the head should be. Posterior labours are often longer and many rotate late — exactly why your accurate charting of the pattern matters to the senior team.",
      whyOthers: {
        A: "An anterior position puts the back firmly on one side of the mother's abdomen with a clear margin, not limbs everywhere and an elusive back.",
        C: "An occipito-transverse baby still has a definable back on one flank; the bilateral limbs and backache point posterior, not transverse.",
        D: "Nothing in the scenario describes a fundal breech or a breech presenting part — the story is a vertex baby facing the wrong way.",
      },
      courseSlug: "normal-labour",
    },
    {
      topic: "Labour Complications",
      type: "MULTI_SELECT",
      difficulty: "Hard",
      stem: "A 39-week woman having her first baby is found to have a transverse lie at ANC. Select all appropriate elements of the response.",
      options: [
        "Senior review and a delivery-planning discussion that includes referral options",
        "Counselling the woman to come in immediately if her waters break or labour begins",
        "Clear documentation of lie, presentation and engagement status for the next caregiver",
        "The student attempting to turn the baby at the ANC desk before senior assessment",
      ],
      correctIndexes: [0, 1, 2],
      explanation: "A transverse lie at term in a first-time mother is a planning problem: the senior team needs to decide about mode and place of delivery, and the woman needs to understand why the normal wait-for-strong-contractions advice does not apply to her. Careful documentation carries the finding to the next visit, and the come-in-immediately instruction covers the prolapse risk. Everything about correcting the lie — external version — is a specialist procedure requiring skill, consent and emergency backup; it is never a student manoeuvre.",
      whyOthers: {
        D: "Attempting version at the desk is outside a student's scope on every axis — skill, consent, monitoring and emergency preparedness — and an uncorrected lie is safer than a badly attempted one.",
      },
      courseSlug: "normal-labour",
    },
    {
      topic: "Fetal Position Assessment",
      type: "MCQ",
      difficulty: "Moderate",
      stem: "During palpation the fetal back is clearly felt on the mother's right side toward the front, with limbs on the left; the presenting part is a well-flexed vertex. Which position will you chart?",
      options: [
        "LOA",
        "ROA",
        "LOP",
        "ROP",
      ],
      correctIndex: 1,
      explanation: "The occiput keeps house with the back: a right-anterior back in a vertex presentation means the occiput points to the mother's right front — right occipito-anterior, ROA. LOA would need a left-anterior back, and the posterior labels would need the back (and occiput) directed toward the mother's spine. This one inference — back position to occiput position — is the fastest bedside shortcut you will ever own.",
      whyOthers: {
        A: "LOA requires the back and occiput on the mother's left front — the mirror image of this finding.",
        C: "LOP needs the occiput directed backward on the left — here the back is palpable anteriorly, which is incompatible with a posterior occiput.",
        D: "ROP needs the occiput pointing back on the right — an anterior, right-sided back rules that out.",
      },
      courseSlug: "normal-labour",
    },
  ],
  flashcards: [
    {
      topic: "Fetal Lie",
      front: "Define fetal lie and list its three types.",
      back: "The relationship of the baby's long axis to the mother's long axis: longitudinal (aligned), oblique (diagonal), transverse (across). Longitudinal is the goal at term.",
    },
    {
      topic: "Fetal Position",
      front: "Name the denominator for vertex, breech, face and shoulder presentations.",
      back: "Vertex → occiput; breech → sacrum; face → mentum (chin); shoulder → acromion. Occiput rules the crown, Sacrum the seat, Mentum the chin, Acromion the shoulder.",
    },
    {
      topic: "Fetal Position",
      front: "How do you convert a felt fetal back into a vertex position?",
      back: "Back and occiput live on the same side: left-anterior back → LOA; right-anterior back → ROA; back toward the mother's spine → posterior positions (LOP/ROP/OP).",
    },
    {
      topic: "Labour Complications",
      front: "Why is transverse lie at term a referral-level concern?",
      back: "Nothing fills the pelvis, so labour obstructs — and when membranes rupture, the cord or an arm can prolapse. It needs senior review, delivery planning, and instructions to come in immediately if waters break.",
    },
    {
      topic: "Leopold's Manoeuvres",
      front: "What four questions does abdominal palpation answer, in order?",
      back: "1) What is in the fundus (head or breech)? 2) Where is the back? 3) What is presenting above the pelvis, and is it engaged? 4) Where does the occiput face — flexion and position?",
    },
    {
      topic: "Fetal Position",
      front: "What does LOA stand for, and describe the finding.",
      back: "Left occipito-anterior: longitudinal lie, vertex presentation, fetal back on the mother's left front, limbs on the right — the most favourable common position.",
    },
  ],
  sources: [
    {
      organization: "Elsevier",
      title: "Myles Textbook for Midwives",
      year: "2020 (17th edition)",
      note: "Educational source — verify current edition.",
    },
    {
      organization: "Elsevier (Baillière Tindall)",
      title: "Mayes' Midwifery: A Textbook for Midwives",
      year: "2019 (14th edition)",
      note: "Educational source — verify current edition.",
    },
    {
      organization: "World Health Organization",
      title: "Managing complications in pregnancy and childbirth: a guide for midwives and doctors",
      year: "2017 (2nd edition)",
      note: "Educational source — referral and emergency reasoning; verify current edition.",
    },
  ],
};
