import type { SeedFullLesson } from "../types";

export const lessonAnatomicalPosition: SeedFullLesson = {
  courseSlug: "anatomy-physiology-1",
  moduleTitle: "The Language of the Body",
  lessonTitle: "Anatomical Position: The Language of the Human Body",
  description: "Before you can chart a fundus, describe a fetal back, or hand over a wound, you need the one position every health worker on earth agrees on. Let's learn the language your entire career will be written in.",
  difficulty: "Easy",
  durationMin: 12,
  objectives: [
    "By the end you can describe standard anatomical position precisely — including what the palms and feet are doing.",
    "By the end you can use the six core directional pairs: superior/inferior, anterior/posterior, medial/lateral, proximal/distal, superficial/deep, ipsilateral/contralateral.",
    "By the end you can name the three anatomical planes and state what each one divides.",
    "By the end you can interpret chart phrases like fundus two finger-breadths below the umbilicus without hesitating.",
    "By the end you can explain why one shared reference position prevents dangerous miscommunication at handover.",
  ],
  tags: ["anatomy", "directional terms", "body planes", "clinical communication"],
  sourceStatus: "PROPOSED",
  sections: [
    {
      type: "callout",
      title: "Why this matters",
      body: "Every chart you will ever write, every handover you will ever give, and every fetal position you will ever describe assumes one agreed starting pose. Anatomical position is that agreement. Learn it once, properly, and the sentence 'the wound is 3 cm superior to the umbilicus' means exactly the same thing in Accra, in Kumasi and in every exam hall you will ever enter.",
    },
    {
      type: "text",
      title: "The one position everyone agrees on",
      body: "Picture a person standing upright, facing you, with feet flat on the floor and toes pointing straight ahead. The arms hang relaxed at the sides and — the part everyone forgets — the palms face forward, so the thumbs point away from the body. The head is level and the eyes look straight ahead.\n\nThat single pose is standard anatomical position, and every direction word in medicine is defined from it. It feels oddly stiff because it is a reference, not a habit — nobody stands like that in real life, and that is exactly the point.\n\nLike the zero mark on a ruler, it only works if it never changes. Clinically, that is its whole power: when any nurse in any facility says inferior, you already know which way she means.",
    },
    {
      type: "quiz_prompt",
      title: "Quick check: the palms",
      body: "A classmate swears that in anatomical position the palms face backward with the thumbs resting against the thighs. Where do the palms actually face, and what happens to the two forearm bones when they face that way?\n\nAnswer: The palms face forward with thumbs pointing away from the body — and in that pose the radius and ulna lie parallel. Copy the pose with your own hands and you will feel the bones untwist.",
    },
    {
      type: "text",
      title: "Directional terms: six pairs that do all the work",
      body: "Simply first: superior means toward the head and inferior means toward the feet. Anterior means toward the front of the body, posterior toward the back. Medial means nearer the midline — the invisible line splitting the body into equal halves — and lateral means further from it.\n\nProximal and distal describe limbs: proximal is nearer the trunk, distal is further from it. Superficial means closer to the skin, deep means further in. When two structures sit on the same side of the body they are ipsilateral; on opposite sides, contralateral.\n\nClinically these are the working words of your charts. At 20 weeks the fundus rises to about the level of the umbilicus and then climbs superior to it; after birth it shrinks back inferior to it. The baby's back may press against the mother's anterior abdominal wall. Same words, every day, forever.",
    },
    {
      type: "table",
      title: "Directional terms at a glance",
      body: "| Pair | Plain meaning | Where you will meet it |\n|---|---|---|\n| Superior / Inferior | Toward the head / toward the feet | Fundal height described above or below the umbilicus |\n| Anterior / Posterior | Front / back | The fetal back on the anterior or posterior abdominal wall |\n| Medial / Lateral | Nearer the midline / further from it | An injection landmark described medial to a structure |\n| Proximal / Distal | Nearer the trunk / further along a limb | A drip site chosen distal to a previous bruise |\n| Superficial / Deep | Closer to the skin / further in | A superficial wound versus a deep tissue injury |\n| Ipsilateral / Contralateral | Same side / opposite side | Referred pain felt contralateral to its source |",
    },
    {
      type: "memory_trick",
      title: "SCoT: the three planes",
      body: "SCoT keeps the planes in their lanes: Sagittal Splits left from right, Coronal Cuts front from back, and Transverse Takes off the top, dividing superior from inferior. Say it aloud three times and it will hold through every exam you sit.",
    },
    {
      type: "text",
      title: "The three planes: imaginary slices with real jobs",
      body: "Imagine slicing the standing body with a sheet of invisible glass. A vertical slice straight down the middle splits left from right — that is the sagittal plane, and it is called mid-sagittal (or median) when it passes through the exact midline. A vertical slice from shoulder to shoulder splits front from back — the coronal or frontal plane. A horizontal slice, like a blade passing at waist height, divides top from bottom — the transverse plane.\n\nClinically, the planes quietly organise your day. Fundal height is a transverse level — the umbilicus names a horizontal line across the abdomen. The quadrants you will use to describe a fetal back are drawn with coronal and sagittal lines.\n\nEven scan reports speak this language: a transverse view of the uterus is a different picture from a sagittal one, and knowing the difference makes your requests and reports make sense.",
    },
    {
      type: "table",
      title: "The planes and what they divide",
      body: "| Plane | Orientation | Divides the body into | Where you meet it |\n|---|---|---|---|\n| Sagittal (mid-sagittal at the exact midline) | Vertical, front-to-back | Left and right portions | Describing structures left or right of the midline |\n| Coronal (frontal) | Vertical, side-to-side | Anterior and posterior portions | Locating the fetal back; describing the abdominal wall |\n| Transverse (axial) | Horizontal | Superior and inferior portions | Fundal height levels; standard ultrasound slice views |",
    },
    {
      type: "clinical_pearl",
      title: "Palms forward is not a small detail",
      body: "With palms forward, the radius and ulna lie parallel; in every other hand position they cross. When a forearm diagram confuses you, copy the pose with your own hands before you doubt your understanding — the artist drew anatomical position, and your relaxed wrists are doing something different. Examiners know this is where students slip, so check the palms first.",
    },
    {
      type: "text",
      title: "Common confusions — and how to dodge them",
      body: "Relative beats absolute. Nothing is simply proximal: the elbow is proximal to the wrist but distal to the shoulder. Always ask — proximal to what?\n\nAnterior and posterior belong to the patient, never to you. If she lies on her left side facing you, her anterior surface now faces your right, but the words do not flip because she did. Charts are written from the body's point of view for exactly this reason.\n\nAnd superficial does not mean trivial. A superficial wound can sit a few millimetres above something that matters enormously.",
    },
    {
      type: "quiz_prompt",
      title: "Translate the chart note",
      body: "A postnatal note reads: fundus firm, midline, two finger-breadths below the umbilicus. Where is the fundus relative to the umbilicus, in proper directional language — and which plane does that measuring line run along?\n\nAnswer: The fundus is inferior to the umbilicus, two finger-breadths toward the feet, and the measurement runs along a transverse level of the abdomen — which is why fundal checks are always described relative to a horizontal landmark.",
    },
    {
      type: "case",
      title: "The ward round note",
      body: "Mimie, you are the student nurse on the postnatal ward. A woman delivered six hours ago. The nurse palpates and asks you to record the findings: the fundus is firm, in the midline, about three finger-breadths superior to the umbilicus; a small dressing covers a wound two centimetres lateral to the midline on the anterior abdominal wall.\n\nBefore the nurse glances over: which single word tells the next shift exactly where the wound sits without any diagram? Rewrite 'below the belly button' in words a nurse in another region could picture instantly. And if you were asked whether the wound is superficial or deep, what extra information would you need?\n\nNotice how much precision four little words carry: superior, midline, lateral, anterior. Zero ambiguity, no diagram required — that is the entire promise of anatomical language.",
    },
    {
      type: "quiz_prompt",
      title: "Two pairs at once",
      body: "No chart in sight: the kneecap sits on the front of the leg — but is it superior or inferior to the navel, and proximal or distal to the hip?\n\nAnswer: Inferior to the navel (closer to the feet) and distal to the hip (further from the trunk along the limb). Two different pairs, both true at the same time — that is the everyday texture of anatomical language.",
    },
    {
      type: "summary",
      title: "In one minute",
      body: "- Standard anatomical position: standing upright, facing forward, eyes level, arms at the sides, palms facing forward, feet parallel and pointing straight ahead.\n- Superior/inferior (head/feet), anterior/posterior (front/back) and medial/lateral (toward or away from the midline) are defined from the body's own perspective.\n- Proximal/distal belong to limbs — nearer or further from the trunk; superficial/deep describe distance from the skin.\n- Ipsilateral means same side, contralateral means opposite side.\n- SCoT: Sagittal splits left/right, Coronal cuts front/back, Transverse takes the top.\n- Palms forward makes radius and ulna parallel — the detail that betrays a rushed student in viva.\n- Chart phrases like 'fundus two finger-breadths inferior to the umbilicus' are directions, landmarks and planes working as one.",
    },
  ],
  questions: [
    {
      topic: "Anatomical Position",
      type: "MCQ",
      difficulty: "Easy",
      stem: "You are revising the forearm before an anatomy test and the diagram shows the radius and ulna lying perfectly parallel to each other. What does this tell you about the hand in that drawing?",
      options: [
        "The palms face anteriorly — the bones only lie parallel in the standard anatomical position",
        "The palms face posteriorly, because relaxed arms at the sides naturally untwist the bones",
        "The hand is gripping an object, and gripping straightens both bones",
        "Nothing — the radius and ulna are parallel in every possible hand position",
      ],
      correctIndex: 0,
      explanation: "The radius and ulna are parallel only when the forearm is supinated — palms facing forward, as in standard anatomical position. In pronation (palms back), the radius crosses over the ulna, so the parallel bones in the diagram are a fingerprint of anatomical position. This is why the palm detail is not decoration: it fixes the position of the forearm bones, and therefore every description built upon them.",
      whyOthers: {
        B: "With the palms facing posteriorly the forearm is pronated and the radius crosses the ulna — the bones are not parallel.",
        C: "Gripping involves the finger flexors and has nothing to do with the parallel alignment of the two forearm bones, which depends on supination.",
        D: "The bones are parallel only in supination; pronation deliberately crosses them, which is how your hand can turn a doorknob.",
      },
      courseSlug: "anatomy-physiology-1",
    },
    {
      topic: "Directional Terms",
      type: "MCQ",
      difficulty: "Moderate",
      stem: "A nurse charts a newborn's cord stump as '2 cm inferior to the umbilicus, midline, anterior abdominal wall'. Which restatement of that note is correct?",
      options: [
        "The stump is 2 cm below the umbilicus, on the front of the body, in the midline",
        "The stump is 2 cm above the umbilicus, on the front of the body, in the midline",
        "The stump is 2 cm below the umbilicus, on the back of the body, right of the midline",
        "The stump is level with the umbilicus, on the side of the body, in the midline",
      ],
      correctIndex: 0,
      explanation: "Inferior means toward the feet, anterior means toward the front, and midline means on the median sagittal line — so the note describes a point 2 cm below the navel, on the front, in the middle. Translating chart shorthand into plain language, and back again, is a daily ward skill. Notice how three terms replaced an entire diagram.",
      whyOthers: {
        B: "Above the umbilicus would be superior — the opposite direction to the note.",
        C: "The back is posterior, not anterior, and midline rules out any rightward offset.",
        D: "A point 2 cm inferior lies below the level of the umbilicus, not level with it, and the side of the body is neither anterior nor midline.",
      },
      courseSlug: "anatomy-physiology-1",
    },
    {
      topic: "Clinical Application",
      type: "CLINICAL_SCENARIO",
      difficulty: "Clinical Reasoning",
      stem: "Day one after a normal birth, the fundus is firm but palpable three finger-breadths above the umbilicus. Using directional language and what you know of normal postnatal involution, which interpretation fits best?",
      options: [
        "The fundus is inferior to the umbilicus, which is expected on day one",
        "The fundus is superior to the umbilicus; at one day postpartum it is usually much closer to the umbilicus, so this height should prompt checks such as bladder fullness and a report to the nurse in charge",
        "The fundus is posterior to the umbilicus, suggesting an abnormally tilted uterus",
        "The fundus is lateral to the umbilicus, which is a harmless variation needing no action",
      ],
      correctIndex: 1,
      explanation: "Three finger-breadths superior to the umbilicus is high for day one — after delivery the uterus normally sits at or just below the umbilicus and descends daily. A high fundus can signal a full bladder (the most common innocent cause), retained products, or another problem, and it deserves measurement, reassessment after bladder emptying and a report. This question tests whether you can pair directional language with clinical meaning — exactly what ward work demands.",
      whyOthers: {
        A: "The note says the fundus is above the umbilicus — superior, not inferior — and it is unusually high for day one regardless.",
        C: "Posterior describes depth relative to the abdominal wall, not height; a tilted uterus would not present as a raised palpable fundus in this way.",
        D: "Lateral displacement can occur with a full bladder, but dismissing any day-one deviation as harmless is not a safe habit — the finding must be reported and rechecked.",
      },
      courseSlug: "anatomy-physiology-1",
    },
    {
      topic: "Directional Terms",
      type: "TRUE_FALSE",
      difficulty: "Easy",
      stem: "True or false: in a person standing in anatomical position, the knee is distal to the hip and proximal to the ankle.",
      options: [
        "True",
        "False",
        "True only when the palms face backward",
        "True only when the person is lying flat",
      ],
      correctIndex: 0,
      explanation: "Proximal and distal are relative terms along a limb: the knee is further from the trunk than the hip (distal to it) but closer to the trunk than the ankle (proximal to it). One structure can therefore be both, depending on its comparison partner. Directional terms are anchored to the body's standard anatomical frame, so the answer does not depend on hand position or posture.",
      whyOthers: {
        B: "False would claim one of the two relationships fails, but both hold — the knee sits between hip and ankle along the lower limb.",
        C: "The position of the hands has no bearing on terms describing the lower limb, which are judged by distance from the trunk.",
        D: "Directional language is defined from the standard anatomical frame and applies whether the patient stands, sits or lies — charts never depend on posture.",
      },
      courseSlug: "anatomy-physiology-1",
    },
    {
      topic: "Body Planes",
      type: "MCQ",
      difficulty: "Moderate",
      stem: "When you plot fundal height, you imagine a horizontal line across the mother's abdomen at the level of the umbilicus. Which plane is that line parallel to?",
      options: [
        "The sagittal plane",
        "The coronal plane",
        "The transverse plane",
        "The mid-sagittal plane",
      ],
      correctIndex: 2,
      explanation: "A horizontal line across the abdomen runs in the same direction as a transverse (axial) slice, which divides the body into superior and inferior portions. Fundal height is literally reported as a transverse level — at, above or below the umbilicus. Recognising the plane behind the landmark turns charting from memory work into simple geometry.",
      whyOthers: {
        A: "The sagittal plane is vertical and splits the body into left and right portions — it is perpendicular to a horizontal abdominal line.",
        B: "The coronal plane is also vertical, dividing front from back, so it cannot be parallel to a horizontal measuring line.",
        D: "The mid-sagittal plane is simply the sagittal plane at the exact midline — vertical like the others, not horizontal.",
      },
      courseSlug: "anatomy-physiology-1",
    },
    {
      topic: "Clinical Communication",
      type: "CLINICAL_SCENARIO",
      difficulty: "Hard",
      stem: "Handover at 07:00: 'Wound on the left anterior thigh, about a hand's breadth distal to the inguinal crease, superficial.' Which action shows you understood the handover correctly?",
      options: [
        "Inspect the front of the right thigh, one hand's breadth below the groin crease",
        "Inspect the front of the left thigh, one hand's breadth below the groin crease, checking near the skin surface",
        "Inspect the back of the left thigh, one hand's breadth below the buttock crease",
        "Inspect the left lower abdomen at the level of the hip bone",
      ],
      correctIndex: 1,
      explanation: "Anterior means front, left means the patient's own left, distal to the inguinal crease means a hand's breadth down the thigh from the groin, and superficial means near the skin. Together they point to one small patch of the body with no diagram needed. Getting all four right is the difference between a wound that gets inspected and one that gets missed.",
      whyOthers: {
        A: "Right is contralateral to the stated side — left and right in charts always belong to the patient, never to the observer.",
        C: "The back of the thigh is posterior, not anterior — the wound is described on the front.",
        D: "The inguinal crease marks the groin fold at the top of the thigh; distal to it lies along the thigh, not up on the abdomen.",
      },
      courseSlug: "anatomy-physiology-1",
    },
    {
      topic: "Directional Terms",
      type: "MULTI_SELECT",
      difficulty: "Moderate",
      stem: "Select every statement that uses anatomical terminology correctly.",
      options: [
        "The heart lies posterior to the sternum",
        "The umbilicus lies inferior to the pubic symphysis",
        "The fingers are distal to the wrist",
        "The ears are medial to the eyes",
      ],
      correctIndexes: [0, 2],
      explanation: "The heart does sit behind the sternum (posterior to it), and the fingers are further from the trunk than the wrist (distal to it) — both statements are correct. The umbilicus lies above the pubic symphysis, so it is superior, not inferior; and the ears are further from the midline than the eyes, so they are lateral, not medial. Multi-select questions reward slow, term-by-term checking rather than pattern recognition.",
      whyOthers: {
        B: "The umbilicus sits above the pubic symphysis, making it superior — the statement reverses the relationship.",
        D: "The eyes are nearer the midline than the ears; the ears are the lateral pair, so the statement is backwards.",
      },
      courseSlug: "anatomy-physiology-1",
    },
  ],
  flashcards: [
    {
      topic: "Anatomical Position",
      front: "Describe standard anatomical position in one breath.",
      back: "Standing upright, facing forward, eyes level, arms relaxed at the sides, palms facing forward with thumbs away from the body, feet parallel and pointing straight ahead.",
    },
    {
      topic: "Directional Terms",
      front: "Superior vs inferior — which way is which?",
      back: "Superior = toward the head; inferior = toward the feet. Example: at term the fundus rises superior to the umbilicus; postnatally it descends inferior to it.",
    },
    {
      topic: "Directional Terms",
      front: "Proximal vs distal — how do you keep them apart?",
      back: "Proximal = nearer the trunk along a limb; distal = further from the trunk. The knee is proximal to the ankle but distal to the hip — relative, never absolute.",
    },
    {
      topic: "Body Planes",
      front: "Which plane divides the body into left and right, and which divides front from back?",
      back: "Sagittal divides left from right (mid-sagittal at the exact midline); coronal divides anterior from posterior; transverse divides superior from inferior. SCoT: Splits, Cuts, Takes the top.",
    },
    {
      topic: "Directional Terms",
      front: "Medial vs lateral — one-line memory.",
      back: "Medial = closer to the midline (the nose is medial to the eyes); lateral = further from the midline (the ears are lateral to the eyes).",
    },
  ],
  sources: [
    {
      organization: "OpenStax (Rice University)",
      title: "Anatomy and Physiology 2e",
      year: "2022",
      url: "https://openstax.org/books/anatomy-and-physiology-2e",
      note: "Free, peer-reviewed textbook. Educational source — verify current edition.",
    },
    {
      organization: "Elsevier",
      title: "Gray's Anatomy for Students",
      year: "2020 (4th edition)",
      note: "Educational source — verify current editions and use alongside your course texts.",
    },
    {
      organization: "Pearson",
      title: "Martini: Fundamentals of Anatomy and Physiology",
      year: "2021 (11th edition)",
      note: "Educational source — verify current edition.",
    },
  ],
};
