import type { SeedFullLesson } from "../types";

export const lessonPrevention: SeedFullLesson = {
  courseSlug: "health-promotion-1",
  moduleTitle: "Prevention & Education",
  lessonTitle: "Prevention Before Treatment",
  description: "The best patient of your career will be the one who never falls sick because of something you taught her in ten minutes. Meet the three levels of prevention — the quiet superpower of midwifery.",
  difficulty: "Easy",
  durationMin: 14,
  objectives: [
    "By the end you can define the three levels of prevention and give one midwifery example of each.",
    "By the end you can classify any intervention — a bed net, a screening test, rehabilitation — into its prevention level.",
    "By the end you can explain why a single antenatal visit weaves all three levels together.",
    "By the end you can design a short health education message a woman can actually act on.",
    "By the end you can describe where community-level prevention happens in Ghana — ANC clinics, health centres and CHPS zones.",
  ],
  tags: ["health promotion", "prevention levels", "health education", "community health"],
  sourceStatus: "PROPOSED",
  sections: [
    {
      type: "callout",
      title: "Why this matters",
      body: "Surgery saves one person at a time; prevention saves whole communities. In Ghana, midwives are often the most trusted health voice a woman has — the person she tells her real symptoms, her real plans and her real fears. Health promotion is where that trust turns into lower maternal and newborn illness. This lesson is the theory behind the softest, most powerful skill you own.",
    },
    {
      type: "text",
      title: "Three levels, one idea",
      body: "Simply first: prevention comes in three flavours. Primary prevention stops disease before it starts — bed nets, immunisation, good nutrition in pregnancy. Secondary prevention catches disease early, while it is still cheap and easy to treat — screening tests, growth monitoring, checking blood pressure at every ANC visit. Tertiary prevention limits the damage of disease that already exists — rehabilitation, support and preventing recurrence.\n\nThe classic picture is a river: primary prevention stops people falling in upstream; secondary throws them a rope while they are still swimming; tertiary pulls them out downstream and helps them recover.\n\nClinically, midwifery lives in all three — often within the same ten-minute antenatal contact.",
    },
    {
      type: "table",
      title: "The three levels in maternity practice",
      body: "| Level | When it acts | Goal | Midwifery examples |\n|---|---|---|---|\n| Primary | Before disease exists | Stop it starting | Antenatal health education, balanced diet in pregnancy, insecticide-treated bed nets, tetanus immunisation through ANC, family planning counselling, clean birth preparation |\n| Secondary | Early disease, few or no symptoms | Detect and treat early | Blood pressure check at every ANC visit, haemoglobin and infection screening at booking, fetal growth monitoring, partograph use in labour |\n| Tertiary | Established disease | Limit damage, prevent recurrence | Rehabilitation and reintegration support after obstetric fistula repair, mental-health support after a traumatic birth, structured follow-up after severe pre-eclampsia |",
    },
    {
      type: "memory_trick",
      title: "Please Screen Today",
      body: "The three levels — Primary, Secondary, Tertiary — become Please Screen Today. Primary PLEASES the healthy (keeps them well), Secondary SCREENS the silent (finds disease early), Tertiary TAMES the established (limits damage). If a question blurs the levels, ask the river question: is this stopping the fall, catching the swimmer, or rescue-and-rebuild?",
    },
    {
      type: "text",
      title: "The ANC visit: all three levels in one room",
      body: "Watch a single antenatal contact through a prevention lens. You check her blood pressure — secondary prevention, hunting pre-eclampsia before it produces symptoms. You counsel on nutrition and sleep under a net — primary prevention. For a woman whose previous pregnancy ended in a stillbirth, your extra vigilance and honest discussion are both secondary (intensified screening) and tertiary (limiting the damage of the past).\n\nThis is why prevention is not a separate chapter of midwifery — it is the weave of the job. Even the casual question about how she will reach the facility in labour ('who will bring you if it is 2 am?') is prevention: a birth plan is an emergency plan, and emergency plans save mothers.",
    },
    {
      type: "text",
      title: "Health education is one tool; health promotion is the whole workshop",
      body: "Health education — the advice and teaching you give — is the part people see. Health promotion is broader: everything that makes the healthy choice possible, from the existence of the clinic itself to a national bed net programme to the mother-in-law's approval of the net.\n\nThe Ottawa Charter, the founding document of modern health promotion, framed it as building healthy public policy, creating supportive environments, strengthening community action, developing personal skills (that is your teaching) and reorienting services toward prevention.\n\nSimply put: you educate the woman, but you promote health when the community around her moves too. That is why a great ANC talk and a CHPS compound doing home visits are partners, not rivals.",
    },
    {
      type: "clinical_pearl",
      title: "Education is dosed like medicine",
      body: "Health education works when it is short, specific and actionable — one behaviour per contact, phrased in the woman's own terms. 'Eat more dark leaves, beans and small fish' beats 'improve your nutrition'; 'sleep under the net every night, even when it is hot' beats 'prevent malaria'. If she cannot repeat the action back to you, the message was not received.",
    },
    {
      type: "case",
      title: "The Tuesday clinic",
      body: "Mimie, you are the student midwife at a busy Tuesday antenatal clinic. Three women are waiting. Madam Yaa, 20 weeks into her first pregnancy, has no complaints — her blood pressure is normal, and she asks why she should sleep under a net when she has never had malaria. Madam Dzigbordi, 28 weeks, had a booking pressure of 124/76 and records 138/88 today, with mild swelling of her fingers. Madam Afiba delivered her first baby by caesarean two years ago and wants to know whether her next birth must also be by caesarean.\n\nWhich level of prevention is your net conversation with Madam Yaa — and what one sentence could make it stick? Madam Dzigbordi's pressure change: which level catches this, and whose decision is the response? Madam Afiba's question: which level serves her, and what does safe counselling look like when you are the student in the room?\n\nThree chairs, three levels, ten minutes each — and notice that two of your three best interventions today are sentences, not procedures. (For the record: Madam Dzigbordi's reading goes straight to the midwife in charge for review, and Madam Afiba's birth-mode question belongs to senior counselling — your part is to listen well and support the plan.)",
    },
    {
      type: "quiz_prompt",
      title: "Classify the three chairs",
      body: "Classify quickly, before the answer: (a) haemoglobin screening at booking; (b) advising a new mother to keep the cord stump clean and dry; (c) supporting a woman with postnatal depression back to full functioning. Which level is which?\n\nAnswer: (b) is primary — it stops infection starting; (a) is secondary — it detects anaemia early; (c) is tertiary — it limits the damage of established illness. Ask the river question whenever the levels blur: before, early, or after.",
    },
    {
      type: "text",
      title: "Where prevention lives in Ghana",
      body: "Prevention in Ghana travels on infrastructure you can see: the antenatal clinic at the district hospital, the health centre, and the CHPS zone — Community-based Health Planning and Services — which takes basic primary care and health education into communities, with community health officers and volunteers on its frontline.\n\nMaternal health promotion also rides on national programmes: insecticide-treated net distribution for pregnant women, tetanus immunisation through ANC, skilled birth attendance campaigns and newborn care messaging, organised through Ghana Health Service structures down to the district level.\n\nYou do not need to memorise programme documents as a student — you need to know that the woman in front of you is connected to them, and that your counselling is often the bridge she crosses to reach them.",
    },
    {
      type: "text",
      title: "Behaviour change: the gentle mechanics",
      body: "People rarely change behaviour because of fear or facts alone; they change when the new behaviour is easy, socially approved and visibly worth it. So make it easy ('tie the net up over the mattress corner so it drops in one pull'), make it approved (enlist the husband or mother-in-law, who often guard the household's sleep and food decisions), and make it worth it (link it to the baby: 'malaria in pregnancy can make the baby arrive early and small').\n\nThen return to it. One-off advice evaporates; the follow-up question at the next visit — 'how did the sleeping under the net go?' — is the booster dose of health education.",
    },
    {
      type: "quiz_prompt",
      title: "The polite smile problem",
      body: "A woman smiles politely at your advice, and you suspect nothing will change at home. What is the smallest redesign of the message that turns advice into action — and who else might you involve?\n\nAnswer: Give her one specific action she can picture doing tonight, and bring the household decision-makers into the conversation. Behaviour follows ease and approval — vague advice, however correct, rarely survives the walk home.",
    },
    {
      type: "summary",
      title: "In one minute",
      body: "- Primary prevention stops disease before it starts; secondary finds it early and treats it cheaply; tertiary limits the damage of established disease.\n- Ask the river question: stop the fall, catch the swimmer, or rescue-and-rebuild?\n- A single ANC visit weaves all three levels — screening, counselling and follow-up of past events.\n- Education is dosed: one behaviour per contact, specific, actionable, in her own words, revisited next time.\n- Ghana's prevention network includes ANC clinics, health centres and CHPS zones reaching communities directly.\n- Involve household decision-makers — approval at home decides whether advice becomes behaviour.\n- In prevention, your strongest instruments are sentences.",
    },
  ],
  questions: [
    {
      topic: "Levels of Prevention",
      type: "MCQ",
      difficulty: "Easy",
      stem: "At an ANC visit you counsel a pregnant woman to sleep under an insecticide-treated bed net every night. Which level of prevention is this?",
      options: [
        "Primary prevention — the intervention stops malaria infection from starting",
        "Secondary prevention — the net screens for early malaria",
        "Tertiary prevention — it limits damage from established malaria",
        "Curative care, not prevention, since nets contain insecticide",
      ],
      correctIndex: 0,
      explanation: "The woman does not have malaria; the net stops infection before it ever begins, which is the definition of primary prevention. Secondary prevention would be detecting an existing problem early (like a rapid diagnostic test at a fever visit), and tertiary prevention would be limiting damage after disease is established. Sleeping arrangements that prevent the mosquito bite remove the cause entirely — the purest form of prevention.",
      whyOthers: {
        B: "Screening applies to a disease that has begun — the net stops infection occurring at all, which is primary.",
        C: "There is no established disease to limit — tertiary prevention begins after illness exists.",
        D: "The insecticide on the net repels or kills mosquitoes before any bite transmits malaria; the woman is not being treated for anything.",
      },
      courseSlug: "health-promotion-1",
    },
    {
      topic: "Levels of Prevention",
      type: "CLINICAL_SCENARIO",
      difficulty: "Moderate",
      stem: "A woman at 28 weeks records a blood pressure of 138/88, up from 124/76 at booking, during a routine ANC check. In prevention terms, what does the blood pressure check represent — and what happens next?",
      options: [
        "Primary prevention — the visit itself has protected her from pre-eclampsia",
        "Secondary prevention — it detects a possible hypertensive disorder early — and the reading must be reported now to the midwife in charge for review and follow-up",
        "Tertiary prevention, because a rise in blood pressure means established disease",
        "It is not prevention at all, since the finding requires medical treatment",
      ],
      correctIndex: 1,
      explanation: "The blood pressure check is textbook secondary prevention: detecting disease at a stage before symptoms, when management can still change the outcome. A rise from her own booking baseline is exactly what screening is designed to catch — and the response (review, repeat measurement, further assessment of protein and symptoms) belongs to the qualified midwife or clinician, today, not at the next visit. The student's contribution is accurate measurement and immediate reporting.",
      whyOthers: {
        A: "Primary prevention acts before disease exists; by the time a baseline shift is detectable, you are detecting — not preventing onset.",
        C: "A single elevated reading is a screening signal, not established disease — tertiary prevention applies after diagnosis and damage, which is not yet the situation.",
        D: "Screening remains prevention even when it triggers treatment — early detection is what makes the eventual treatment short, cheap and effective.",
      },
      courseSlug: "health-promotion-1",
    },
    {
      topic: "Levels of Prevention",
      type: "TRUE_FALSE",
      difficulty: "Moderate",
      stem: "True or false: tertiary prevention means preventing a disease from ever occurring in the first place.",
      options: [
        "True",
        "False",
        "True, but only in chronic disease",
        "True, but only when rehabilitation is available",
      ],
      correctIndex: 1,
      explanation: "Preventing a disease from ever occurring is the definition of primary prevention, the upstream end of the river. Tertiary prevention operates downstream: the disease already exists, and its aim is to limit damage, prevent recurrence and restore function — physiotherapy after a stroke, support after fistula repair. Keeping the two apart matters because exam questions — and clinic plans — hinge on which end of the river you are standing on.",
      whyOthers: {
        A: "This reverses the definitions: tertiary is the last line of defence after disease, primary is the first line before it.",
        C: "Chronic disease is where tertiary prevention is most visible, but its definition never changes — it acts after disease is established.",
        D: "Rehabilitation is one form of tertiary prevention, not a condition that redefines the level itself.",
      },
      courseSlug: "health-promotion-1",
    },
    {
      topic: "Levels of Prevention",
      type: "MCQ",
      difficulty: "Hard",
      stem: "Which of the following is LEAST likely to be primary prevention?",
      options: [
        "Counselling a pregnant woman on eating dark green leaves, beans and small fish",
        "Tetanus immunisation given through antenatal care",
        "Physiotherapy and community reintegration support after obstetric fistula repair",
        "Advising a family to sleep under insecticide-treated nets every night",
      ],
      correctIndex: 2,
      explanation: "Fistula repair rehabilitation is the textbook face of tertiary prevention: the injury has occurred, and the intervention limits its damage and restores function. Nutrition counselling, immunisation and net use all act before disease exists, which is the primary level. Notice how the least-likely question rewards calm classification over memorised lists — run each option through the river test: does it stop the fall, or rebuild after the rescue?",
      whyOthers: {
        A: "Improving pregnancy nutrition before any deficiency disease appears is primary prevention at work.",
        B: "Immunisation protects against tetanus before exposure causes disease — a flagship primary prevention activity in ANC.",
        D: "Net use prevents the infecting mosquito bite from ever happening — primary prevention against malaria.",
      },
      courseSlug: "health-promotion-1",
    },
    {
      topic: "Health Education",
      type: "CLINICAL_SCENARIO",
      difficulty: "Clinical Reasoning",
      stem: "A pregnant woman at 26 weeks admits she rarely sleeps under her insecticide-treated net because it feels hot. Which response is most likely to change her behaviour?",
      options: [
        "Warn her firmly that malaria in pregnancy can kill both her and the baby, and insist she complies",
        "Acknowledge that the net feels hot, suggest tying it up so it drops in one pull at bedtime, link net use to protecting her baby from being born too early or too small, and ask how it went at the next visit",
        "Give her a leaflet on malaria prevention to read at home",
        "Tell her the pharmacist has stronger options she can ask about",
      ],
      correctIndex: 1,
      explanation: "Behaviour change follows ease, approval and perceived benefit — not fear alone. This response removes the practical barrier (one-pull net arrangement), gives a reason that matters to her (the baby arriving healthy), and schedules follow-up, which is the booster dose of education. Fear-based messages often produce polite nods and no change; specific, kind, revisited messages move households. This is the craft of health promotion in a single sentence.",
      whyOthers: {
        A: "Fear raises anxiety but rarely changes behaviour on its own — and an insisting tone can close the conversation she was brave enough to start.",
        C: "A leaflet without conversation rarely survives the journey home; written material supports counsel, it does not replace it.",
        D: "Deferring to the pharmacist abandons your teaching role and hints at medication where the effective intervention is behavioural and free.",
      },
      courseSlug: "health-promotion-1",
    },
    {
      topic: "Antenatal Screening",
      type: "MULTI_SELECT",
      difficulty: "Moderate",
      stem: "Select all activities that are secondary prevention in a maternity setting.",
      options: [
        "Blood pressure measurement at every antenatal visit",
        "Haemoglobin screening at booking",
        "Counselling a well mother on exclusive breastfeeding",
        "Syphilis screening during antenatal care",
      ],
      correctIndexes: [0, 1, 3],
      explanation: "Secondary prevention is detection of silent or early disease: blood pressure checks catch hypertensive disorders before symptoms, haemoglobin screening reveals anaemia before collapse, and syphilis screening finds an infection that benefits both mother and baby from early treatment. Counselling a well mother on breastfeeding is primary prevention — it stops illness (like diarrhoeal disease and infection) from starting. One contact can mix levels, and sorting them sharpens your clinical eye.",
      whyOthers: {
        C: "Breastfeeding support for a currently well mother protects health before disease exists — that is primary prevention, valuable but on the other side of the river.",
      },
      courseSlug: "health-promotion-1",
    },
    {
      topic: "Community Health",
      type: "MCQ",
      difficulty: "Moderate",
      stem: "A community health officer in a CHPS zone plans home visits to teach pregnant families about newborn danger signs before their babies arrive. Which level of prevention is this work?",
      options: [
        "Primary prevention — the families are well, and education aims to stop illness and delay in care-seeking before it starts",
        "Secondary prevention, because danger signs are a screening list",
        "Tertiary prevention, because it follows up after births in the community",
        "Curative care, because danger signs lead to treatment",
      ],
      correctIndex: 0,
      explanation: "CHPS-zone health education delivered before illness exists is primary prevention in its purest community form: knowledge that stops late recognition and late care-seeking from ever becoming a tragedy. The danger-sign list is used at home before any disease appears — education, not screening of an affected patient. When the same officer later assesses an already-sick newborn, that encounter shifts to other levels — one worker, several hats.",
      whyOthers: {
        B: "Screening (secondary) involves testing or examining to detect existing disease; teaching families before illness is upstream of that.",
        C: "The visits happen before and around births, not after established disease — tertiary prevention acts after damage exists.",
        D: "No treatment is given during the teaching visit — curative care belongs to the encounters the education prepares families to seek early.",
      },
      courseSlug: "health-promotion-1",
    },
  ],
  flashcards: [
    {
      topic: "Levels of Prevention",
      front: "Define the three levels of prevention in one line each.",
      back: "Primary stops disease before it starts; secondary detects and treats it early; tertiary limits damage and prevents recurrence after disease is established.",
    },
    {
      topic: "Levels of Prevention",
      front: "The river analogy — which level is which part?",
      back: "Primary stops people falling in upstream; secondary throws a rope while they are still swimming; tertiary pulls them out downstream and rebuilds. Ask: before, early, or after?",
    },
    {
      topic: "Antenatal Screening",
      front: "Classify the routine blood pressure check at ANC.",
      back: "Secondary prevention — it detects hypertensive disorders of pregnancy before symptoms, enabling early review and management.",
    },
    {
      topic: "Health Education",
      front: "How do you make health education stick?",
      back: "One specific action per contact, phrased in her own words; involve household decision-makers; revisit at the next contact — follow-up is the booster dose.",
    },
    {
      topic: "Community Health",
      front: "What is CHPS in the Ghanaian health system?",
      back: "Community-based Health Planning and Services — the frontline that takes primary care and health education into communities through community health officers and volunteers.",
    },
  ],
  sources: [
    {
      organization: "World Health Organization",
      title: "WHO recommendations on antenatal care for a positive pregnancy experience",
      year: "2016",
      url: "https://www.who.int/publications/i/item/9789241549912",
      note: "Educational source — verify current edition.",
    },
    {
      organization: "World Health Organization",
      title: "The Ottawa Charter for Health Promotion",
      year: "1986",
      note: "Foundational health promotion framework. Educational source.",
    },
    {
      organization: "Ghana Health Service",
      title: "Community-based Health Planning and Services (CHPS) programme",
      note: "Educational description — verify current GHS programme documents for operational details.",
    },
    {
      organization: "Banarsidas Bhanot",
      title: "Park's Textbook of Preventive and Social Medicine",
      note: "Educational source — verify current edition.",
    },
  ],
};
