import type { SeedFullLesson } from "../types";

export const lessonHomeostasis: SeedFullLesson = {
  courseSlug: "anatomy-physiology-1",
  moduleTitle: "Homeostasis & Balance",
  lessonTitle: "Why Homeostasis Matters",
  description: "Your body runs a silent thermostat for temperature, sugar, salt and pressure — every second of every day. Learn the loop behind it and you will suddenly understand why a rising pulse in a postpartum woman is a message, not just a number.",
  difficulty: "Moderate",
  durationMin: 15,
  objectives: [
    "By the end you can define homeostasis and name the three components of a negative feedback loop.",
    "By the end you can trace one full loop — such as thermoregulation — from stimulus to correction.",
    "By the end you can distinguish negative from positive feedback and give a physiological example of each.",
    "By the end you can explain why labour is a healthy positive feedback loop while a fever is a shifted set point.",
    "By the end you can recognise what compensated blood loss looks like clinically, and why early reporting matters.",
  ],
  tags: ["homeostasis", "feedback loops", "thermoregulation", "compensation"],
  sourceStatus: "PROPOSED",
  sections: [
    {
      type: "callout",
      title: "Why this matters",
      body: "Homeostasis is the reason a body can be quietly unwell before it looks unwell. Midwives read compensation for a living — the pulse that rises before the pressure falls, the fever that spikes before the shiver. Master the loop behind these shifts, and the observation chart becomes a story you can actually read.",
    },
    {
      type: "text",
      title: "The body's thermostat",
      body: "Simply first: your body keeps its inside conditions steady — temperature, blood sugar, water, salt, oxygen, pressure — the way a thermostat keeps a room at one set temperature. Small drifts away from the set point trigger automatic corrections that push conditions back. That steady state has a name: homeostasis.\n\nThe thermostat analogy hides one beautiful detail: your body has no single thermostat. It runs thousands of tiny control loops at once, layered on each other. A pregnant woman runs these loops for two, with the placenta and the growing baby adding fresh demands to every one of them.\n\nClinically, the word you will actually use is 'stable'. When you say a woman is stable, you are really saying her control loops are currently winning.",
    },
    {
      type: "text",
      title: "The loop that keeps everything steady",
      body: "Every negative feedback loop has three players. A sensor (receptor) detects a change and reports it. A control centre compares the change against the set point and decides what to do. An effector carries out the correction — and the result feeds back to switch the loop off.\n\nTake a hot afternoon in Tamale. Receptors in the skin and deep tissues detect the temperature rising. The hypothalamus — your control centre — compares that against the set point. Effectors act: sweat glands open, skin blood vessels widen, and heat leaves the body. As temperature returns to set point, sweating is turned down. Job done, loop closed.\n\nNotice the name: negative feedback means the response negates the stimulus. It is not negative in the emotional sense — it is the body's most polite and most powerful habit.",
    },
    {
      type: "quiz_prompt",
      title: "Blood pressure falls — who does what?",
      body: "A woman's blood pressure drops. Which part of the loop are the stretch receptors in her carotid arteries, and which effector does the control centre order into action?\n\nAnswer: The carotid receptors are the sensors, and the heart is the main effector — it beats faster and harder, with blood vessels tightening to support it. Sensors detect, the brainstem decides, effectors act, and the falling pressure is pushed back toward its set point.",
    },
    {
      type: "table",
      title: "Homeostasis loops you will meet on the ward",
      body: "| Controlled variable | Sensors | Control centre | Effectors | Ward clue |\n|---|---|---|---|---|\n| Temperature | Skin and deep thermoreceptors | Hypothalamus | Sweat glands, skin blood vessels, shivering muscles | Fever, flushing, rigors |\n| Blood pressure | Stretch receptors in the carotid arteries and aorta | Medulla oblongata | Heart rate and force; blood vessel width | Pulse climbing before pressure falls |\n| Blood glucose | Glucose-sensing cells in the pancreas | Pancreas, with the liver | Insulin and glucagon release | Shakiness, drowsiness, unusual thirst |\n| Body water | Osmoreceptors | Hypothalamus, acting via ADH | Kidneys and thirst | Concentrated urine, dry mouth |",
    },
    {
      type: "text",
      title: "Positive feedback: the loop that amplifies",
      body: "Negative feedback resists change. Positive feedback does the opposite: the response increases the original stimulus, and the loop accelerates until something external switches it off.\n\nYour two career-defining examples: blood clotting, where activated factors activate more factors until a clot seals the vessel, and labour. As the fetal head distends the cervix, oxytocin release surges; stronger contractions cause more distension; more distension releases more oxytocin. The loop ends not when a set point is restored, but when the baby is born and the stimulus — cervical stretch — is removed.\n\nA circuit breaker that never trips becomes a hazard. That is why the body uses positive feedback rarely, and always with a built-in ending.",
    },
    {
      type: "clinical_pearl",
      title: "The loop that ends the loop",
      body: "In labour, the positive feedback loop's off-switch is the birth of the baby. The same uterine machinery that was amplifying all day remains primed in the minutes after birth — one reason the immediate postpartum hour is watched so closely in every delivery setting. Respect that hour; it is homeostasis' most exposed moment.",
    },
    {
      type: "memory_trick",
      title: "Detect, Decide, Deliver",
      body: "Remember every negative feedback loop as Detect → Decide → Deliver. The receptor Detects, the control centre Decides, the effector Delivers the correction. If the names ever fade, picture a security guard who spots trouble (detect), radios control (decide), and sends backup (deliver).",
    },
    {
      type: "text",
      title: "When the loop fights for your patient: compensation",
      body: "Here is where homeostasis becomes clinical. When blood volume drops — say, after a childbirth haemorrhage — the baroreceptor loop does not wait politely. The heart rate climbs and vessels tighten, so blood pressure holds almost normal... for a while.\n\nThe loop is winning, so the chart looks reassuring. But it is paying for that appearance, and the pulse rate is the price tag. A young woman with a rising pulse and a 'normal' blood pressure after delivery is not stable — she is compensated, and compensation has a deadline.\n\nThis is why observations matter as a trend, not as single numbers. A pulse of 96, then 110, then 124 across three checks is a story the loop is telling you. Read it early, escalate early — recognition and reporting are the student midwife's superpower.",
    },
    {
      type: "quiz_prompt",
      title: "The quiet postpartum trend",
      body: "One hour after birth, a woman's pulse moves from 84 to 102 to 118 across three observations. Her blood pressure is still 108/70, and she is pale but calm. Which single observation should concern you most — and what does it say about the blood pressure reading?\n\nAnswer: The rising pulse is the concerning finding — in a compensated patient, tachycardia appears before blood pressure falls, so a 'normal' BP must not be read as reassurance. The pattern calls for immediate reporting to the midwife in charge so bleeding can be ruled out early.",
    },
    {
      type: "case",
      title: "The quiet delivery room",
      body: "Mimie, you are the student midwife on the evening shift. Madam Adjoa delivered a healthy boy 40 minutes ago. She is chatty, breastfeeding, and says she feels 'fine, just tired'. The midwife asks you to do the 40-minute fourth-stage observations while she attends another woman.\n\nYou find: fundus firm and central, moderate lochia, pulse 112 (it was 88 during labour), blood pressure 106/64, skin slightly cool and pale, and a little restlessness between her sentences.\n\nWhich observation is out of step with her own baseline? What could a quietly rising pulse at 40 minutes postpartum mean even when the fundus feels firm? What is your best move as the student — recheck quietly in an hour, or report now? And what exactly would you say to the midwife in charge so she can act fast?\n\nNotice the shape of this case: nothing is dramatic, and that is precisely the trap. Compensation is quiet by design — your job is to notice the pattern and report it, not to diagnose it alone.",
    },
    {
      type: "quiz_prompt",
      title: "Shivering: which loop, whose set point?",
      body: "A woman feels cold and begins to shiver. Which feedback pattern does shivering belong to, and where does the body's temperature set point actually live?\n\nAnswer: Shivering is part of a negative feedback response to cold — effectors generating heat to push temperature back toward the set point, which lives in the hypothalamus. When infection resets that set point upward, the same machinery produces fever, and the body shivers its way up to the new target.",
    },
    {
      type: "text",
      title: "Fever: the loop with a moved goalpost",
      body: "A fever is not a broken thermostat — it is a temporarily reprogrammed one. Chemicals released during infection shift the hypothalamic set point upward, and the body then treats its old normal as 'too cold'.\n\nIt responds exactly as it would to cold: skin vessels constrict (the woman feels cold, looks pale, and may shiver violently — a rigor), and temperature climbs toward the new set point. That is why the chills often come before the thermometer peaks.\n\nThis is also why a woman in labour with rigors and fever needs urgent review — infection on the labour ward is never a wait-and-see problem. Recognise, report, refer.",
    },
    {
      type: "summary",
      title: "In one minute",
      body: "- Homeostasis is the maintenance of a steady internal environment — temperature, glucose, fluids, pressure and more.\n- Every negative feedback loop runs Detect → Decide → Deliver: receptor, control centre, effector.\n- Negative feedback reverses the stimulus; positive feedback amplifies it until an external event ends it.\n- Labour and blood clotting are the classic healthy positive feedback loops; daily homeostasis runs on negative feedback.\n- Compensation hides trouble: a rising pulse with a 'normal' BP after birth may mean blood loss — report the trend early.\n- Fever is a raised set point, not a failed loop — rigors are the body climbing to its new target.\n- Observation charts are homeostasis written down: read them as stories, not numbers.",
    },
  ],
  questions: [
    {
      topic: "Feedback Loops",
      type: "MCQ",
      difficulty: "Easy",
      stem: "During a heatwave, a pregnant woman begins to sweat and her skin flushes. Which statement best describes what is happening?",
      options: [
        "Positive feedback is amplifying the heat until she reaches a new set point",
        "Negative feedback has detected a rise above the set point, and effectors are returning her temperature toward it",
        "Her thermoregulatory loop has failed, and the set point is being reset upward",
        "Sweating is a voluntary cooling behaviour directed by the cerebral cortex",
      ],
      correctIndex: 1,
      explanation: "Sweating and skin flushing are classic negative feedback effectors: thermoreceptors detected a rise, the hypothalamus compared it with the set point, and heat-losing mechanisms were switched on to reverse the stimulus. The direction of the response — back toward the set point, not away from it — is the signature of negative feedback. Voluntary behaviours like seeking shade can help, but the sweating itself is automatic.",
      whyOthers: {
        A: "Positive feedback would intensify the original change — the body would become hotter and hotter, which is heat stroke territory, not the normal response.",
        C: "A failed or reset loop describes fever or malignant hyperthermia — flushing and sweating show the loop is working exactly as designed.",
        D: "Sweat glands are controlled automatically by the autonomic nervous system; the cerebral cortex handles conscious decisions like moving into shade.",
      },
      courseSlug: "anatomy-physiology-1",
    },
    {
      topic: "Compensation",
      type: "CLINICAL_SCENARIO",
      difficulty: "Clinical Reasoning",
      stem: "One hour after a normal delivery, a woman's pulse is 118 (booking baseline 88), blood pressure 104/66, skin pale and cool, and she is calm. Which interpretation fits best?",
      options: [
        "She is stable because her blood pressure is normal",
        "Her signs suggest she may be compensating for blood loss; the tachycardia deserves immediate escalation to the midwife in charge",
        "The tachycardia is a positive feedback loop triggered by breastfeeding and needs no action",
        "She is most likely chronically anaemic and can wait for review at the next routine visit",
      ],
      correctIndex: 1,
      explanation: "A stepwise-rising pulse with a still-normal blood pressure in the first postpartum hour is the textbook picture of compensation for volume loss: baroreceptor reflexes hold pressure by driving the heart harder. Compensated patients look deceptively calm — the calm is physiology, not safety. The correct student response is immediate reporting so the team can assess blood loss and act; tachycardia at rest is never dismissed after delivery.",
      whyOthers: {
        A: "Blood pressure is the late mover — it is held 'normal' precisely because the heart is paying for it with rate, so it cannot be used as the reassurance here.",
        C: "Breastfeeding does release oxytocin, but oxytocin does not produce a sustained pulse rise of this size — blaming a physiological loop without ruling out bleeding is dangerous.",
        D: "Chronic anaemia may lower baseline tolerance, but a rising trend after birth is an acute finding requiring now-action, not a routine visit.",
      },
      courseSlug: "anatomy-physiology-1",
    },
    {
      topic: "Feedback Loops",
      type: "ORDERING",
      difficulty: "Moderate",
      stem: "A woman stands up quickly and her blood pressure falls. Put the baroreceptor reflex in the correct order, from stimulus to correction.",
      options: [
        "Baroreceptors in the carotid arteries and aorta detect reduced stretch as pressure falls",
        "The cardiovascular control centre in the medulla compares the signal with the set point",
        "Sympathetic output rises: the heart beats faster and blood vessels narrow",
        "Blood pressure returns toward its set point and the reflex is dialled back down",
      ],
      explanation: "This is the Detect → Decide → Deliver sequence wearing its clinical clothes. The sensors fire first because nothing happens until the fall is detected; the medulla decides second because it is the control centre that knows the set point; the effectors (heart and vessels) act third; and the correction itself, plus the switching-off of the reflex, must come last. Misordering any pair breaks the logic of a feedback loop — a response cannot precede its detection, and the dialling-down cannot precede the response.",
      whyOthers: {
        A: "Detection must come first — without the baroreceptors reporting reduced stretch, no signal exists for the medulla to act on.",
        B: "The decision step belongs second: the control centre needs the sensory input before it can compare anything with the set point.",
        C: "The effector response belongs third — the heart and vessels only receive their instructions after the medulla has decided, and they must act before the pressure can recover.",
        D: "The return toward the set point is the outcome of the effector actions, so it must sit last, and it is also the signal that switches the reflex back down.",
      },
      courseSlug: "anatomy-physiology-1",
    },
    {
      topic: "Positive Feedback",
      type: "TRUE_FALSE",
      difficulty: "Moderate",
      stem: "True or false: the positive feedback loop of labour ends when a set point is restored.",
      options: [
        "True",
        "False",
        "True, but only in induced labours",
        "False, unless the placenta is retained",
      ],
      correctIndex: 1,
      explanation: "Positive feedback loops are not governed by set points at all — they amplify their stimulus until an external event removes it. In labour, that event is the birth of the baby: cervical stretch, the input driving the oxytocin surge, disappears when the baby is born. That is the opposite of negative feedback, which self-terminates by returning a variable to its set point. Knowing this difference explains why labour accelerates instead of stabilising.",
      whyOthers: {
        A: "True would describe negative feedback, where the loop switches itself off at the set point — labour does not work this way.",
        C: "The termination mechanism is the same whether labour starts spontaneously or is induced: the loop ends when the stimulus is removed, not at any set point.",
        D: "A retained placenta keeps some risk factors in play after birth, but the positive feedback loop itself still ends with delivery of the baby and loss of cervical stretch.",
      },
      courseSlug: "anatomy-physiology-1",
    },
    {
      topic: "Fever",
      type: "CLINICAL_SCENARIO",
      difficulty: "Hard",
      stem: "A woman in early labour suddenly feels intensely cold, shivers violently, and has a temperature of 38.9 °C. What is happening, and what does her situation demand?",
      options: [
        "Her thermoregulatory loop has failed, and she should be warmed with extra blankets to reset it",
        "Her hypothalamic set point has shifted upward, most likely in response to infection — chorioamnionitis must be considered, and she needs urgent review; as a student, your task is to report immediately",
        "This is normal thermoregulation during the transition from latent to active labour and needs no action",
        "The shivering is a positive feedback loop generating heat for labour, and it will end with delivery",
      ],
      correctIndex: 1,
      explanation: "Rigors with fever in labour are the body climbing to a newly raised hypothalamic set point — and on a labour ward, infection (including chorioamnionitis) is the first consideration that must be ruled out by senior staff. Fever in labour is associated with risks for both mother and baby and is never a wait-and-see finding. Your role as the student is precise measurement, documentation and immediate escalation — recognition, then referral, not self-management.",
      whyOthers: {
        A: "Warming a febrile patient fights the body's own response and worsens comfort; the thermostat is not broken, it is reset — the treatment question belongs to the clinicians.",
        C: "Temperature swings of this size with rigors are not part of normal latent-to-active transition; treating them as normal delays the review that matters.",
        D: "Shivering does generate heat, but as a response to a raised set point, not as labour's engine — waiting for delivery to solve an intrapartum fever is dangerous.",
      },
      courseSlug: "anatomy-physiology-1",
    },
    {
      topic: "Feedback Loops",
      type: "MCQ",
      difficulty: "Moderate",
      stem: "Which of these is the LEAST likely to be an example of negative feedback?",
      options: [
        "Breathing rate increases when blood carbon dioxide rises",
        "Cervical stretch triggers oxytocin release, which strengthens contractions and causes more cervical stretch",
        "Sweating increases when skin temperature rises",
        "Insulin release increases when blood glucose rises after a meal",
      ],
      correctIndex: 1,
      explanation: "The oxytocin-contraction-stretch cycle is the classic positive feedback loop of labour: the output of the loop increases the very input that drove it. Every other option reverses its stimulus — more CO2 is breathed off, heat is sweated out, glucose is driven back down — which is the fingerprint of negative feedback. Spotting the direction of the response is faster than memorising lists.",
      whyOthers: {
        A: "Rising CO2 driving faster ventilation to remove it is negative feedback — the response removes the stimulus.",
        C: "Sweating in response to heat, which then cools the body, is negative feedback — the stimulus is reversed.",
        D: "Insulin lowering post-meal glucose back toward the set point is one of the most familiar negative feedback loops in the body.",
      },
      courseSlug: "anatomy-physiology-1",
    },
    {
      topic: "Compensation",
      type: "MULTI_SELECT",
      difficulty: "Moderate",
      stem: "Select ALL findings that can be early signs that a postpartum woman's compensatory loops are under strain.",
      options: [
        "A pulse rising stepwise across consecutive observations",
        "Pale, cool, clammy skin despite a 'normal' blood pressure",
        "Increasing restlessness or faintness when she sits up to feed",
        "A fundus that is firm and central with light lochia",
      ],
      correctIndexes: [0, 1, 2],
      explanation: "Compensation announces itself through trends and quiet signs: a stepwise pulse rise is the heart paying for pressure, pale cool skin reflects blood diverted to core organs, and postural faintness signals a circulation under volume stress. These findings warrant prompt reporting and reassessment for blood loss. A firm central fundus with light lochia is a reassuring finding — though it never overrides the message of the other signs.",
      whyOthers: {
        D: "A well-contracted uterus with minimal lochia is exactly what you want to find — it points away from uterine atony as a bleeding source, but it does not erase the warning carried by the other findings.",
      },
      courseSlug: "anatomy-physiology-1",
    },
  ],
  flashcards: [
    {
      topic: "Homeostasis",
      front: "Define homeostasis in one sentence.",
      back: "The maintenance of a relatively stable internal environment — temperature, glucose, fluids, blood pressure — through automatic control loops.",
    },
    {
      topic: "Feedback Loops",
      front: "Name the three components of a negative feedback loop.",
      back: "Receptor (detects the change) → control centre (compares with the set point) → effector (carries out the correction). Detect, Decide, Deliver.",
    },
    {
      topic: "Feedback Loops",
      front: "How does positive feedback differ from negative feedback?",
      back: "Positive feedback amplifies the stimulus until an external event ends it (labour, clotting). Negative feedback reverses the stimulus back toward the set point and switches itself off.",
    },
    {
      topic: "Compensation",
      front: "Why can a postpartum woman have a 'normal' BP while losing significant blood?",
      back: "Baroreceptor compensation — the heart rate rises and vessels constrict to hold pressure, so tachycardia with a normal BP is an early warning. Report the trend, not the pressure.",
    },
    {
      topic: "Fever",
      front: "What is a fever, in loop terms?",
      back: "A hypothalamic set point temporarily raised by infection — the body then shivers and vasoconstricts to climb up to the new target (a rigor).",
    },
  ],
  sources: [
    {
      organization: "OpenStax (Rice University)",
      title: "Anatomy and Physiology 2e — Unit on Homeostasis",
      year: "2022",
      url: "https://openstax.org/books/anatomy-and-physiology-2e",
      note: "Free, peer-reviewed textbook. Educational source — verify current edition.",
    },
    {
      organization: "Elsevier",
      title: "Guyton and Hall Textbook of Medical Physiology",
      year: "2021 (14th edition)",
      note: "Educational source — verify current edition.",
    },
    {
      organization: "World Health Organization",
      title: "WHO recommendations for the prevention and treatment of postpartum haemorrhage",
      year: "2022",
      note: "Educational source — verify current edition and follow local protocols.",
    },
    {
      organization: "Elsevier",
      title: "Myles Textbook for Midwives",
      year: "2020 (17th edition)",
      note: "Educational source — verify current edition.",
    },
  ],
};
