// ─────────────────────────────────────────────────────────────
// MIMIE'S STUDY — CASE DETECTIVE HERO IMAGES
// AI-generated evocative scenes for each detective case, keyed to
// the order of `detectiveCases` in src/lib/game-content.ts.
// Generated by scripts/gen-case-images.ts (z-ai image generation,
// resumable). Pure data — no client/server deps.
// ─────────────────────────────────────────────────────────────

export interface CaseImage {
  src: string;
  alt: string;
}

export const caseImages: CaseImage[] = [
  {
    src: "/images/games/case-1.jpg",
    alt: "A Ghanaian midwife gently checking on a young mother resting in a warm, softly-lit district hospital postnatal ward — the quiet opening scene of a postpartum haemorrhage case.",
  },
  {
    src: "/images/games/case-2.jpg",
    alt: "A Ghanaian midwife measuring the blood pressure of a quietly worried young pregnant woman at a bright antenatal clinic — the opening scene of a pre-eclampsia case.",
  },
];
