// ─────────────────────────────────────────────────────────────
// MIMIE'S STUDY — CASE DETECTIVE HERO IMAGES
// AI-generated evocative scenes for each detective case, keyed to
// the order of `detectiveCases` in src/lib/game-content.ts.
// Generated by scripts/gen-case-images.ts (z-ai image generation,
// resumable). Pure data — no client/server deps.
// ─────────────────────────────────────────────────────────────

export interface CaseImage {
  src: string;
  alt: string;
}

export const caseImages: CaseImage[] = [
  {
    src: "/images/games/case-1.jpg",
    alt: "A Ghanaian nurse gently checking on an older man resting in a warm, softly-lit district hospital ward at night — the quiet opening scene of a sepsis case.",
  },
  {
    src: "/images/games/case-2.jpg",
    alt: "A Ghanaian nurse measuring the blood pressure of a middle-aged woman with a worried expression at her bedside — the opening scene of a chest pain case.",
  },
];
