// Shared image-search query plan (category, query sentence, tags, teaching caption)
export interface Query {
  c: string; // category / folder
  q: string; // search sentence
  t: string[]; // match tags
  cap: string; // teaching caption
}

export const QUERIES: Query[] = [
  // ── Year 1: basic sciences ──────────────────────────────
  { c: "cells", q: "human cell structure under microscope", t: ["cell", "cells", "organelles"], cap: "Real cells under the microscope — the tiny building blocks everything else is built from." },
  { c: "cells", q: "animal cell diagram with labeled organelles", t: ["cell", "organelles", "nucleus", "diagram"], cap: "A labelled map of the cell — learn the organelles like rooms in a house." },
  { c: "cells", q: "cell membrane phospholipid bilayer diagram", t: ["cell", "membrane", "transport"], cap: "The cell membrane — a selective gate that decides what enters and leaves." },
  { c: "cells", q: "mitosis cell division under microscope", t: ["cell", "mitosis", "division"], cap: "Cell division in action — growth and repair depend on this careful copying." },
  { c: "tissues", q: "epithelial tissue under microscope slide", t: ["tissue", "epithelial", "histology"], cap: "Epithelial tissue under the microscope — the covering and lining family." },
  { c: "tissues", q: "connective tissue microscope histology", t: ["tissue", "connective", "histology"], cap: "Connective tissue — the glue, rope and padding of the body." },
  { c: "skin", q: "human skin layers anatomy diagram", t: ["skin", "integumentary", "anatomy"], cap: "The skin's layers — your first barrier against the outside world." },
  { c: "skeleton", q: "human skeleton anatomy labeled", t: ["skeleton", "bones", "anatomy"], cap: "The living skeleton — a frame that stores calcium and makes blood." },
  { c: "skeleton", q: "female pelvis bones anatomy", t: ["pelvis", "bones", "female", "anatomy"], cap: "The female pelvis — the bony passage every baby must navigate at birth." },
  { c: "skeleton", q: "human skull bones anatomy", t: ["skull", "bones", "anatomy"], cap: "The skull — protecting the brain and shaping the face." },
  { c: "muscles", q: "skeletal muscle tissue histology", t: ["muscle", "tissue", "histology"], cap: "Muscle tissue up close — striped fibres built for movement and warmth." },
  { c: "muscles", q: "muscular system human body diagram", t: ["muscles", "muscular", "anatomy"], cap: "The muscular system — every move a mother makes in labour uses it." },
  { c: "heart", q: "human heart anatomy cross section", t: ["heart", "cardiovascular", "anatomy"], cap: "The heart's chambers — a double pump that never takes a break." },
  { c: "heart", q: "heart diagram blood flow through chambers", t: ["heart", "circulation", "blood"], cap: "Blood's route through the heart — follow the arrows and never get lost again." },
  { c: "blood", q: "red blood cells under microscope", t: ["blood", "cells", "red"], cap: "Red blood cells — biconcave discs built to carry oxygen." },
  { c: "blood", q: "white blood cells blood smear microscopy", t: ["blood", "immunity", "white"], cap: "White blood cells on a smear — the body's defence patrol." },
  { c: "blood", q: "sickle cell red blood cells microscope", t: ["sickle", "blood", "anaemia"], cap: "Sickle-shaped red cells — the anaemia you will screen for in Ghana." },
  { c: "lungs", q: "human lungs anatomy respiratory system", t: ["lungs", "respiratory", "anatomy"], cap: "The lungs — where every breath exchanges gases for life." },
  { c: "lungs", q: "alveoli gas exchange diagram", t: ["alveoli", "respiration", "lungs"], cap: "Alveoli — millions of tiny air sacs where oxygen crosses into blood." },
  { c: "digestion", q: "human digestive system anatomy diagram", t: ["digestive", "digestion", "anatomy"], cap: "The digestive tract — a nine-metre kitchen from mouth to anus." },
  { c: "kidneys", q: "kidney anatomy nephron diagram", t: ["kidney", "urinary", "nephron"], cap: "The nephron — the kidney's million tiny filters." },
  { c: "nerves", q: "neuron nerve cell structure diagram", t: ["neuron", "nerve", "nervous"], cap: "A neuron — the body's electrical wiring, one cell long as a metre." },
  { c: "nerves", q: "human brain anatomy diagram", t: ["brain", "nervous", "anatomy"], cap: "The brain — control centre for thought, temperature and hormones." },
  { c: "nerves", q: "spinal cord cross section anatomy", t: ["spinal", "nervous", "cord"], cap: "The spinal cord — the information highway protected by the spine." },
  { c: "endocrine", q: "endocrine system glands diagram", t: ["endocrine", "hormones", "glands"], cap: "The endocrine glands — chemical messengers released straight into blood." },
  { c: "endocrine", q: "thyroid gland anatomy", t: ["thyroid", "endocrine", "glands"], cap: "The thyroid — the butterfly gland that sets the body's speed." },
  { c: "endocrine", q: "pancreas insulin islets histology", t: ["pancreas", "insulin", "endocrine"], cap: "The pancreas — both a digestive helper and a hormone factory." },

  // ── Year 1–2: reproductive & pregnancy ──────────────────
  { c: "repro-female", q: "female reproductive system anatomy diagram", t: ["reproductive", "female", "uterus", "anatomy"], cap: "The female reproductive system — the anatomy at the heart of nursing." },
  { c: "repro-female", q: "uterus anatomy layers diagram", t: ["uterus", "reproductive", "anatomy"], cap: "The uterus — a muscle that grows a baby and then powers it out." },
  { c: "repro-female", q: "ovaries fallopian tubes anatomy", t: ["ovaries", "fallopian", "reproductive"], cap: "Ovaries and tubes — where eggs ripen and fertilisation happens." },
  { c: "repro-female", q: "cervix anatomy diagram", t: ["cervix", "reproductive", "anatomy"], cap: "The cervix — the gateway that softens and opens in labour." },
  { c: "repro-male", q: "male reproductive system anatomy diagram", t: ["male", "reproductive", "anatomy"], cap: "The male reproductive system — the other half of the fertility story." },
  { c: "repro-cycle", q: "menstrual cycle phases diagram hormones", t: ["menstrual", "cycle", "hormones", "reproductive"], cap: "The menstrual cycle — four acts guided by rising and falling hormones." },
  { c: "repro-embryo", q: "fertilization egg and sperm microscope", t: ["fertilization", "conception", "embryo"], cap: "Fertilisation — the moment egg and sperm become one new cell." },
  { c: "repro-embryo", q: "embryo development stages week by week", t: ["embryo", "development", "pregnancy"], cap: "The embryo week by week — from a dot to a recognisable baby." },
  { c: "repro-genetics", q: "human chromosomes karyotype", t: ["chromosomes", "genetics", "dna"], cap: "A karyotype — the 46 chromosomes that carry the instruction manual." },
  { c: "pregnancy", q: "pregnant woman third trimester belly", t: ["pregnancy", "trimester", "antenatal"], cap: "Third trimester — the uterus now reaches the ribs and the walk changes." },
  { c: "pregnancy", q: "nurse measuring fundal height pregnant woman", t: ["fundal", "height", "antenatal", "measurement"], cap: "Fundal height — centimetres from pubic bone to fundus roughly matching weeks after 20." },
  { c: "pregnancy", q: "nurse palpating pregnant abdomen", t: ["palpation", "abdomen", "fetal", "position"], cap: "Abdominal palpation — hands reading the baby's lie and position." },
  { c: "pregnancy", q: "fetal ultrasound scan screen image", t: ["ultrasound", "fetus", "scan"], cap: "An ultrasound scan — seeing the baby before meeting the baby." },
  { c: "pregnancy", q: "fetus inside womb illustration", t: ["fetus", "womb", "uterus"], cap: "The fetus in the womb — floating, cushioned and growing." },
  { c: "pregnancy", q: "antenatal care check up pregnant woman clinic Africa", t: ["antenatal", "check", "pregnancy", "clinic"], cap: "Antenatal check-up — the visit that catches problems before they catch mother or baby." },
  { c: "pregnancy", q: "pregnant woman blood pressure measurement", t: ["blood", "pressure", "pregnancy", "vital"], cap: "Blood pressure in pregnancy — the number that guards against pre-eclampsia." },
  { c: "pregnancy", q: "pregnant woman healthy food nutrition", t: ["nutrition", "pregnancy", "diet"], cap: "Eating for two, sensibly — iron, protein and folate in local foods." },
  { c: "pregnancy", q: "pregnant woman taking iron folate tablets", t: ["iron", "folate", "anaemia", "pregnancy"], cap: "Iron and folate tablets — the daily shield against anaemia." },

  // ── Labour & birth ──────────────────────────────────────
  { c: "labour", q: "nurse assisting woman during labour delivery", t: ["labour", "delivery", "nurse", "birth"], cap: "A nurse supporting a mother through birth — calm hands, watchful eyes." },
  { c: "labour", q: "woman in labour supported breathing", t: ["labour", "support", "breathing"], cap: "Breathing with the contraction — support that changes the experience of pain." },
  { c: "labour", q: "stages of labor cervical dilation diagram", t: ["cervix", "dilation", "labour", "stages"], cap: "Cervical dilation from 1 to 10 — the doorway opening for the baby." },
  { c: "labour", q: "partograph WHO form filled example", t: ["partograph", "labour", "monitoring"], cap: "The partograph — one page that tracks labour and flags danger early." },
  { c: "labour", q: "hospital delivery room labour ward", t: ["delivery", "room", "ward", "labour"], cap: "The delivery room — ready for both the routine and the emergency." },
  { c: "labour", q: "placenta examination after birth", t: ["placenta", "birth", "examination"], cap: "Checking the placenta — vessels, lobes and membranes, all accounted for." },
  { c: "labour", q: "delayed cord clamping newborn", t: ["cord", "clamping", "newborn", "birth"], cap: "Cord clamping — waiting a minute passes iron to the baby." },
  { c: "labour", q: "suturing perineal tear after birth", t: ["perineal", "suture", "tear", "repair"], cap: "Perineal repair — careful suturing protects healing and dignity." },
  { c: "labour", q: "caesarean section operation theatre", t: ["caesarean", "surgery", "theatre"], cap: "Caesarean section — a theatre team's fastest route when birth must hurry." },
  { c: "labour", q: "immediate newborn skin to skin mother", t: ["skin", "skin", "newborn", "warmth"], cap: "Skin-to-skin — the mother's chest is the newborn's first and best warmer." },

  // ── Newborn & feeding ───────────────────────────────────
  { c: "newborn", q: "newborn baby examination apgar check", t: ["newborn", "apgar", "examination"], cap: "The first examination — breathing, colour, tone and cry in the first minutes." },
  { c: "newborn", q: "newborn baby crying first minutes", t: ["newborn", "crying", "baby"], cap: "A strong first cry — the lungs opening for the first time." },
  { c: "newborn", q: "newborn baby weighing scale clinic", t: ["newborn", "weighing", "measurement", "baby"], cap: "Weighing the newborn — the first growth chart point." },
  { c: "newborn", q: "kangaroo mother care premature baby", t: ["kangaroo", "care", "premature", "newborn"], cap: "Kangaroo mother care — a mother's warmth working better than a machine." },
  { c: "newborn", q: "newborn jaundice phototherapy lights", t: ["jaundice", "phototherapy", "newborn"], cap: "Phototherapy — blue light that clears the newborn's bilirubin." },
  { c: "newborn", q: "premature baby incubator NICU", t: ["incubator", "nicu", "premature", "newborn"], cap: "The incubator — warmth, humidity and monitoring for the smallest fighters." },
  { c: "newborn", q: "newborn umbilical cord care clean stump", t: ["cord", "care", "hygiene", "newborn"], cap: "Clean and dry cord care — no applications, just watchful cleanliness." },
  { c: "newborn", q: "baby immunization vaccination injection thigh", t: ["immunization", "vaccination", "baby"], cap: "Immunisation — a tiny prick for a lifetime of protection." },
  { c: "feeding", q: "mother breastfeeding newborn good latch", t: ["breastfeeding", "latch", "feeding"], cap: "A good latch — more areola above than below, chin touching breast." },
  { c: "feeding", q: "breastfeeding positions cradle hold", t: ["breastfeeding", "position", "feeding"], cap: "Feeding positions — mother comfortable first, then baby latches." },
  { c: "feeding", q: "cup feeding newborn expressed breast milk", t: ["cup", "feeding", "expressed", "milk"], cap: "Cup feeding — expressed milk without confusing a young baby's suck." },

  // ── Infection control & skills ──────────────────────────
  { c: "hygiene", q: "nurse washing hands soap water", t: ["hand", "hygiene", "handwashing", "infection"], cap: "Handwashing — 40 to 60 seconds that protect every patient you touch." },
  { c: "hygiene", q: "hand hygiene five moments poster", t: ["hand", "hygiene", "moments", "infection"], cap: "WHO's five moments — the map of when hands must be cleaned." },
  { c: "hygiene", q: "alcohol hand rub healthcare worker", t: ["hand", "rub", "hygiene", "infection"], cap: "Alcohol hand rub — 20 to 30 seconds when hands are not visibly soiled." },
  { c: "ppe", q: "nurse wearing PPE gown gloves mask", t: ["ppe", "protective", "infection"], cap: "Full PPE — the armour for procedures and outbreaks." },
  { c: "ppe", q: "donning sterile surgical gloves", t: ["gloves", "sterile", "aseptic"], cap: "Sterile gloving — the hands stay sterile from pack to patient." },
  { c: "ppe", q: "surgical face mask and shield", t: ["mask", "shield", "ppe"], cap: "Mask and shield — protecting eyes, nose and mouth from splashes." },
  { c: "instruments", q: "sterile surgical instruments tray forceps scissors", t: ["instruments", "forceps", "sterile", "tray"], cap: "A sterile instrument tray — every tool laid out and counted." },
  { c: "instruments", q: "nursing delivery kit instruments", t: ["delivery", "kit", "instruments"], cap: "The delivery kit — what a nurse checks before every birth." },
  { c: "sterilization", q: "autoclave machine hospital sterilization", t: ["autoclave", "sterilization", "instruments"], cap: "The autoclave — steam under pressure for true sterilisation." },
  { c: "wounds", q: "nurse dressing wound bandage", t: ["wound", "dressing", "bandage"], cap: "Wound dressing — clean technique, gentle hands, dated tape." },
  { c: "wounds", q: "pressure ulcer stages wound care", t: ["pressure", "ulcer", "wound", "skin"], cap: "Pressure ulcers — what unrelieved pressure does to skin over bone." },
  { c: "injections", q: "intramuscular injection technique thigh", t: ["injection", "intramuscular", "vaccination"], cap: "IM injection — quick, confident and in the right landmark." },
  { c: "injections", q: "subcutaneous injection insulin technique", t: ["injection", "subcutaneous", "insulin"], cap: "Subcutaneous injection — into the fat, not the muscle." },
  { c: "medications", q: "medicine vials and ampoules with syringes", t: ["medication", "vials", "injection"], cap: "Vials and ampoules — check the label three times." },
  { c: "medications", q: "oral tablets medication pills", t: ["tablets", "medication", "oral"], cap: "Oral medicines — right patient, drug, dose, route and time." },
  { c: "iv", q: "IV infusion drip bag patient hand", t: ["intravenous", "infusion", "fluids"], cap: "An IV drip — fluids running at the rate the patient needs." },
  { c: "iv", q: "blood transfusion bag hospital", t: ["transfusion", "blood", "infusion"], cap: "Blood transfusion — matched, labelled and watched closely." },
  { c: "vitals", q: "blood pressure cuff measurement arm", t: ["blood", "pressure", "vital", "measurement"], cap: "Taking blood pressure — cuff, valve and a trained ear." },
  { c: "vitals", q: "nurse checking patient temperature thermometer", t: ["temperature", "thermometer", "vital"], cap: "Temperature — the vital sign that announces infection." },
  { c: "vitals", q: "chest auscultation with stethoscope", t: ["stethoscope", "auscultation", "chest", "lung"], cap: "Auscultation — listening to the lungs breath by breath." },
  { c: "vitals", q: "pulse oximeter finger measurement", t: ["oxygen", "saturation", "vital"], cap: "The pulse oximeter — oxygen saturation in a single clip." },
  { c: "vitals", q: "pinard stethoscope fetal heart auscultation", t: ["pinard", "fetal", "heart", "auscultation"], cap: "The Pinard — low-tech listening for the fetal heartbeat." },
  { c: "vitals", q: "fetal doppler monitoring heartbeat", t: ["doppler", "fetal", "heart", "monitoring"], cap: "The Doppler — counting the fetal heart rate in seconds." },

  // ── Microbiology ────────────────────────────────────────
  { c: "microbiology", q: "bacteria culture petri dish colonies", t: ["bacteria", "culture", "microbiology"], cap: "Bacterial colonies on a plate — each dot a city of microbes." },
  { c: "microbiology", q: "virus particles electron microscope", t: ["virus", "microbiology", "microbes"], cap: "Viruses up close — hijackers far smaller than any cell." },
  { c: "microbiology", q: "candida yeast fungus under microscope", t: ["fungus", "candida", "microbiology"], cap: "Candida — the yeast behind thrush in mothers and babies." },
  { c: "microbiology", q: "malaria parasite in blood smear microscope", t: ["malaria", "parasite", "blood"], cap: "Malaria parasites in a blood smear — a slide that saves lives." },
  { c: "microbiology", q: "intestinal worm eggs stool microscopy", t: ["worm", "parasite", "stool"], cap: "Worm eggs on a stool slide — the quiet cause of childhood anaemia." },
  { c: "microbiology", q: "anopheles mosquito malaria vector", t: ["mosquito", "malaria", "vector"], cap: "The Anopheles mosquito — the vector that carries malaria." },

  // ── Ward, community, wider curriculum ───────────────────
  { c: "ward", q: "hospital ward beds patients Africa", t: ["ward", "hospital", "beds", "patients"], cap: "A hospital ward — the classroom where most learning happens." },
  { c: "ward", q: "nurse making hospital bed patient", t: ["bed", "making", "ward", "comfort"], cap: "Bed-making — comfort, safety and dignity in one skill." },
  { c: "communication", q: "nurse listening to patient bedside", t: ["communication", "patient", "listening"], cap: "Listening — the strongest instrument on your belt." },
  { c: "documentation", q: "nurse writing notes patient chart", t: ["documentation", "chart", "notes"], cap: "Charting — if it isn't written, it didn't happen." },
  { c: "community", q: "community health worker Ghana village", t: ["community", "health", "ghana", "worker"], cap: "Community health workers — care that travels to the last house." },
  { c: "community", q: "health education session community Ghana", t: ["health", "education", "community", "teaching"], cap: "Health education — knowledge shared is health multiplied." },
  { c: "community", q: "mosquito net insecticide treated Ghana", t: ["malaria", "prevention", "net"], cap: "A treated mosquito net — sleeping under protection." },
  { c: "nutrition", q: "balanced diet food groups plate", t: ["nutrition", "diet", "food"], cap: "A balanced plate — the GO, GROW and GLOW of everyday eating." },
  { c: "nutrition", q: "healthy local Ghanaian foods meal", t: ["nutrition", "ghana", "food", "diet"], cap: "Local foods — kenkey, kontomire and tilapia are nutrition too." },
  { c: "water", q: "clean drinking water sachet Ghana", t: ["water", "sanitation", "hygiene"], cap: "Clean water — the most basic prescription in community health." },
  { c: "family-planning", q: "family planning contraception methods options", t: ["family", "planning", "contraception"], cap: "Family planning methods — choices every woman deserves to know." },
  { c: "family-planning", q: "oral contraceptive pills package", t: ["pills", "contraception", "family", "planning"], cap: "The pill — daily consistency is what makes it work." },
  { c: "family-planning", q: "IUD intrauterine device copper", t: ["iud", "contraception", "family", "planning"], cap: "The IUD — long-acting protection that forgets nothing." },
  { c: "family-planning", q: "condoms hiv prevention", t: ["condom", "prevention", "protection"], cap: "Condoms — protection that is both family planning and infection control." },
  { c: "emergency", q: "hospital emergency team resuscitation", t: ["emergency", "resuscitation", "team"], cap: "An emergency response — roles rehearsed before the alarm ever sounds." },
  { c: "emergency", q: "emergency obstetric care transfer ambulance", t: ["emergency", "obstetric", "referral", "transport"], cap: "Referral transport — minutes between home and theatre decide outcomes." },
  { c: "leadership", q: "healthcare team meeting discussion", t: ["leadership", "team", "meeting"], cap: "A team huddle — leadership is mostly listening and planning." },
  { c: "research", q: "health researcher collecting data survey Africa", t: ["research", "data", "survey"], cap: "Data collection — where good research begins." },
  // ── VARIETY EXPANSION (dedupe across lessons) ─────────────
  { c: "cells", q: "electron microscope cell organelle ultrastructure", t: ["cell", "organelles", "microscope"], cap: "An electron micrograph — the cell revealed at molecular detail." },
  { c: "cells", q: "white blood cell phagocytosis microscopy", t: ["cell", "immunity", "phagocytosis"], cap: "A white cell engulfing bacteria — immunity you can see." },
  { c: "cells", q: "osmosis diffusion cell membrane experiment diagram", t: ["cell", "membrane", "transport", "osmosis"], cap: "Osmosis in action — water moving where solutes call it." },
  { c: "tissues", q: "muscle tissue histology section stained", t: ["tissue", "muscle", "histology"], cap: "Muscle histology — striped, striped, contracting." },
  { c: "tissues", q: "nervous tissue neuron histology slide", t: ["tissue", "nerve", "neuron"], cap: "Nervous tissue — the wiring of thought and reflex." },
  { c: "skin", q: "skin epidermis dermis histology microscope", t: ["skin", "histology", "layers"], cap: "Skin under the microscope — layers doing different jobs." },
  { c: "skin", q: "pressure sore sacrum clinical photograph", t: ["skin", "pressure", "wound", "ulcer"], cap: "A pressure ulcer over the sacrum — what unrelieved pressure costs." },
  { c: "skeleton", q: "fetal skull bones fontanelle anatomy", t: ["skull", "fontanelle", "fetal", "bones"], cap: "The fetal skull — sutures and fontanelles that mould through birth." },
  { c: "skeleton", q: "pelvic diameters female pelvis diagram anatomy", t: ["pelvis", "diameters", "anatomy", "labour"], cap: "Pelvic diameters — the measurements birth must fit through." },
  { c: "skeleton", q: "vertebral column spine anatomy labeled", t: ["spine", "vertebrae", "skeleton"], cap: "The vertebral column — the pillar the pelvis hangs from." },
  { c: "muscles", q: "perineal muscles pelvic floor anatomy diagram", t: ["perineum", "pelvic", "floor", "muscles"], cap: "The pelvic floor — the birth canal's living floor." },
  { c: "muscles", q: "uterus myometrium muscle layers", t: ["uterus", "muscle", "myometrium"], cap: "The uterine muscle layers — the engine of labour." },
  { c: "heart", q: "human heart anatomy model photo", t: ["heart", "anatomy", "model"], cap: "A heart model — four chambers held in two hands." },
  { c: "heart", q: "ECG electrocardiogram rhythm strip", t: ["ecg", "heart", "rhythm", "cardiac"], cap: "An ECG strip — the heart's rhythm written in electricity." },
  { c: "heart", q: "fetal circulation diagram placenta", t: ["fetal", "circulation", "placenta", "heart"], cap: "Fetal circulation — the placenta is the fetus's lungs before birth." },
  { c: "blood", q: "blood smear platelets microscopy", t: ["blood", "platelets", "clotting"], cap: "Platelets on a smear — the tiny plugs that stop the bleeding." },
  { c: "blood", q: "hemoglobin red blood cells anemia", t: ["blood", "hemoglobin", "anaemia"], cap: "Haemoglobin-rich red cells — the oxygen couriers." },
  { c: "blood", q: "blood group typing test slide", t: ["blood", "group", "typing"], cap: "Blood grouping — the slide that decides transfusion safety." },
  { c: "lungs", q: "chest x-ray normal anatomy", t: ["chest", "x-ray", "lungs", "radiology"], cap: "A chest X-ray — the shadow picture that reveals the lungs." },
  { c: "lungs", q: "neonatal incubator oxygen therapy hospital", t: ["newborn", "oxygen", "lungs", "respiratory"], cap: "Oxygen support for a newborn — gentle help while lungs mature." },
  { c: "digestion", q: "stomach intestine anatomy model", t: ["digestive", "stomach", "anatomy"], cap: "The digestive organs — a model you can walk through." },
  { c: "kidneys", q: "urinary system kidneys bladder anatomy model", t: ["kidney", "urinary", "bladder", "anatomy"], cap: "The urinary system — filtration, storage, release." },
  { c: "kidneys", q: "urine dipstick test strips laboratory", t: ["urine", "dipstick", "test", "antenatal"], cap: "The urine dipstick — protein and glucose screened in seconds." },
  { c: "nerves", q: "peripheral nerve histology cross section", t: ["nerve", "histology", "peripheral"], cap: "A peripheral nerve in cross-section — cables within cables." },
  { c: "endocrine", q: "pituitary gland hypothalamus diagram", t: ["pituitary", "endocrine", "hormones"], cap: "The pituitary — the conductor of the hormonal orchestra." },
  { c: "endocrine", q: "adrenal gland anatomy", t: ["adrenal", "endocrine", "glands"], cap: "The adrenal glands — stress hormones and salt balance." },
  { c: "repro-female", q: "uterus cervix vagina anatomical model", t: ["uterus", "cervix", "anatomy", "female"], cap: "An anatomical model — the pelvis contents in one view." },
  { c: "repro-female", q: "hysterosalpingography fallopian tubes x-ray", t: ["fallopian", "tubes", "fertility"], cap: "A tubal X-ray — checking the road egg and sperm must meet on." },
  { c: "repro-female", q: "ovulation follicle development ovary diagram", t: ["ovulation", "follicle", "ovary"], cap: "Follicle to corpus luteum — the ovary's monthly story." },
  { c: "repro-female", q: "speculum gynecological examination instrument", t: ["speculum", "examination", "gynecology"], cap: "The speculum — warmed, gentled, and always explained first." },
  { c: "repro-cycle", q: "ovarian cycle hormones FSH LH diagram", t: ["cycle", "hormones", "ovulation"], cap: "FSH and LH — the hormones that time the whole cycle." },
  { c: "repro-embryo", q: "human embryo Carnegie stage illustration", t: ["embryo", "development", "stages"], cap: "Embryo stages — week by week, shape before function." },
  { c: "repro-embryo", q: "twins ultrasound twin pregnancy scan", t: ["twins", "ultrasound", "pregnancy"], cap: "A twin pregnancy scan — two heartbeats to count." },
  { c: "repro-genetics", q: "DNA double helix molecular model", t: ["dna", "genetics", "chromosomes"], cap: "The DNA double helix — the code of inheritance." },
  { c: "repro-genetics", q: "pedigree chart inheritance diagram", t: ["genetics", "inheritance", "pedigree"], cap: "A family pedigree — patterns of inheritance drawn across generations." },
  { c: "repro-genetics", q: "down syndrome trisomy karyotype", t: ["genetics", "karyotype", "trisomy", "screening"], cap: "A trisomy karyotype — why antenatal screening exists." },
  { c: "pregnancy", q: "obstetric ultrasound machine clinic examination", t: ["ultrasound", "pregnancy", "clinic"], cap: "The ultrasound machine — windows into the womb." },
  { c: "pregnancy", q: "pregnant woman urine test pregnancy test", t: ["pregnancy", "test", "urine"], cap: "The pregnancy test — the small strip that starts a big journey." },
  { c: "pregnancy", q: "antenatal class pregnant women group education", t: ["antenatal", "education", "class"], cap: "Antenatal class — questions answered before they're urgent." },
  { c: "pregnancy", q: "pregnant woman exercise walking", t: ["pregnancy", "exercise", "health"], cap: "Activity in pregnancy — gentler, but still daily." },
  { c: "pregnancy", q: "eclampsia magnesium sulfate treatment intravenous", t: ["eclampsia", "magnesium", "treatment"], cap: "Magnesium sulfate — the eclampsia drug that guards the brain." },
  { c: "pregnancy", q: "anaemia pregnancy iron deficiency blood test", t: ["anaemia", "iron", "pregnancy", "blood"], cap: "Anaemia in pregnancy — screened, treated, and re-checked." },
  { c: "labour", q: "cervical dilation effacement diagram childbirth", t: ["cervix", "dilation", "labour", "stages"], cap: "Dilation and effacement — the cervix thinning and opening." },
  { c: "labour", q: "epidural anesthesia labour pain relief", t: ["labour", "pain", "relief", "epidural"], cap: "Pain relief options — every woman's choice, informed." },
  { c: "labour", q: "obstetric emergency drill simulation training", t: ["emergency", "simulation", "training", "labour"], cap: "Emergency drills — rehearsing the day you hope never comes." },
  { c: "labour", q: "vacuum extraction assisted delivery instrument", t: ["vacuum", "assisted", "delivery", "instruments"], cap: "The vacuum cup — assisted birth with the right conditions." },
  { c: "labour", q: "birth crowning head delivery photograph", t: ["birth", "crowning", "delivery", "head"], cap: "Crowning — the moment of no return, gently guided." },
  { c: "labour", q: "newborn first cry stimulation drying", t: ["newborn", "resuscitation", "cry", "drying"], cap: "Drying and stimulating — the first actions of the Golden Minute." },
  { c: "newborn", q: "newborn apgar scoring assessment", t: ["apgar", "newborn", "assessment"], cap: "APGAR at one and five minutes — the first report card." },
  { c: "newborn", q: "newborn Vitamin K injection prophylaxis", t: ["vitamin", "newborn", "injection", "prophylaxis"], cap: "Vitamin K at birth — protecting against bleeding disease." },
  { c: "newborn", q: "newborn eye examination red reflex ophthalmoscope", t: ["newborn", "eyes", "examination", "red reflex"], cap: "The red reflex — a healthy glow from a clear eye." },
  { c: "newborn", q: "newborn hearing screening test", t: ["newborn", "hearing", "screening"], cap: "Newborn hearing screening — sounds checked before words come." },
  { c: "newborn", q: "neonatal jaundice yellow skin baby", t: ["jaundice", "newborn", "yellow", "bilirubin"], cap: "Jaundice in a newborn — watch the eyes, watch the timing." },
  { c: "newborn", q: "baby bath newborn sponge bathing demonstration", t: ["newborn", "bath", "hygiene", "care"], cap: "Newborn bathing — warm room, warm water, gentle hands." },
  { c: "newborn", q: "low birth weight baby weighing", t: ["low", "birth", "weight", "newborn"], cap: "Low birth weight — small size, big watchfulness." },
  { c: "feeding", q: "lactation breast anatomy milk ducts diagram", t: ["lactation", "breast", "anatomy", "milk"], cap: "The milk factory — alveoli and ducts that answer the suck." },
  { c: "feeding", q: "expressing breast milk manual pump", t: ["expressing", "milk", "pump", "feeding"], cap: "Expressing milk — by hand or pump, the skill that feeds separation." },
  { c: "feeding", q: "baby feeding bottle formula preparation", t: ["formula", "bottle", "feeding"], cap: "Safe formula feeding — when breastfeeding isn't possible, clean technique matters." },
  { c: "feeding", q: "mastitis breast inflammation breastfeeding", t: ["mastitis", "breastfeeding", "feeding"], cap: "Mastitis — the tender, red, painful quarter that needs feeding THROUGH." },
  { c: "hygiene", q: "WHO hand hygiene technique steps diagram", t: ["hand", "hygiene", "technique"], cap: "The six handwashing steps — palm, back, between, nails, thumbs, wrists." },
  { c: "hygiene", q: "surgical scrub brush hands operation", t: ["surgical", "scrub", "hand", "asepsis"], cap: "The surgical scrub — nails first, hands up, water running down." },
  { c: "hygiene", q: "isolation room infection control hospital", t: ["isolation", "infection", "control"], cap: "Isolation precautions — barriers that protect the many." },
  { c: "ppe", q: "N95 respirator mask fitting healthcare", t: ["mask", "n95", "respirator", "ppe"], cap: "Respirator fit — a seal checked before the hazard is met." },
  { c: "ppe", q: "protective apron gown healthcare worker", t: ["apron", "gown", "protection"], cap: "The plastic apron — splash protection changed between patients." },
  { c: "instruments", q: "surgical scissors needle holder instruments closeup", t: ["scissors", "instruments", "suture", "sterile"], cap: "Suture instruments — named, counted, and never borrowed mid-case." },
  { c: "instruments", q: "episiotomy repair instruments delivery set", t: ["episiotomy", "repair", "instruments"], cap: "The repair set — needle holder, scissors, and a steady hand." },
  { c: "instruments", q: "artery forceps clamp instrument surgical", t: ["forceps", "clamp", "instruments", "sterile"], cap: "Artery forceps — the clamp that controls the bleed." },
  { c: "sterilization", q: "instrument tray wrapped sterile indicator tape", t: ["sterile", "tray", "pack", "indicator"], cap: "A sterile pack — the indicator tape that says 'trust me'." },
  { c: "sterilization", q: "chemical disinfection antiseptic solution bottles", t: ["disinfection", "antiseptic", "sterilization"], cap: "Antiseptics and disinfectants — cleaning levels, from skin to surfaces." },
  { c: "wounds", q: "wound debridement dressing clinical", t: ["wound", "dressing", "debridement"], cap: "Wound dressing — clean from clean to dirty, never backwards." },
  { c: "wounds", q: "surgical wound healing stitches suture", t: ["wound", "healing", "sutures"], cap: "A healing surgical wound — approximation, circulation, protection." },
  { c: "injections", q: "vaccination syringe preparation drawing up", t: ["vaccination", "injection", "syringe", "preparation"], cap: "Drawing up a vaccine — air in, vaccine drawn, bubbles out." },
  { c: "injections", q: "sharps container disposal needles", t: ["sharps", "disposal", "safety", "injection"], cap: "The sharps container — needles go in point-first, never recapped." },
  { c: "injections", q: "intravenous cannula insertion arm", t: ["cannula", "iv", "insertion", "vein"], cap: "IV cannulation — the vein chosen, the tourniquet released." },
  { c: "medications", q: "pharmacy medicines dispensing shelves", t: ["pharmacy", "medication", "dispensing"], cap: "The pharmacy — labelled, stored, and counted." },
  { c: "medications", q: "oral rehydration salts sachet WHO", t: ["ors", "rehydration", "diarrhea", "treatment"], cap: "ORS — the sachet that saves children from dehydration." },
  { c: "medications", q: "amoxicillin antibiotic capsules", t: ["antibiotic", "capsules", "medication"], cap: "Antibiotics — the right drug, dose, and duration." },
  { c: "iv", q: "IV drip chamber infusion set closeup", t: ["intravenous", "infusion", "drip"], cap: "The drip chamber — drop counting is rate control." },
  { c: "iv", q: "giving set blood transfusion laboratory crossmatch", t: ["transfusion", "blood", "crossmatch"], cap: "Crossmatching — the lab step that makes blood safe." },
  { c: "vitals", q: "digital blood pressure monitor display", t: ["blood", "pressure", "monitor", "measurement"], cap: "A digital BP monitor — still needs the right cuff and calm arm." },
  { c: "vitals", q: "respiratory rate counting watch timer", t: ["respiratory", "rate", "vital", "measurement"], cap: "Counting breaths — with a watch the patient can't see." },
  { c: "vitals", q: "fetal heart rate monitor cardiotocography CTG", t: ["fetal", "heart", "ctg", "monitoring", "labour"], cap: "Continuous fetal monitoring — the strip that tells the baby's story." },
  { c: "microbiology", q: "gram stain bacteria microscopy slide", t: ["bacteria", "gram", "stain", "microbiology"], cap: "Gram staining — purple or pink, the first bacterial ID." },
  { c: "microbiology", q: "streptococcus bacteria chain microscope", t: ["bacteria", "streptococcus", "microbiology"], cap: "Streptococcus in chains — the Group B screened in pregnancy." },
  { c: "microbiology", q: "HIV virus structure diagram", t: ["hiv", "virus", "immunity"], cap: "HIV — the virus counselling and testing guard against." },
  { c: "microbiology", q: "tuberculosis mycobacteria acid fast stain", t: ["tuberculosis", "microbiology", "stain"], cap: "Acid-fast bacilli — the red rods that announce TB." },
  { c: "microbiology", q: "antibiotic sensitivity test disc agar", t: ["antibiotic", "sensitivity", "microbiology", "culture"], cap: "Sensitivity testing — which drug the bug still fears." },
  { c: "ward", q: "hospital corridor nurses station", t: ["ward", "hospital", "nurses"], cap: "The nurses' station — the ward's cockpit." },
  { c: "ward", q: "patient bedside monitoring vital signs", t: ["ward", "monitoring", "patient", "vitals"], cap: "Bedside monitoring — eyes before monitors, always." },
  { c: "communication", q: "doctor nurse patient consultation talking", t: ["communication", "consultation", "patient"], cap: "The consultation — sitting at eye level changes everything." },
  { c: "communication", q: "interpreter health worker patient language barrier", t: ["communication", "interpreter", "language"], cap: "Working across languages — the interpreter as bridge, not barrier." },
  { c: "documentation", q: "medical records folder paper charts archive", t: ["documentation", "records", "charts"], cap: "Medical records — yesterday's notes are tomorrow's evidence." },
  { c: "documentation", q: "computer hospital information system data entry", t: ["documentation", "digital", "records"], cap: "Digital records — legible, searchable, backed up." },
  { c: "community", q: "village health outreach rural clinic Africa", t: ["community", "outreach", "rural", "clinic"], cap: "Rural outreach — care meeting people where they live." },
  { c: "community", q: "immunization campaign child vaccination Africa", t: ["immunization", "campaign", "vaccination"], cap: "Immunisation day — queues of little arms, lifetimes of protection." },
  { c: "community", q: "home visit community nurse elderly patient", t: ["community", "home", "visit", "nursing"], cap: "The home visit — the house tells the story the clinic can't." },
  { c: "community", q: "community meeting health education village elders", t: ["community", "meeting", "leaders", "education"], cap: "Community entry — leaders first, health second." },
  { c: "nutrition", q: "food group balanced meal plate demonstration", t: ["nutrition", "food", "groups", "diet"], cap: "Food groups on one plate — variety is the rule." },
  { c: "nutrition", q: "measuring mid upper arm circumference MUAC child", t: ["muac", "nutrition", "assessment", "child"], cap: "MUAC tape — malnutrition screened in one wrap." },
  { c: "nutrition", q: "oranges vitamin C fruits food", t: ["nutrition", "vitamin", "fruits"], cap: "Vitamin C foods — healing, absorption, immunity." },
  { c: "water", q: "hand pump well clean water village Africa", t: ["water", "sanitation", "village", "pump"], cap: "The village pump — clean water at the heart of health." },
  { c: "water", q: "boiling water purification pot stove", t: ["water", "boiling", "purification", "household"], cap: "Boiling water — household purification at its simplest." },
  { c: "family-planning", q: "family planning counselling clinic couple", t: ["family", "planning", "counselling"], cap: "Family planning counselling — method choice belongs to the couple." },
  { c: "family-planning", q: "contraceptive implant insertion arm procedure", t: ["implant", "contraception", "insertion"], cap: "The implant — a five-minute procedure, years of protection." },
  { c: "family-planning", q: "injectable contraception depot injection", t: ["injectable", "contraception", "depo"], cap: "The contraceptive injection — discreet and every three months." },
  { c: "family-planning", q: "calendar rhythm natural family planning", t: ["natural", "family", "planning", "cycle"], cap: "Natural methods — knowledge of the cycle as the tool." },
  { c: "emergency", q: "cardiopulmonary resuscitation CPR training manikin", t: ["cpr", "resuscitation", "training", "emergency"], cap: "CPR on a manikin — 100 compressions a minute, muscle memory." },
  { c: "emergency", q: "ambulance loading patient transfer", t: ["ambulance", "transfer", "referral", "emergency"], cap: "The ambulance transfer — care continues in motion." },
  { c: "emergency", q: "emergency triage tags color patients", t: ["triage", "emergency", "tags"], cap: "Triage tags — the colors that order the chaos." },
  { c: "emergency", q: "obstetric hemorrhage emergency drill", t: ["obstetric", "emergency", "hemorrhage", "drill"], cap: "The PPH drill — roles rehearsed, drugs within reach." },
  { c: "leadership", q: "nurse team leader briefing shift handover", t: ["leadership", "handover", "team", "shift"], cap: "Shift handover — the two minutes that decide continuity." },
  { c: "leadership", q: "quality improvement meeting hospital staff", t: ["quality", "improvement", "leadership", "meeting"], cap: "Quality improvement — small changes measured honestly." },
  { c: "research", q: "statistical graph chart data analysis", t: ["research", "statistics", "data", "analysis"], cap: "Data visualised — the pattern the numbers were hiding." },
  { c: "research", q: "informed consent form signing research participant", t: ["research", "consent", "ethics"], cap: "Informed consent — understanding verified, not assumed." },
  { c: "research", q: "focus group discussion qualitative research", t: ["research", "qualitative", "focus", "group"], cap: "A focus group — the research that hears the quiet voices." },
];
